### ISSUE TITLE
Support for http/2

### ISSUE THREAD

**Issue by misner** [rack/rack#1000]
Read a great article about http/2 and how it will contribute to Rails performance: https://www.nateberkopec.com/2016/01/07/what-http2-means-for-ruby-developers.html

Is the rake core team working on a true and complete http/2 support for Rails rack?
Is there any date planned for release ?

**Comment by raggi** [comment]
Rack is not a webserver. Although some things could be added to the Rack spec to add support for special things, this needs to start with webserver support.

Also, this is Rack, not "rails rack"

**Comment by misner** [comment]
ok thanks for your answer
