### ISSUE TITLE
rackup -O SSLEnable doesn't work for WEBrick

### ISSUE THREAD

**Issue by dgbustos** [rack/rack#1013]
The WEBrick documentation indicates that enabling SSL should be done with `require 'webrick/https'` and passing `SSLEnable => true` as an option.  `rackup -O SSLEnable` does the second, but not the first.  I think this can be fixed by adding

``` ruby
    if options[:SSLEnable]
      require 'webrick/https'
    end
```

to the `run` method in `Rack::Handler::WEBrick`.

**Comment by ioquatix** [comment]
Fixed.
