### ISSUE TITLE
Memcache-client gem is not maintained anymore and recommand to switch to dalli

### ISSUE THREAD

**Issue by sbadia** [rack/rack#1025]
Hi here,

According upstream (https://github.com/mperham/memcache-client/commit/42a9472782f7d2919b4064e8dc918aecc69c5cb6) [memcache-client](https://github.com/mperham/memcache-client) is deprecated as of August 2010. It will be supported through 2010 but new code should use [Dalli](https://github.com/petergoldstein/dalli) instead.

Thanks in advance!

**Comment by simi** [comment]
I can take a look in switch to Dalli, but maybe it will make more sense to move `Rack::Session::Memcache` to own gem.

**Comment by simi** [comment]
Alternatively it can be moved to `rack-contrib`.
