### ISSUE TITLE
cookie parse error when there are multi-cookies

### ISSUE THREAD

**Issue by wavezhang** [rack/rack#1039]
when there are muti-cookies in request header like following:

`Cookie: request_method=POST; _session=bd18bc9ca6b72901fb4939484c2b92fa`

note that there is a space after semicolon and it will be encode into

`request_method=POST;%20_session=bd18bc9ca6b72901fb4939484c2b92fa`

and parse_query function will return

`{
"request_method":"POST",
" _session":"bd18bc9ca6b72901fb4939484c2b92fa"
}`

with a space in key name 
this patch fix this problem [strip key name when pares query](https://github.com/rack/rack/compare/1-6-stable...wavezhang:patch-1)

**Comment by jeremyevans** [comment]
This works correctly in current rack.  There is no cookie-specific test for it, but I will add one.
