### ISSUE TITLE
request.ip should select first IP address

### ISSUE THREAD

**Issue by maletor** [rack/rack#1049]
Specifically, Rack::Request and ActionDispatch::RemoteIp::GetIp use different ordinality (`.last` vs `.first`) to fetch the forwarded IP address (the original visitor's address).

https://github.com/rack/rack/blob/master/lib/rack/request.rb#L281

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L147

It seems to me that when multiple X-Forwarded-For addresses are given, they are always listed with the originator first (e.g., client, proxy, proxy).

However, it's entirely possible this is working correctly by accident since most X-Forwarded-For addresses do not include multiple proxies.

**Comment by maletor** [comment]
Ok, so it appears they both pull the same, rightmost ip address since `forwarded_ips` is reversed in ActionDispath::RemoteIp::GetIp 

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L116

So in a scenario where there are a header `X-Forwarded-For: REAL_IP, CLOUDFLARE, NGINX (localhost)` we would want the leftmost one? Currently, the code would return a Cloudflare IP.

**Comment by smathy** [comment]
The code seems to have focused only on proxies within the web host's own network, these methods break down for any public-proxy situation.

A public proxy will take the incoming `REMOTE_ADDR` and add it *to the end* of `XFF`/`Client-IP`, so if it's a public proxy then that public IP at the end of `XFF` will now be what `request.ip` returns.

The algorithm should be:

 1. Remove all private IPs from `XFF/Client-IP`
 2. Take the *leftmost* IP from `XFF/Client-IP`
 3. If none then fall back to `REMOTE_ADDR`

**Comment by jeremy** [comment]
@smathy The idea is that public proxies can't be trusted either.

There's a long history behind the current behavior. Thorough discussion: http://blog.gingerlime.com/2012/rails-ip-spoofing-vulnerabilities-and-protection/

Check out https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L52-L59 for providing additional trusted (possibly public) proxies.

**Comment by maletor** [comment]
@jeremy, I see where I went wrong. The tl;dr; sums it up nicely there. Thanks for taking a look.

**Comment by smathy** [comment]
@jeremy so because you can't trust what a client tells you then the method that people expect to return that untrusted client IP instead returns the IP of the closest public proxy to the host?

**Comment by jeremy** [comment]
@smathy Yep! You can think of it as returning the furthest "real" IP in the forwarding chain.

**Comment by smathy** [comment]
Ok, good to know. I can't imagine ever wanting that, but thanks for the clarification.
