### ISSUE TITLE
request IP should be originating client IP

### ISSUE THREAD

**Issue by davetroiano** [rack/rack#1055]
[This line](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L281) sets ip to the last ip of the HTTP_X_FORWARDED_FOR list.  This header goes from client to each successive proxy so we want the first, not last, IP in that list, in order to get the originating client IP.

**Comment by jeremy** [comment]
It's selecting the outermost IP that we can trust to not be spoofed.

[Some history](https://github.com/rack/rack/issues?q=request+ip):
- https://github.com/rack/rack/issues/1049
- https://github.com/rack/rack/pull/705
- https://github.com/rack/rack/issues/691
- https://github.com/rack/rack/pull/192
- https://github.com/rack/rack/issues/1
