### ISSUE TITLE
Possible regression from previous refactoring of multipart parser

### ISSUE THREAD

**Issue by Tony-D** [rack/rack#1057]
I was investigating an issue in an app running an older version of Rack in which params were not fully parsing. It turns out, it seems to be a legitimate issue in Rack for all versions < 1.3. Essentially, if a content-boundary ends precisely at a multiple of the buffer (16384) and that multiple is greater than 1, the remaining content is not parsed (i'm aware this was fixed for multiples of 1 in a9440bc752be9b3093669614c6b56bf78d592958).

I then tried to find the commit in which this issue was addressed and to my surprise it appears to have been fixed accidentally during a refactoring of the multipart-parser (24d512531bd88f2d6ce94b3a3d9798fde8fbb713).

The root of it seems to be that the scoping of a regular expression changed during this refactoring. When evaluating the following line to determine if parsing should continue, the value of $1 changes after the refactoring:

``` ruby
break if (buf.empty? && $1 != EOL) || content_length == -1
```

Using the attached test case, $1 was evaluating to nil before and EOL afterwards, which causes it to break prematurely before the change was made.

Is this expected? I imagine it was not intentional to have this functionality change after the refactoring. Although my initial bug is fixed now, i'm unsure what else this could have possibly changed.

[test_case.zip](https://github.com/rack/rack/files/231171/test_case.zip)

**Comment by jeremyevans** [comment]
The line of code in question was removed in 360d374ab1a263fcf81a18d6e5ac74cccccbc7e9.  The test case provided currently parses fine, and Rack <1.3 is no longer supported.
