### ISSUE TITLE
After/between request callback

### ISSUE THREAD

**Issue by maxnordlund** [rack/rack#1060]
Hi, I couldn't find an issue with this so here it goes.

I would like to run some code after the request has been flushed to the client but before the next request. Essentially be able to queue up some work per request without affecting the load time. An example is to defer some logging/profiling, or send an email.

Is this possible to do this already? Or is it possible to add? Thoughts and feedback more then welcome.

**Comment by janko-m** [comment]
@maxnordlund I think `Rack::BodyProxy` is what you're looking for. You can wrap your response body that you would return in a `Rack::BodyProxy` object, pass it a block to be called when response body is closed, and return the `Rack::BodyProxy` object as your response body.

```rb
Rack::BodyProxy.new(body) do
  # will be executed after response body has been written to the client
end
```

**Comment by maxnordlund** [comment]
Cool, sadly I'm not coding any Ruby/Rails at the moment. But I hope this helps whoever comes by next.

**Comment by jeremy** [comment]
Puma supports this via `env["rack.after_reply"] << -> { do_stuff }`. This is run even if the response body is not closed, such as when an exception is raised in a middleware.
