### ISSUE TITLE
"provide a .run" webrick test causing travis ci builds to fail on ruby-head

### ISSUE THREAD

**Issue by tgrindinger** [rack/rack#1061]
This particular test is causing many travis ci builds to fail on ruby-head (in particular, my recent pull request). The "after" block is calling "shutdown" before the server has a chance to finish starting. Other tests do not cause the issue, since they communicate directly with the server and thus allow the server to finish initialization.

I can think of a few ways to fix this and have tested several, with good results:

1) Easiest, but prone to side effects: issue a "priming" request to the server to ensure it's up when it's ready to shut down
2) Ugly, but very simple: add a busy wait to ensure the server is running before shutdown happens
3) Prettier, but needless complexity?: add a method to the webrick handler that waits until it's running and/or takes a block that will be executed when it's up

I'm ready to submit a pull request for any of these approaches, whenever I get confirmation on which is preferred.

**Comment by jeremy** [comment]
> This particular test is causing many travis ci builds to fail on ruby-head (in particular, my recent pull request)

Got a link to the test that's failing and an example of the failure?

> I can think of a few ways to fix this and have tested several, with good results:

Which do you prefer?

**Comment by tgrindinger** [comment]
https://github.com/rack/rack/blob/master/test/spec_webrick.rb#L108-L124

https://travis-ci.org/rack/rack/jobs/125310602

Took a bit of digging to figure out what's going on. It doesn't happen every time, unfortunately. I could probably restart that build a few times to eventually get it working, but I figured it would be better to deal with the real problem, instead.

Since this is just a test, and it doesn't appear this is a problem that shows up much (at all?) in production, I'm inclined to go with option 2. I don't see a good reason to add more unneeded functionality to a class that's working pretty well already (option 3), and side effects are rarely a good thing (option 1).

**Comment by jeremy** [comment]
Looks like we already have a countdown latch that ensures we wait until the handler is booted: https://github.com/rack/rack/blob/master/test/spec_webrick.rb#L122-L126

The `after` block appears unrelated; it's acting on the other `@server` set up in `before`.

**Comment by tgrindinger** [comment]
that's the server that's causing the problem. `before` sets up the `@server`, the test runs but doesn't use it (thus not allowing it to finish initializing), and `after` tries to call `@server.shutdown` before `@server.state == :Running`

**Comment by jeremy** [comment]
I see! We can fix with another latch.

**Comment by jeremy** [comment]
Hm, doesn't look like the latch hooks at the right spot. It's after the server is instantiated and the handler is mounted, not after it's `:Running`. Same is true for the latch in this test.

**Comment by jeremy** [comment]
#1063
