### ISSUE TITLE
Gem Conflict with Sinatra App

### ISSUE THREAD

**Issue by kylestengline** [rack/rack#1074]
I have a sinatra app with this in the gemfile 
 gem "rake"
gem "pg"
gem "sinatra" tried this uncommented then bundled //, :github => 'sinatra/sinatra', :branch => "master"
//gem "rack", "~> 1.5" commented this out then bundled, uncommented, then bundled again.
gem "sinatra-contrib"
gem "pry"
gem "rspec"
gem “capybara”

I’m getting this error 
`Unable to activate sinatra-1.4.7, because rack-2.0.0.rc1 conflicts with rack (~> 1.5) (Gem::ConflictError)`
 when I try to 
`rackup -p 3000` or `rackup` 
I tried `bundle update rack` and  `bundle update` tried to use the master branch in my gemfile for sinatra, but still getting this error. 
For some reason `bundle exec rackup` is the only way to load the server now. 
Anyone have any ideas or get this error before?

**Comment by arthurnn** [comment]
I think this happens due to the way and where bundler installs your gems.
Gems that are built from source might not leave in the global gem registry, so you need to run with `bundle exec` so setup the right paths.
is that right @indirect?

**Comment by jeremyevans** [comment]
This isn't a bug in rack, it's just that older versions of sinatra stated they weren't compatible with rack 2 (even if they may have worked with it).  Current versions of sinatra support current versions of rack, so you would probably want to upgrade.
