### ISSUE TITLE
Rack::Lint::LintError at /index.erb, a header value must be a String, but the value of 'Content-Type' is a NilClass

### ISSUE THREAD

**Issue by jjgh** [rack/rack#1076]
I'm using https://github.com/migrs/rack-server-pages/ and when in index.erb I'm doing

`<% redirect("page.erb") %>`

I receive this error:

Rack::Lint::LintError at /index.erb
a header value must be a String, but the value of 'Content-Type' is a NilClass

```
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb: in assert
          raise LintError, message...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb: in block in check_headers
        assert("a header value must be a String, but the value of " +...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/utils.rb: in block in each
          yield(k, v.respond_to?(:to_ary) ? v.to_ary.join("\n") : v)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/utils.rb: in each
        super do |k, v|...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/utils.rb: in each
        super do |k, v|...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb: in check_headers
      header.each { |key, value|...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb: in _call
      check_headers headers...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb: in call
      dup._call(env)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb: in call
      @app.call(env)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb: in call
      status, header, body = @app.call(env)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb: in call
      status, headers, body = @app.call(env)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb: in call
      status, headers, body = @app.call(env)...
c:/Ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb: in service
        status, headers, body = @app.call(env)...
c:/Ruby/lib/ruby/2.3.0/webrick/httpserver.rb: in service
      si.service(req, res)...
c:/Ruby/lib/ruby/2.3.0/webrick/httpserver.rb: in run
          server.service(req, res)...
c:/Ruby/lib/ruby/2.3.0/webrick/server.rb: in block in start_thread
          block ? block.call(sock) : run(sock)
```

I'm on Windows 7 64bit running ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32], rack-server-pages 0.0.6 and rack 1.6.4.

I've also posted this as a [rack-server-pages issue](https://github.com/migrs/rack-server-pages/issues/4) but the repository seems unmaintained...

Possibly it has to do with some small change in new Ruby versions? 
Thanks!

**Comment by kevinchandler** [comment]
FWIW I've gotten this same error before using the mail preview gem. There was an error rendering the email, i.e. bug. Maybe something's wrong w/ `page.erb`?

**Comment by jjgh** [comment]
I'm seeing that response.redirect()  works, but using just redirect() produces the error message. 

It's weird because I went looking at a older app I did with rack-server-pages and I was using just redirect()  all over the app and it worked as expected...

**Comment by jeremyevans** [comment]
This was a bug in rack-server-pages, fixed by: https://github.com/migrs/rack-server-pages/commit/b18129ce7d76085de009c616e5e0bef2119329b2
