### ISSUE TITLE
PID file deletion race condition when using Puma

### ISSUE THREAD

**Issue by sophiedeziel** [rack/rack#1077]
I have that same error really well described here:
https://github.com/puma/puma/issues/915

TL;DR : When using Puma, that method of server.rb bellow (Rack) tries to delete the pid file. Every Puma thread executes it and they all see that the file exists. So only the first thread can delete it and every other will raise a `ENOENT No such file tmp/pids/server.pid`

``` ruby
      def write_pid
        ::File.open(options[:pid], ::File::CREAT | ::File::EXCL | ::File::WRONLY ){ |f| f.write("#{Process.pid}") }
        at_exit { ::File.delete(options[:pid]) if ::File.exist?(options[:pid]) }
      rescue Errno::EEXIST
        check_pid!
        retry
      end
```

This is something I'd love to submit a pull request for, but I am not sure of the approach you'd prefer. 

It is clear to me that we could rescue the `Errno::ENOENT`. I'd like to replace the `if` entirely with it but I don't know if you'd like it.

**Comment by chneukirchen** [comment]
The `if` is unnecessary indeed.  Just delete and ignore errors.

**Comment by steakknife** [comment]
This is probably fixed now, yeah?

**Comment by sophiedeziel** [comment]
Yes it is. People will benefit of the fix when a new version is deployed to RubyGems.
