### ISSUE TITLE
multipart POST parameters with UTF-8 names are incorrectly parsed as ASCII-8BIT Strings

### ISSUE THREAD

**Issue by marcinkoziej** [rack/rack#1078]
I have a:
- Padrino app using Rack 2.3.0
- Page uses UTF-8 encoding
- `<form action="(...)" accept-charset="UTF-8" enctype="multipart/form-data" method="post">`
- Form fields with UTF-8 parameters in names: `<input type="radio" name="q[158][Wysyłanie e-maili do polityków]" value="Bardzo bliskie" />`

In POST handler params[:q] contains:
`{"Wysy\xC5\x82anie e-maili do polityk\xC3\xB3w"=>"Bardzo bliskie"}`

Diagnosis:
`Rack::Multipart::Parser` receives the POST body as  ASCII-8BIT encoded String, and then extracts field names using `Rack::Multipart::MULTIPART_CONTENT_DISPOSITION` Regexp (method with longish name `get_current_head_and_filename_and_content_type_and_name_and_body` :P), with _n_ flag (force treating String as ASCII encoded). Even without the Regexp _n_ flag the POST body has ASCII encoding (adding _u_ flag to Regexp will raise an error).

I don't think this is the right behaviour, although RFC1867 suggests that _Field names originally in non-ASCII character sets MAY be encoded using the method outlined in RFC 1522._ 

Rack doesn't parse RFC 1522 field names anyway, so perhaps it should default to UTF-8 encoding?

Workaround:
A workaround is to `force_encode('utf-8')` the param key.

**Comment by jeremyevans** [comment]
Defaulting to UTF-8 would break the use of Rack with other character sets, so it isn't possible.  The Rack SPEC requires request bodies be encoded in ASCII-8BIT, which is the reason the form parameter names are in ASCII-8BIT.

Starting in Rack 2, you can replace the query_parser used to more easily get custom behavior:

```ruby
class QP < Rack::QueryParser
  def self.make_default(key_space_limit, param_depth_limit)
    new Params, key_space_limit, param_depth_limit
  end
  class Params < Rack::QueryParser::Params
    def []=(key, value)
      super(key.force_encoding('UTF-8'), value)
    end
  end
end
Rack::Utils.default_query_parser = QP.make_default(65536, 100)
```

However, you should be prepared to handle the fallout in your application if someone submits non-UTF-8 form parameter names to your application.
