### ISSUE TITLE
Could not find compatible versions for rack

### ISSUE THREAD

**Issue by eduardobarbiero** [rack/rack#1082]
Gem rack works correctly, via inline installation, however when it is via Gemfile, or the dependence of the rails 5.0.0.rc1 , it says not find the gem.
### ERROR:

Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
      actioncable (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
        actionpack (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
          rack (~> 2.x)

Was removed **Gemfile.lock** and made ​​**bundle install** again , remembering what was done the **bundle update** before action .
### System configuration

**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0 and 2.2.2

**Comment by thelamborghinistory** [comment]
+1

**Comment by sembo12** [comment]
Same issue here

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is not a rack issue. Make sure you have compatible gem requirements in your Gemfile (bundler usually tells what is incompatible). If you don't have anything incompatible so you have found a bug in bundler.
