### ISSUE TITLE
Updated History file

### ISSUE THREAD

**Issue by mneumark** [rack/rack#1092]
I stumbled into the discovery that 2.0 came out today. I have had trouble finding any information telling me what is new and how the interface differs, et cetera. Could you update the History file and the README?

**Comment by evanleck** [comment]
I'm with you but in the interim, you can check out the diff from 1.6.4 to 2.0.1 here https://github.com/rack/rack/compare/1.6.4...2.0.1

**Comment by jeremyevans** [comment]
The History file has been removed and replaced by the CHANGELOG.md file, which describes changes in released versions.
