### ISSUE TITLE
Inconsistency in the ordering of (status, headers, body)

### ISSUE THREAD

**Issue by ma11hew28** [rack/rack#1094]
The argument order for `Response#new` (body, status, headers) is inconsistent with that of `MockResponse#new` and the order of elements in the array returned by a Rack application's `call` method (status, headers, body). Related: #1095

**Comment by TechRsch** [comment]
Just ran across this today and my head exploded.  :) Positional parameters are problem enough without randomly reordering them.  I certainly appreciate all the work involved here.  I am currently opening an API to my Rails application for my Rack Middleware application and found these parameters out of order.  I expect there is a problem now, with legacy code.  Perhaps keyword arguments could be an option?  Thanks.

**Comment by ioquatix** [comment]
I've added `Rack::Response[status, headers, body]` and `Rack::MockResponse[status, headers, body]` as a way to mitigate this issue and perhaps in Rack 3.0 we can break this.
