### ISSUE TITLE
Body inconsistency: call, Response, MockResponse

### ISSUE THREAD

**Issue by ma11hew28** [rack/rack#1095]
1. `call`
   
   "The Body itself should not be an instance of String." — [Rack interface specification](http://www.rubydoc.info/github/rack/rack/master/file/SPEC#The_Body)
   
   If it is, an exception is raised.
   
   ``` ruby
   #<NoMethodError: undefined method 'each' for "Hello, World!":String>
   ```
2. `Response`
   
   If the body's a string, it's converted to an array and no exception is raised.
   
   ``` ruby
   response = Rack::Response.new("Hello, World!", 200, {})
   # => . . . @body=["Hello, World!"] . . .
   ```
   
   `Response#body` returns the body as is.
   
   ``` ruby
   response.body
   # => ["Hello, World!"]
   ```
3. `MockResponse`
   
   Like `Response`, if the body's a string, it's converted to an array and no exception is raised.
   
   ``` ruby
   mock_response = Rack::MockResponse.new(200, {}, "Hello, World!")
   # => . . . @body=["Hello, World!"] . . .
   ```
   
   Unlike `Response#body`, `MockResponse#body` converts the body from an array to a string.
   
   ``` ruby
   mock_response.body
   # => "Hello, World!"
   ```

Related: #1094

**Comment by mattdipasquale** [comment]
Related: #1094

**Comment by ioquatix** [comment]
Feel free to submit a PR if you can see a way to resolve this without breaking backwards compatibilty.

Additionally, there are some improvements to `Rack::Response` implemented in master.
