### ISSUE TITLE
Body::each in lib/rack/chunked.rb fails when @body is a string

### ISSUE THREAD

**Issue by kevinmullican** [rack/rack#1096]
This issue arises because ruby >= 1.9 no longer has a String::each method. See line 23:

https://github.com/rack/rack/blob/master/lib/rack/chunked.rb#L23

If @body is a string, the likely best solution is something like:

@body.split($/).each

Obviously, this would necessitate some check (@body.respond_to?('each')) or the like.

**Comment by matthewd** [comment]
If the body is a string, it is not conformant with the [spec](https://github.com/rack/rack/blob/25a549883b85fb33970b4a1530a365c0c9e51f95/SPEC#L245-L248).

**Comment by kevinmullican** [comment]
it seems that the issue is coming from rainbows/unicorn 5.0.0, who suggest the problem is with rack. I'm not too interested in getting in the middle of finger pointing. do you have a workaround?

**Comment by dankegel** [comment]
I work with Kevin, and helped track this down.  Neither of us use Ruby much, hence our difficulty.
I'm posting a followup here in case others in a similar spot happen across this issue.

One problem was in our rackup.ru (I'll show a bit more code than needed, to be kind to newbies):
```
class AppendSlash
  def initialize(app, options={})
    @app = app
    @base = options[:base]
  end
  def call(env)
    if env['REQUEST_URI'] == @base
      [301, {
        'Content-Type' => 'text/html',
        'Location' =>  @base + '/'
        }, '']
    else
      @app.call(env)
    end
  end
end
```
The fix was to change
```
        }, '']
```
to
```
        }, ['']]
```
Likewise, in a few of our apps, we had to change
```
      [200, {
          'Content-Type' => 'text/plain',
          'Content-Length' => data.length.to_s
        }, data
      ]
```
to
```
      [200, {
          'Content-Type' => 'text/plain',
          'Content-Length' => data.length.to_s
        }, [data]
      ]
```
