### ISSUE TITLE
What's new in Rack 2.0 Docs

### ISSUE THREAD

**Issue by gthiruva** [rack/rack#1097]
Are there any docs on Rack 2.0? Like, what's changed to warrant the bump in the major version?

And is the project page still at http://rack.github.io/? The latest item in the _news_ section is from February 2013 about the release of 1.5.2.

**Comment by dijonkitchen** [comment]
It's really obscure, but I found these in the root directory:

https://github.com/rack/rack/blob/master/NEWS
https://github.com/rack/rack/blob/master/HISTORY.md

That covers through end of 2015 as of today, but nothing really specific. 

The pull request milestones don't look to be completed, but there is a non-pre-release for 2.0.0:
https://github.com/rack/rack/milestone/11
https://github.com/rack/rack/releases

Best we've got for now may be to compare the versions with a diff and examine the commits.

**Comment by jeremyevans** [comment]
Changes are now described in `CHANGELOG`, which has been updated to describe what is new in Rack 2.0 and later.
