### ISSUE TITLE
Add in documentation of Rack::MockRequest that `:params` is the key to use when creating a POST-request

### ISSUE THREAD

**Issue by Qqwy** [rack/rack#1098]
Today I spent more than an hour to figure out how make `Rack::MockRequest.post(location, opts)` work.

In the end, it turns out that using the `:params` option is the way to go:

```
Rack::MockRequest.post(location, {params: "test"})
```

This is very badly documented. I would be very happy if this could be added to the documentation of Rack::MockRequest.

**Comment by Qqwy** [comment]
@jeremyevans Could you deliberate why this issue was closed? Is it maybe fixed in the documentation, or is there a reason why it will not be fixed? Thank you! :slightly_smiling_face:

**Comment by jeremyevans** [comment]
GitHub links to the commit that closed this: https://github.com/rack/rack/commit/da8b4ef8781da9cb913a1395814afa615a58d527

Not sure if that shows up in the email GitHub sends, but if not that sounds like something GitHub should fix.

**Comment by Qqwy** [comment]
Apologies, I totally missed that the closing notification in the thread pointed to a commit. 
My mistake :sweat:.

Thank you very much for fixing this!
