### ISSUE TITLE
bug parsing nested parameter url_encoded_form 

### ISSUE THREAD

**Issue by jsnick** [rack/rack#1101]
Hi, I was asked by @maclover7 to open issue here about rails/rails#25920

As you can see, I think there is a problem when parse nested parameters url_encoded_form.

**Comment by tak1n** [comment]
Issue https://github.com/rails/rails/issues/26069 is also caused by this.

```
[1] pry(#<BooksControllerTest>)> params
=> {:id=>1, :book=>{:title=>"Cool", :pages_params=>[{:id=>1, :content=>"another content"}, {:id=>2, :_destroy=>1}, {:content=>"another new page"}]}, :format=>:json}
[2] pry(#<BooksControllerTest>)> query_params = params.to_query
=> "book%5Bpages_params%5D%5B%5D%5Bcontent%5D=another+content&book%5Bpages_params%5D%5B%5D%5Bid%5D=1&book%5Bpages_params%5D%5B%5D%5B_destroy%5D=1&book%5Bpages_params%5D%5B%5D%5Bid%5D=2&book%5Bpages_params%5D%5B%5D%5Bcontent%5D=another+new+page&book%5Btitle%5D=Cool&format=json&id=1"
[3] pry(#<BooksControllerTest>)> Rack::Utils.parse_nested_query(query_params)
=> {"book"=>{"pages_params"=>[{"content"=>"another content", "id"=>"1", "_destroy"=>"1"}, {"id"=>"2", "content"=>"another new page"}], "title"=>"Cool"}, "format"=>"json", "id"=>"1"}
```

**Comment by tak1n** [comment]
Also in rack 1.6.4 the behavior was the same:

```
[1] pry(main)> Rack.release
=> "1.6.4"
[2] pry(main)> Rack::Utils.parse_nested_query("x[y][][z]=1_2&x[y][][id]=1_1&x[y][][id]=2_1&x[y][][_destroy]=2_2&x[y][][z]=3_1&id=1")
=> {"x"=>{"y"=>[{"z"=>"1_2", "id"=>"1_1"}, {"id"=>"2_1", "_destroy"=>"2_2", "z"=>"3_1"}]}, "id"=>"1"}
```

So there must be another reason why controller tests/specs in rails 5 start to fail with nested attributes.

I can think of that in rails 4.2 the `ActionDispatch::ParamsParser` [middleware](https://github.com/rails/rails/blob/v4.2.7.1/actionpack/lib/action_dispatch/middleware/params_parser.rb) was used to parse params and in controller specs this middleware was skipped (params were generated in another way).

And for rails 5 the parsing happens in [`ActionDispatch::Request`](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/request.rb#L366) which `ActionController::TestRequest` finally inherits from.

**Comment by tenshilg** [comment]
Having the same issue with rails 5.0.1 and rack 2.0.1 in API mode
request params:
```
:ordered_coupons_attributes => [
        [0] {
                 :id => 1,
              :count => 10,
            :city_id => 1
        },
        [1] {
                  :id => 2,
            :_destroy => true
        }
    ]
```

In rails controller I got
```
    "ordered_coupons_attributes" => [
        [0] {
                  "id" => "1",
               "count" => "10",
             "city_id" => "1",
            "_destroy" => "true"
        },
        [1] {
            "id" => "2"
        }
    ]
}
```

As a workaround setting request **Content-Type** header to **"application/json"** helped me.

**Comment by jeremyevans** [comment]
This isn't a bug in Rack, it is a just how Rack parses arrays of hashes, appending a new hash to the array when coming across a key that already exists in the current hash.  If you have a an array of hashes that do not share a key, Rack cannot unambiguously parse that because it doesn't know when a new hash should be created. See #1205 for a similar issue.
