### ISSUE TITLE
[Replace or Remove] http://www.fastcgi.com is unavailable on README.rdoc

### ISSUE THREAD

**Issue by ysksn** [rack/rack#1102]
http://www.fastcgi.com is no longer available, so the **FCGI installation example**(from line 160) which on **README.rdoc** should be updated or removed.  I found [FastCGI-Archives/FastCGI.com](https://github.com/FastCGI-Archives/FastCGI.com) on [Wikipedia](https://en.wikipedia.org/wiki/FastCGI) and created a **Docker image** on [Docker Hub](https://hub.docker.com/r/ysksn/dockerfile_fcgi/)(see its [Dockerfile](https://hub.docker.com/r/ysksn/dockerfile_fcgi/~/dockerfile/)).

Could I replace

> Installing the FCGI libraries:
> 
> ```
> curl -O http://www.fastcgi.com/dist/fcgi-2.4.0.tar.gz
> tar xzvf fcgi-2.4.0.tar.gz
> cd fcgi-2.4.0
> ./configure --prefix=/usr/local
> make
> sudo make install
> cd ..
> ```

with

Installing the FCGI libraries:

```
curl -O -k -L https://github.com/FastCGI-Archives/FastCGI.com/raw/master/original_snapshot/fcgi-2.4.1-SNAP-0910052249.tar.gz
tar xvfz fcgi-2.4.1-SNAP-0910052249.tar.gz
cd fcgi-2.4.1-SNAP-0910052249
./configure --prefix=/usr/local
mv libfcgi/fcgio.cpp /tmp/original
echo "#include <stdio.h>" > libfcgi/fcgio.cpp
cat /tmp/original >> libfcgi/fcgio.cpp
make
sudo make install
```

or just remove it?

What
1. `mv libfcgi/fcgio.cpp /tmp/original`
2. `echo "#include <stdio.h>" > libfcgi/fcgio.cpp`
3. `cat /tmp/original >> libfcgi/fcgio.cpp`

are doing is just inserting header file `#include <stdio.h>` top of of `fcgio.cpp` which is somehow missing. I know it's weird though.

**Comment by mcarbonneaux** [comment]
You can use also the git repo, https://github.com/FastCGI-Archives/fcgi2

**Comment by rafaelfranca** [comment]
Both alternative are good. Can you open a PR?

**Comment by mcarbonneaux** [comment]
Attention about the use of https://github.com/FastCGI-Archives/FastCGI.com/raw/master/original_snapshot/fcgi-2.4.1-SNAP-0910052249.tar.gz

This is the last snap from old fastcgi site. 

The github repository are more up to date :
https://github.com/FastCGI-Archives/fcgi2

This one while receve pr fix.
