### ISSUE TITLE
Documentation for 2.0 version?

### ISSUE THREAD

**Issue by georgeu2000** [rack/rack#1106]
Are there any breaking changes for v 2.0?

http://rack.github.io/ does not mention anything about 2.0. In fact, there has not been an update since February 7th, 2013.

https://github.com/rack/rack does not mention v 2.0 or any breaking changes.

**Comment by dubek** [comment]
Duplicate of #1097 ?

**Comment by NobodysNightmare** [comment]
@dubek It is... sad enough, that such an issue can have duplicates...

**Comment by mikegee** [comment]
This issue is definitely a duplicate. Let's close this one. The discussion around 2.0 documentation should stay in one place.
