### ISSUE TITLE
Reloader not works with Builder

### ISSUE THREAD

**Issue by coopermaa** [rack/rack#1109]
Hi,

I found a problem. Rack::Reloader seems not work correctly with Rack::Builder.
Given that:

```ruby
# lib/greeter.rb
class Greeter
  def call(env)
      [200, {"Content-Type" => "text/html"}, ["Hello World"]]
  end
end
```
```ruby
require "rack"
require "greeter"

app = Rack::Builder.new do
  use Rack::Reloader, 0    
  run Greeter.new
end

Rack::Server.start app: app, Port: 8080
```

And run as:

```
$ ruby -Ilib app.rb
$ curl localhost:9292
Hello World
```
This works correctly. If I make a change to lib/greeter.rb as follows:

```
$ sed -i 's/Hello World/Hello Rack/' lib/greeter.rb
$ curl localhost:9292
Hello World
```
It's expected that Rack::Reloader will pick up the changes, reload the lib/greeter.rb, and the result "Hello Rack" will be returned when requested, but it doesn't. Anyone have any ideas?

**Comment by akhramov** [comment]
Hi @coopermaa,

I'm not sure whether it's documented somewhere explicitly, but you should either use [Rack::Builder.app](https://github.com/rack/rack/blob/95172a60fe5c2a3850163fc75e0981fe440c064e/lib/rack/builder.rb#L58-L60):

```ruby
require "rack"
require "greeter"

app = Rack::Builder.app do
  use Rack::Reloader, 0    
  run Greeter.new
end

Rack::Server.start app: app, Port: 8080
```
or call [Rack::Builder#to_app](https://github.com/rack/rack/blob/95172a60fe5c2a3850163fc75e0981fe440c064e/lib/rack/builder.rb#L144-L150):

```ruby
app = Rack::Builder.new do
  use Rack::Reloader, 0    
  run Greeter.new
end

Rack::Server.start app: app.to_app, Port: 8080
```

Thanks

**Comment by coopermaa** [comment]
Thanks, @akhramov 

It works. 

Now I know why. The [Rack::Builder#to_app](https://github.com/rack/rack/blob/95172a60fe5c2a3850163fc75e0981fe440c064e/lib/rack/builder.rb#L144-L150) will create the middleware chain. If I pass app.to_app to the Rack server, it works correctly because the middleware chain is created only once. But if I pass an instance of the Rack::Builder to a Rack server directly, it will create a middleware chain every time when a request is received since [Rack::Builder#call](https://github.com/rack/rack/blob/95172a60fe5c2a3850163fc75e0981fe440c064e/lib/rack/builder.rb#L152-L154)  calls to_app. 

I was wondering if [Rack::Builder#to_app] (https://github.com/rack/rack/blob/95172a60fe5c2a3850163fc75e0981fe440c064e/lib/rack/builder.rb#L144-L150) could check the middleware chain is created or not, for example:

```ruby
 def to_app
  return @to_app if @to_app
  @to_app = @map ? generate_map(@run, @map) : @run
  fail "missing run or map statement" unless @to_app
  @to_app = @use.reverse.inject(@to_app) { |a,e| e[a] }
  @warmup.call(@to_app) if @warmup
  @to_app
end
```
