### ISSUE TITLE
global variable `$verbose' not initialized

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1116]
When running with `--warnings`, the following shows up in `lib/rack/request.rb`

```
^_^ > irb
2.3.0 :001 > $verbose
 => nil 
2.3.0 :002 > $VERBOSE
 => false 
2.3.0 :003 > defined? $verbose
 => nil 
2.3.0 :004 > defined? $VERBOSE
 => "global-variable" 
```

That's because it should probably be $VERBOSE, not $verbose.

**Comment by lsoarestd** [comment]
Hi. Any news on this? I'm also having this warning. Anything I can do to help moving this forward?

![image](https://cloud.githubusercontent.com/assets/20595884/23175141/6d20b922-f856-11e6-92e8-540b4abb654e.png)
