### ISSUE TITLE
Will TempfileReaper clean tmp file when request 500 error?

### ISSUE THREAD

**Issue by chaomao** [rack/rack#1118]
Hi, there
according to [TempfileReaper](https://github.com/rack/rack/blob/4b33af1c80c822cbcbb69113ff1e54f9454921c1/lib/rack/tempfile_reaper.rb), will tmp file remove when request throw 500 error?

**Comment by janko-m** [comment]
I think all web server Rack handlers are written to `#close` the response body in case of exceptions (and `#close` will delete the Tempfiles), for example [WEBRick handler does that](https://github.com/rack/rack/blob/55500f93e6da1860fd63267af1f226d05d9b0bdf/lib/rack/handler/webrick.rb#L114-L115).

**Comment by summera** [comment]
@janko I did a quick test with rails `5.2.3` and puma `4.3.1`  by raising an error in a controller action that receives a temp file (photo in this case) submitted through a form:

```ruby
def update
  puts request.env["rack.tempfiles"].map(&:path)
  raise "oops"
  if @record.update(record_params)
  ...
end
```

I checked to see if the temp file existed after the request was over and it does indeed. Any idea why this might be?

**Comment by ioquatix** [comment]
Can you test with falcon?
