### ISSUE TITLE
Mention setting up a Reverse Proxy in the docs

### ISSUE THREAD

**Issue by zdavatz** [rack/rack#1119]
Why is there no mentioning of setting up a Reverse Proxy to run Rack. That is the most simple solution for testing and development. Something like this:

https://www.playframework.com/documentation/2.5.x/HTTPServer#Set-up-with-Apache

At the moment a new developer gets the impression that the setup of Rack is more complicated then it actually is.

**Comment by tonytonyjan** [comment]
In my opinion, it's because rack is not HTTP server.

**Comment by zdavatz** [comment]
But it works perfectly.

**Comment by rafaelfranca** [comment]
What do you suggest?

**Comment by zdavatz** [comment]
As I mentioned above, same as it is mentioned with the Play-Framework: https://www.playframework.com/documentation/2.5.x/HTTPServer#Set-up-with-Apache

Rack uses the exact same settings.

**Comment by rafaelfranca** [comment]
I see. I don't think this documentation belongs to rack. This configuration works for any Web server and it is not specific to rack.

**Comment by zdavatz** [comment]
You should still mention Apache in the docs!
