### ISSUE TITLE
Why merging session_was?

### ISSUE THREAD

**Issue by coin8086** [rack/rack#1126]
https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb:

``` ruby
        def prepare_session(req)
          session_was               = req.get_header RACK_SESSION
          session                   = session_class.new(self, req)
          req.set_header RACK_SESSION, session
          req.set_header RACK_SESSION_OPTIONS, @default_options.dup
          session.merge! session_was if session_was
        end
```

Is it because you want to enable multi-tier session middlewares like:

``` ruby
use Rack::Session::Cookie
...
use Rack::Session::Memcache # or still use Rack::Session::Cookie
...
run app
```

But does it work by simply merging session_was? I see one session middleware may override another in `commit_session`, because they both may save the session data with the same default cookie.

If it's not for multi-tier session middlewares, then what's it for? I'm asking this because the piece of code gets my code wrong: I'm doing a little hack to it for my app's test purpose.

Thanks!

**Comment by tonytonyjan** [comment]
Are you looking for [this pull](https://github.com/rack/rack/pull/180/)?

**Comment by rafaelfranca** [comment]
I think the PR that @tonytonyjan linked answer your question. Let us know if you need more information. Thanks
