### ISSUE TITLE
LoadError: cannot load such file -- memcache

### ISSUE THREAD

**Issue by tonytonyjan** [rack/rack#1129]
```ruby
require 'rack'
Rack::Session::Memcache
```

```
LoadError: cannot load such file -- memcache
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/session/memcache.rb:4:in `<top (required)>'
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):2
        from /Users/tonytonyjan/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

I found [this commit](https://github.com/rack/rack/commit/648529a0a4388abc9955aeff7d936640d6364b2c) remove some dependencies from gemspec file.

To make `Rack::Session::Memcache` work again, we have to manually install `memcache-client`, and require it:

```ruby
require 'memcache-client'
require 'rack'
Rack::Session::Memcache
```

Is it by design?

We should either fix the dependency or improve the doc.

**Comment by rafaelfranca** [comment]
Yes, this is by design. This gem never were a dependency of rack.

Please send a PR improving the documentation.

**Comment by tonytonyjan** [comment]
Oops, I noticed it's been there already.

https://github.com/rack/rack/commit/e9f9f27ac772de7db0ba33e0421c7ffccbdbade1#diff-c47c7c7383225ab55ff591cb59c41e6bR160

Thanks for your kind reply.
