### ISSUE TITLE
Cookies escaping non consistent with JS decodeURIComponent

### ISSUE THREAD

**Issue by crazyshot** [rack/rack#1139]
Hi,

Is not that much a bug report, as lack of explanation, why `set_cookie_header!` uses `escape` method with encoding space to '+', which is inconsistent with respective methods on client-side encodeURIComponent and not parsable by decodeURIComponent.
I suggest fixing it by replacing `escape` call by `escape_path` call, which encodes space correctly.

**Comment by crazyshot** [comment]
After re-reading latest changes in lib/rack/utils.rb I think it shouldn't use escape_path as this will leave '+' unescape, which will break all decodings that parse it as space.
So new function, `escape_cookie` should be introduced, and implemented as:
`URI.encode_www_form_component(s).gsub('+', '%20')`

**Comment by jeremyevans** [comment]
RFC 6265 (https://www.ietf.org/rfc/rfc6265.txt) does not specify the encoding of cookies.  There is no requirement that any escaping is done, or a specific format if escaping is done, only that certain characters not appear (presumably such characters would be escaped).

For cookie names, only that control characters and separators are excluded, with separators defined as:

```
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

For cookie values, the values should be US-ASCII characters excluding control characters, whitespace, double quote, comma, semicolon, and backslash

So there isn't a bug here, as a cookie name or value is not a URI component and you should not expect to be able to parse it as such.  I think rack's current behavior makes sense and changing it would open up backwards compatibility issues.
