### ISSUE TITLE
"require 'rake'" inside config.ru fails

### ISSUE THREAD

**Issue by j4zzcat** [rack/rack#1145]
config.ru with `require 'rake'` fails with load error - `require': cannot load such file -- rake (LoadError).
The rake gem is installed, and the same line works in irb. Other "require" statements (i.e., require 'rubygems', require 'webrick' etc.) do work. 

Ruby version is ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
Rack version is 2.0.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. This may be a problem with your Rubygems environment or if you are using bundler with bundler, but it is not a problem with rake.
