### ISSUE TITLE
Empty request.params when EOFError is raised by rack.input stream

### ISSUE THREAD

**Issue by thesmart** [rack/rack#1147]
Hello,

We found an interesting bug today.  We're using Unicorn + Rack.  When sending a form multipart > 112KB, I noticed that Rack::Request#params was empty. In Rack, there's a catch for EOFError:
https://github.com/rack/rack/blob/cabaa58fe6ac355623746e287475af88c9395d66/lib/rack/request.rb#L357

When this occurs, it results in params being empty even though `rack.request.form_hash` is populated correctly.  Is this the desired behavior?  I believe some stream implementations may naturally raise EOFError when they reach the end.  Why discard the content in the POST body from params?

**Comment by jeremyevans** [comment]
Looking at the history on this rescue, it dates back to 2008 (67a7507fb07c9d49bf4be4fc6c4fc4578f1673ac).  There is no explanation why it was added, though.  It seems reasonable that EOFError would only be raised after parsing the request body is finished.

Reading the `POST` method, it seems the `parse_multipart` call would be the only way to generate EOFError.  The most probable way to trigger this behavior you described (where `rack.request.form_hash` is correctly populated) would be to change `rack.input` after an earlier call to `POST`.  However, that would no longer effect `params`, as `params` calls are now cached.

If you think this is still a problem in current rack, please submit a failing test or a minimal self-contained example showing the problem.
