### ISSUE TITLE
Allow starting the server when pid is the same as current process

### ISSUE THREAD

**Issue by grosser** [rack/rack#1159]
Puma restarts by replacing itself via `exec`, so they new process has the same pid as the old process, that trips up https://github.com/rack/rack/blob/master/lib/rack/server.rb#L379-L393 which then decides that the server must still be running since the pid is healthy and refuses to boot.

Would you accept a PR that adds a `:dead if old_pid == Process.pid` check ?

see https://github.com/puma/puma/issues/1060

**Comment by tenderlove** [comment]
@grosser yep, I'm good with that.  Send a PR and it will be merged.  😊

**Comment by jeremyevans** [comment]
This looks fixed in Puma.  If you would still like this feature added to Rack, please submit a pull request.  I don't consider this a bug in Rack, so I'm going to close this now.
