### ISSUE TITLE
Release rack 2.0.2?

### ISSUE THREAD

**Issue by ivoanjo** [rack/rack#1164]
Hello there!

There has been a lot of awesome work and small fixes (such as #1117) on rack since the latest 2.0.1 release.

I would like to ask the rack team to consider releasing a 2.0.2 with those fixes/additions.

Thanks in advance!

**Comment by matthewd** [comment]
620766d061975a67f80fa5dc3887563c1563a64d ✅

**Comment by ivoanjo** [comment]
Awesome, thanks!
