### ISSUE TITLE
Webrick handler fails on integer response header

### ISSUE THREAD

**Issue by yoelblum** [rack/rack#1167]
I'm not sure if this is by design or not:
My API uses the http response headers to tell the client how many items it returns, e.g:

       response.headers['x-total-count'] = 16

This causes an exception on webrick but works fine on puma (I couldn't find anything about integer 
The exact line throwing the exception is:
https://github.com/rack/rack/blob/master/lib/rack/handler/webrick.rb#L98
and the exception is trying to call split on integer:

     undefined method `split' for 16:Integer

I'd be happy to submit a patch if you think this is worthy of a fix (it's actually the reason I'm switching to puma on development)

**Comment by tenderlove** [comment]
Sorry, this isn't a bug in the webrick handler.  According to the [`SPEC`](https://github.com/rack/rack/blob/e37c6ae42da4b561321d9d30b91ffac02c214717/SPEC#L230):

> The values of the header must be Strings,

So if you're setting a header value, it's expected that the value will be a string (I guess Puma is less strict about following the spec in this regard).

**Comment by yoelblum** [comment]
@tenderlove  Thanks for the swift response! Just out of curiousity - any idea why this restriction ?  I mean http headers can be integers right?
