### ISSUE TITLE
Remove zero CONTENT_LENGTH in sendfile

### ISSUE THREAD

**Issue by jcm** [rack/rack#1174]
For a Ruby on Rails 4.2 call to send_file when hosted by Apache + uWSGI
I get ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH error with two headers for Content-Length, the first one being zero and set here:
https://github.com/rack/rack/blob/master/lib/rack/sendfile.rb#L128
IMHO it should be simply removed here.

**Comment by jeremyevans** [comment]
This doesn't appear to apply to current mod_xsendfile: https://github.com/nmaier/mod_xsendfile/blob/master/mod_xsendfile.c#L396-L397

Maybe it applied to an earlier version?  In any case, if a later server is taking the response returned by rack and setting a separate Content-Length header without removing the existing one, I think it is a bug in that server, and should be reported to that server's maintainers.
