### ISSUE TITLE
Skip Rack::MethodOverride in certain scenarios?

### ISSUE THREAD

**Issue by jhubert** [rack/rack#1176]
I have a controller in my Rails app that receives a large post body and the rack.request is performing rather slowly. When I tracked it through the middleware stack Rack::MethodOverride was reporting the following timings:

<img width="999" alt="pasted_image_6_5_17__10_10_pm" src="https://cloud.githubusercontent.com/assets/3384/26814624/d3a6a814-4a3b-11e7-95dd-9db5d47dd0de.png">

Seems like a lot of time for something to check if there is a `_method` param.

Turns out it's parsing the post content to search for the `_method` param, which is taking all that time.

Is there a way to selectively disable it for certain routes when I know there will be no need to accept overridden methods, or should I monkeypatch around it?

**Comment by jhubert** [comment]
I've written a little patch using `prepend` to adjust the behavior based on the PATH_INFO in the env. The code loaded from an initializer. Here it is:

```ruby
# Allow us to skip Rack::MethodOverride in certain cases
module RackMethodOverrideSkipper
  # Skip the method override check if we're loading an SSO endpoint
  # so that the large POST body doesn't cause the request to slow down
  def call(env)
    if sso_endpoint?(env)
      @app.call(env)
    else
      super
    end
  end

  private

  # :reek:UtilityFunction
  def sso_endpoint?(env)
    env.fetch('PATH_INFO', '')[0..3] == '/sso'
  end
end

Rack::MethodOverride.prepend RackMethodOverrideSkipper
```

Is there a better way to implement this? Should I be instead swapping in my own middleware?

**Comment by rafaelfranca** [comment]
In Rails each controller has its own middleware stack, so you can remove `MethodOverride` from the application stack and only add in the controllers you want to.

I'm closing since this is not an issue.
