### ISSUE TITLE
warning: regexp match /.../n against to UTF-8 string

### ISSUE THREAD

**Issue by rocLv** [rack/rack#1183]
When I upgrade my ruby version from 2.4.0 to 2.4.1, and rails version from 5.0.2 to 5.1.1, I got this warning during I ran my integration tests.
`.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/query_parser.rb:64: warning: regexp match /.../n against to UTF-8 string
`

It seems the same with **[this](https://github.com/rails/rails/issues/3927)**

**Comment by viraptor** [comment]
Confirming the same issue in tests with:

```
ruby 2.3.3
rack 2.0.5
rails 5.0
```

**Comment by shved** [comment]
same issue
```
ruby 2.5.3
rack 2.0.6
rails 5.1.6
```

**Comment by fractaledmind** [comment]
Same issue here

```
ruby 2.4.5
rack 1.6.11
rails 4.2.10
```

**Comment by fagiani** [comment]
same issue

    ruby 1.9.3
    rack 1.2.5
    rails 3.0.4

Any luck?

**Comment by arloan** [comment]
same issue

jruby 9.1.7
rack 2.0.5
cuba 3.9.2

**Comment by jeremyevans** [comment]
I believe rack should require that the query parameter string be binary (at least if it contains non-ASCII characters).  This is explicitly specified for request bodies in SPEC, and should probably be stated for `QUERY_STRING` as well (I'll submit a PR for that).  Query parameter strings should have all non-ASCII (and some ASCII) characters be URL encoded, so if your tests are including non-ASCII characters in query parameter strings, you should fix your tests to correctly encode the query strings.

This has apparently affected a number of people, so I'm going to allow some time for feedback before closing this.  But I don't think it is a bug in rack.  Has anyone experienced this issue in a production environment?  Can anyone submit a self-contained reproducible example showing the problem?
