### ISSUE TITLE
Memory use balloons on large file uploads

### ISSUE THREAD

**Issue by motevets** [rack/rack#1195]
### Description
We have an app that deals with very large file uploads (~8G).

When we upgraded rack 2.0.3 (as part of a Rails upgrade,) the upload hung seemingly forever, as described in #1075.

When using the most up-to-date master (SHA 877d334a), memory usage went up ~10x from previous version of rack (1.6), and the request failed if the server did not have enough memory.

### Steps to reproduce
1. create a new Rails app
1. add `gem 'rack', git: 'https://github.com/rack/rack.git', ref: '877d334a4878c4f38d0a8fcec575c73cc5a16978'` to Gemfile
1. create a simple controller that allows file upload
     *(note: see [motevets/rack-large-upload-example-rails-app] for a completed example)*
1. upload a 7.78G file
1. run `watch free` on the server while the request is processing
1. wait for browser to show that the upload is at 100% and waiting for the server to respond

#### Result
The peak memory usage during the request was 24G:
```
             total       used       free     shared    buffers     cached
Mem:           51G        50G       311M        17M        35M        26G
-/+ buffers/cache:        24G        26G
Swap:           0B         0B         0B
```
#### Expected result
(On rack 1.6) the peak memory usage during the request was 2.4G.:
```
             total       used       free     shared    buffers     cached
Mem:           51G        31G        19G        17M        50M        29G
-/+ buffers/cache:       2.4G        48G
Swap:           0B         0B         0B
```

cc: @michelleheh

[motevets/rack-large-upload-example-rails-app]: https://github.com/motevets/rack-large-upload-example-rails-app

**Comment by rafaelfranca** [comment]
@motevets can you check the master branch? I just merged https://github.com/rack/rack/pull/1193

**Comment by motevets** [comment]
Thank you for responding so quickly! I'll test it first thing when I get in to work tomorrow (PST.)

**Comment by jkowens** [comment]
@motevets did that update do the trick?

**Comment by motevets** [comment]
Yes 😄 

The peak memory usage was 1.5G.  Which is *less* than it used in 1.6!

```
             total       used       free     shared    buffers     cached
Mem:          7.8G       7.7G       123M        18M        37M       6.2G
-/+ buffers/cache:       1.5G       6.3G
Swap:           0B         0B         0B
```

**Comment by jkowens** [comment]
Wow, nice work @tompng! 🎆

**Comment by nik-kg** [comment]
I'm sorry, but when i uploading 3,5 GB file in my app response stuck on 100% and after ~7 mins i got out of memory (my ram - 1gb). 
Before fix of course it was worse, anyway thank you for fix @tompng.
But i think it's still not ok.

**Comment by jkowens** [comment]
@nik-kg are you pulling the code for rack from the`master` branch?

**Comment by nik-kg** [comment]
@jkowens yes, i set in gemfile `gem 'rack', git: 'https://github.com/rack/rack.git'`

**Comment by jkowens** [comment]
@nik-kg and just to confirm, this works fine for you with rack 1.6?

**Comment by nik-kg** [comment]
@jkowens I didn't check it on 1.6, but i will try.

**Comment by nik-kg** [comment]
@jkowens on rack 1.6 when uploading 1.9GB file with simply rails app based on [example](https://github.com/motevets/rack-large-upload-example-rails-app) by **motevets** i got :
`ERROR NoMemoryError: failed to allocate memory`

before upload i checked free memory:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:        3,0G        1,1G        1,5G         59M        336M        1,5G
```

**Comment by jkowens** [comment]
@nik-kg sorry I went silent there. This is strange, others were reporting that large file uploads worked fine in rack 1.6, so this makes me wonder if there is something else going on in your setup/environment that is creating this issue.

**Comment by nik-kg** [comment]
@jkowens Thank you for answering.
 I try [benchmark](https://gist.github.com/tompng/54eb216d81c600a46fef28ddab68b356) by @tompng 
i changed only in Gemfile
`gem 'rack', git: 'https://github.com/rack/rack'`
and file size:
`[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048].each do |mb|`

Before benchmark i check free memory:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:        3,0G        1,2G        1,4G         50M        308M        1,4G
```

```
$ bundle exec ruby benchmark.rb
{"file_size"=>1000000, "run_parser_called"=>1, "memory"=>"7MB"}: 0.074312308sec
{"file_size"=>2000000, "run_parser_called"=>2, "memory"=>"8MB"}: 0.132896251sec
{"file_size"=>4000000, "run_parser_called"=>4, "memory"=>"10MB"}: 0.12140432sec
{"file_size"=>8000000, "run_parser_called"=>8, "memory"=>"9MB"}: 0.139951907sec
{"file_size"=>16000000, "run_parser_called"=>16, "memory"=>"11MB"}: 0.248028817sec
{"file_size"=>32000000, "run_parser_called"=>31, "memory"=>"11MB"}: 1.441663251sec
{"file_size"=>64000000, "run_parser_called"=>62, "memory"=>"11MB"}: 2.684409082sec
{"file_size"=>128000000, "run_parser_called"=>123, "memory"=>"8MB"}: 5.823216262sec
{"file_size"=>256000000, "run_parser_called"=>245, "memory"=>"8MB"}: 10.747686658sec
{"file_size"=>512000000, "run_parser_called"=>489, "memory"=>"8MB"}: 32.973830242sec
{"file_size"=>1024000000, "run_parser_called"=>977, "memory"=>"8MB"}: 110.520976435sec
"POST /upload HTTP/1.1" 200 63 0.1136
benchmark.rb:5:in `*': failed to allocate memory (NoMemoryError)
	from benchmark.rb:5:in `test'
	from benchmark.rb:14:in `block in <main>'
	from benchmark.rb:13:in `each'
	from benchmark.rb:13:in `<main>'
```
By the way `"memory"=>"8MB"` - it's not true. In process list sometimes i saw ruby using 1 GB memory during benchmark.

**Comment by jkowens** [comment]
@nik-kg if you are using that benchmark script you should see 2 ruby processes. The one that we are concerned with is the `server.rb` script. There of course is going to be some overhead, but it should only use a small amount of memory (less than 100MB).

The second ruby process is the `benchmark.rb` script which is the http client that posts to the server. It will likely consume at least as much memory as the file size you are sending to the server and I see you probably have modified the benchmark script to send a file larger than 1 GB.

**Comment by nik-kg** [comment]
@jkowens Yes, i have 2 ruby processes. I modified benchmark to check file uploading with size more than 512 mb. 

So, for upload large files i need memory as much as file size? And it's ok?

**Comment by jkowens** [comment]
@nik-kg  The server script is where rack is running and it uses very little memory, as the test proved.

Here is how you can update the `benchmark.rb` script to use less memory:

```
require 'json'
require 'httpclient'

# create a 1MB filler
BUFFER  = 'a' * 1_000_000

def test size
  file = Tempfile.new
  size.times { file.write BUFFER }
  file.rewind
  option = { 'content-type' => "multipart/form-data, boundary=#{rand}" }
  t = Time.now
  res = JSON.parse HTTPClient.post('http://localhost:4567/upload', { file: file }, option).body
  raise "Inconsistent file sizes" if res['file_size'] != file.size
  [Time.now - t, res]
end

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512].each do |mb|
  time, res = test mb
  puts "#{res}: #{time}sec" # including GC and profiling time
end
```
