### ISSUE TITLE
I can upload only up to 127 although limit is 128

### ISSUE THREAD

**Issue by akicho8** [rack/rack#1207]
https://github.com/rack/rack/blob/6b942ff543416e0c82196f0790d4915c7eead4cb/lib/rack/multipart/parser.rb#L157

If limit was 128, I thought that it would be natural to think that I could upload up to 128

**Comment by mig-hub** [comment]
Don't take my word on it, but looking at the code it seems the limit is for the number of parts, not the number of open files. There seems to be one more part for the form fields. So the parts are the number of open files + 1.

**Comment by akicho8** [comment]
I see. It was not the number of files, but the number of parts.

**Comment by mig-hub** [comment]
I think so. If you look at this [search for multipart](https://github.com/rack/rack/search?p=2&q=multipart&type=&utf8=%E2%9C%93) you can see in history that the name was changed at some point from "multipart_limit" to "multipart_part_limit". It may be to make this clearer.

Also the description on line 155 of history says max number of parts.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
