### ISSUE TITLE
When can we cut a new version to include bugfixes?

### ISSUE THREAD

**Issue by lostapathy** [rack/rack#1216]
Any idea when we will see a new version of rack cut, or what issues need resolved so we can?

It seems like a fair amount of people are having to monkeypatch around the issue raised in #1175 and fixed on #1179 and it'd be nice to ship an updated version with that included.

If we aren't ready for another release yet, where should efforts be directed so we can get there?

thanks!
 
edit: also requested on #1219

**Comment by jeremy** [comment]
Coming soon.™ 😍

(Rails 5.2 release will depend on it.)

/cc @tenderlove

**Comment by lostapathy** [comment]
Soon indeed, 2.0.4 is out now.

Thanks guys!
