### ISSUE TITLE
new release date?

### ISSUE THREAD

**Issue by jacek213** [rack/rack#1219]
I'm not sure if everyone's aware, but this bug: https://github.com/rack/rack/pull/1179 breaks upload for all newly created RoR apps. As it's already fixed, maybe it's time for a new release? Latest patches date back to May.

**Comment by aiomaster** [comment]
We updated a rails app where we allow large file uploads. Sadly we tested only with small files and everything seemed to work. In production we were hit by the bug which https://github.com/rack/rack/pull/1179 fixes and I can't believe that this fix is not included in a stable release, yet!
This is definitly critical!
Can someone who is able to make a new release please make it clear what is missing and where help is needed to release a new version? (@rafaelfranca, @matthewd, @tenderlove, ... ?)

**Comment by jeremy** [comment]
We hit this also and pinned to Rack master as a workaround. Closing this issue since #1216 asks the same thing and came first.
