### ISSUE TITLE
Headers specs are not clear enough

### ISSUE THREAD

**Issue by rosenfeld** [rack/rack#1222]
Most Rack middlewares expect the returned headers to act like a Hash but this is not stated in the specs:

https://github.com/rack/rack/blob/master/SPEC#L226

```
=== The Headers
The header must respond to +each+, and yield values of key and value.
Special headers starting "rack." are for communicating with the
server, and must not be sent back to the client.
The header keys must be Strings.
The header must not contain a +Status+ key.
The header must conform to RFC7230 token specification, i.e. cannot
contain non-printable ASCII, DQUOTE or "(),/:;<=>?@[\]{}".
The values of the header must be Strings,
consisting of lines (for multiple header values, e.g. multiple
<tt>Set-Cookie</tt> values) separated by "\\n".
The lines must not contain characters below 037.
```

While reading this specs, I get the impression that something like this would meet the requirements:

```ruby
headers = [
  [ 'Server-Timing', 'app;dur=100' ],
  [ 'Server-Timing', 'db;dur=60' ],
]
```

It responds to `each` and yields values of key and value, right?

However, if we take a look at the Runtime middleware we can see it would not work with such a header:

https://github.com/rack/rack/blob/master/lib/rack/runtime.rb#L25

``` ruby
unless headers.has_key?(@header_name)
```

An array doesn't respond to `has_key?`. By the way, Matz prefers `key?` to be used over `has_key?`.

Shouldn't the specs be clear about headers having to act as hashes, or at least list which methods it should respond to?

**Comment by chneukirchen** [comment]
`headers.has_key?` is not part of the spec, so this is a fault in this middleware.
Did you find other things that break?

(The thing you are probably trying to do can be achieved with `{'Server-Timing' => "app;dur=100\ndb;dur=60"}` however.)

**Comment by chneukirchen** [comment]
That said, lots of code assumes it can use `[]` at least...

**Comment by rosenfeld** [comment]
Yes I figured that out, and it's stated in the specs I pasted above, but I was particularly interested about the Rack specs. I do have myself tons of custom middlewares that expect a hash and was just surprised to see that it's not defined in the specs.

**Comment by chneukirchen** [comment]
The wording `The header keys must be Strings.` kinda implies a Hash, but this should be made explicit indeed. That will probably require a bump of the revision however.

**Comment by rosenfeld** [comment]
Rack::ETag is another example of middleware bundled with Rack that expects the headers to be a hash.

**Comment by rosenfeld** [comment]
Other examples include: Rack::File, Rack::Sendfile and Rack::Static.

**Comment by jeremyevans** [comment]
For more context from the SPEC:

```
The header must respond to +each+, and yield values of key and value.
The header keys must be Strings.
```

This indicates to me that currently SPEC explicitly does not require the response headers be a hash.  However, I would guess that almost all middleware that accesses the response headers would break if the headers were not a hash, so SPEC should be changed, and Lint updated to check for it.  I'll submit a pull request for that.

While hash-like responses headers would also work, since SPEC requires the request environment be a hash, I think requiring the response headers be a hash is best.

**Comment by ioquatix** [comment]
The SPEC is very clear on the interface requirements for response headers.

There is a separate issue of whether we should change the spec to require headers be a Hash, or something which looks like a hash. That's a separate issue and will be discussed and implemented in  https://github.com/rack/rack/pull/1485

**Comment by ioquatix** [comment]
As a side note, the `Rack::Runtime` middleware was broken. So, I've fixed it.
