### ISSUE TITLE
Update or remove 'News' from homepage

### ISSUE THREAD

**Issue by Nudin** [rack/rack#1225]
The section 'News' from https://rack.github.io/ lists 1.5.2 as newes version. Update the site or remove the version-info.

**Comment by DannyBen** [comment]
I agree, the site needs to either be removed or completely updated, with the bare minimum of the news section.

There is news from 2013 with the bold sentence **Today's releases are important. All users should upgrade ASAP!**

This does not show `rack` in a positive light, and hints that it is unmaintained for the past 6 years...

**Comment by jeremyevans** [comment]
The NEWS.md file was removed at 68cc4e9f800e114689026fead4c4a3de371c03ba.
