### ISSUE TITLE
X-forwarded-for with ports information in Azure

### ISSUE THREAD

**Issue by wuhanyumsft** [rack/rack#1227]
Hi,

See [Frequently asked questions for Azure Application Gateway | Microsoft Docs](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq)

> Q. Does Application Gateway support x-forwarded-for headers?
> 
> Yes, Application Gateway inserts x-forwarded-for, x-forwarded-proto, and x-forwarded-port headers into the request forwarded to the backend. **The format for x-forwarded-for header is a comma-separated list of IP:Port**. The valid values for x-forwarded-proto are http or https. X-forwarded-port specifies the port at which the request reached at the Application Gateway.

Can we extend https://github.com/rack/rack/blob/2e92a25342b5d51f4094366c3b8dd797cbd208a4/lib/rack/request.rb#L475-L477 to support that? or it will pass invalid ip address (with ports) to the following procedure.

**Comment by tenderlove** [comment]
@wuhanyumsft ya, I think that makes sense.  Please send a PR!

**Comment by wuhanyumsft** [comment]
Thanks. @tenderlove  can you help with the PR https://github.com/rack/rack/pull/1229.

**Comment by thakurinbox** [comment]
Please help me to understand. why its comma-separated list of IP:Port. Is there any case where we can have multiple client IP's for one request. and what it this PORT along with IP. where is this PORT comping from?
