### ISSUE TITLE
Multipart parser behavior with multipart/related

### ISSUE THREAD

**Issue by baarde** [rack/rack#1230]
Hello,

I've noticed that, while the behavior of `Rack::Multipart::Parser` is great for `multipart/form-data`, it has a catch when dealing with `multipart/related`.

## Issue

[`multipart/related`](https://tools.ietf.org/html/rfc2387) allows a multipart body to combines several related body part. It is useful when one wants to send contents of different types in the same request, such as a file to upload plus JSON metadata. For example, Google Cloud Platform provides a [multipart upload API](https://cloud.google.com/storage/docs/json_api/v1/how-tos/multipart-upload#example_sending_a_multipart_upload_request). 

When parsing a multipart body, Rack extracts parts:
- as a "file" (a hash that contains a `Tempfile`, a file name, a type and the part's headers), when `Content-Disposition` contains the `filename` parameter, or
- as a string otherwise.

The `Content-Disposition` header is not necessary for `multipart/related` and may be omitted by the client. For instance, the example from Google Cloud Platform's documentation does not uses it.

However, when this header is omitted, **the part is extracted as a string instead of a file**, which means:
- it is stored in memory, and
- the part's headers are not extracted, and
- the developer will have a harder time handling the request correctly.

For a `multipart/related` (or `multipart/mixed`) request, I don't think there is a situation where it makes much sense to extracts a part as a string instead of a file.

I'd be glad to work on a fix for this issue. However, **I'd like to have other people's opinions** on the matter before submitting a merge request.

## Proposed solution

The parser should decide whether the part is a file or a string like this:
- if the request's `Content-Type` is `multipart/form-data` and the part's `Content-Disposition` does **not** include the `filename` parameter, then the part is a **string**.
- otherwise, the part is a **file**.

## Impact on existing applications

This proposal **would not affect** existing applications that do not expect to receive a `multipart/mixed` or `multipart/related` request.

**However**

This proposal **would affect** existing applications that expect one or more parts of a `multipart/mixed` or `multipart/related` request to never have a `filename` parameter.

This proposal **would affect** existing applications that rely on file params from a `multipart/mixed` or `multipart/related` request always having a filename.

**Comment by jeremyevans** [comment]
From my reading of RFC 2387, absent backwards compatibility issues, it probably does make more sense to treat `multipart/related` parts as files and not strings.  However, I'm not sure how many people are currently using `multipart/related`, and I don't think we would want to break their code.

If there is a way to make this backwards compatible and support the behavior you want as an option, I think we would consider it.  Please submit a pull request in that case.

As this was submitted almost two years ago and nobody has commented on it yet, it doesn't seem like enough of a problem for most people that we would want to break backwards compatibility to fix it.  

You can fix this in your application in Rack 2+ by overriding  `Rack::Request#query_parser` to use a custom query parser with the behavior you want.

As this isn't a bug in Rack, I'm going to close this now.
