### ISSUE TITLE
Rack::Lint is too permissive with responses

### ISSUE THREAD

**Issue by wagenet** [rack/rack#1239]
From the Rack [SPEC](http://www.rubydoc.info/github/rack/rack/file/SPEC):

> A Rack application is a Ruby object (not a class) that responds to call. It takes exactly one argument, the environment and returns an Array of exactly three values: The status, the headers, and the body.

However, in `Rack::Lint` as long as the object responds to `to_ary` it will pass. `Rack::Lint` should validate that the object actually is an array.

https://github.com/rack/rack/blob/master/lib/rack/lint.rb#L49

**Comment by rafaelfranca** [comment]
I believe we don't need to check the type since most of the times `status, headers, body = @app.call(env)` is what people does. So why the type matters here?

**Comment by wagenet** [comment]
@rafaelfranca in Skylight, we had some code that was modifying the response array directly. We've just changed it to create a new array, but in the event that the response wasn't actually an array, this wouldn't work. The SPEC seems to be saying that the response should be an Array, not merely something that has an implicit conversion to an Array. I can live with either one, but IMO, there's a disconnect between the SPEC and Rack::Lint.

**Comment by rafaelfranca** [comment]
I see, yeah, I agree with you. I hate those written specs because they are always subjective to interpretation.

Since it is Array, not `Array` it could mean something that looks like an Array.

@matthewd thoughts?

**Comment by matthewd** [comment]
> we had some code that was modifying the response array directly

The spec also doesn't say you can do that :wink: -- e.g. it might be a reused value; it might be frozen.

I think this is relevant precedent: https://github.com/rack/rack/blob/50db1ffdf8b98503fb7c6e6648622b5d7d78d58e/lib/rack/lint.rb#L66-L71

i.e. yes it should check the class, but it should allow subclasses.

**Comment by wagenet** [comment]
@matthewd yes, I agree that modifying the array isn't great. We actually ended up changing our approach because in one situation the response was frozen. I was just more concerned about the intended behavior in the spec. With Skylight we have to carefully interact with the responses from a variety of Middleware so I'm interesting in understanding how things are supposed to work. In this case, the main question is whether I should expect to have to destructure the response or if I can just access individual elements.

**Comment by ioquatix** [comment]
I think in some of my code, I return an object that implements `to_ary` as expected, but is not a sub-class of Array. It's also the case that sometimes it's frozen. I think we could clarify that `to_ary` returns the 3 elements as required is good enough.

**Comment by mikegee** [comment]
@ioquatix makes a legitimate recommendation, but it is in conflict with @matthewd's suggestion. I think we could put up a PR to clarify the situation if we had a final decision.

**Comment by ioquatix** [comment]
The only thing I can really add is that while the SPEC should aim to be as straight forward as possible, because of the ambiguity it might be impossible in this case to nail it down. Because too much code took the liberty to use `to_ary` or something else. That being said, maybe for the next major version of the SPEC we can make that change, but it wouldn't be backwards compatible. I'd be okay with that, generally. I'd need to check why in specific situations I didn't use an `Array` to present arguments for/against the proposed SPEC change.

**Comment by wagenet** [comment]
It looks like Rack::Response no longer has `to_ary` so we can't rely on implicit destructuring.
https://github.com/rack/rack/commit/72959ebc2f300f3b2ccb7ae2aae9f199e611dfb6#diff-10b933d2c1fdc82ceecade456c64e1c2

**Comment by wagenet** [comment]
@tenderlove I'd appreciate your input here.

**Comment by jeremyevans** [comment]
My reading of SPEC is that the response should be an instance of Array or instance of subclass of Array.  In cases in SPEC where any object that responds to a given method will work, the method is listed explicitly.  Examples:

```
+puts+ must be called with a single argument that responds to +to_s+.

This is an HTTP status. When parsed as integer (+to_i+)

If the Body responds to +to_path+
```

I think either SPEC should be changed or Rack::Lint should be more strict.  My preference is the latter.  I'll submit a pull request to update Rack::Lint, and merge it in a few days if there are no objections.

**Comment by tenderlove** [comment]
@jeremyevans I agree with your assessment. I will merge the Lint changes.

**Comment by ziggythehamster** [comment]
Including the `ary.inspect` in the assertion causes Ruby to build a string potentially containing the entire contents of the body, for every middleware.

I've opened an issue with more detail: https://github.com/rack/rack/issues/1625
