### ISSUE TITLE
CircleCI Checkout Key

### ISSUE THREAD

**Issue by zzak** [rack/rack#1242]
It looks like the build is failing because we aren't able to get a good checkout key:
https://circleci.com/gh/rack/rack/171#config/containers/0

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

This is probably because the repo was added long ago and hasn't been updated.

Here's a build from [a month ago](https://circleci.com/gh/rack/rack/158) with the same error,
and this one from [then months ago](https://circleci.com/gh/rack/rack/123).

This [discuss post](https://discuss.circleci.com/t/solved-permission-denied-publickey/19562/) also outlines the problem, but since I'm not a `rack` org admin I can't fix the key.

Someone, either @jeremy or @rafaelfranca, will need to go fix the checkout key:
https://circleci.com/gh/rack/rack/edit#checkout

If that doesn't work, we can try re-adding the project manually.

Sorry for the trouble. :bow:

**Comment by jeremy** [comment]
Fixed 👍

**Comment by zzak** [comment]
:tada: Thanks Jeremy!
