### ISSUE TITLE
Frozen String LIteral changes

### ISSUE THREAD

**Issue by oniofchaos** [rack/rack#1243]
Looks like there have been multiple PRs opened relating to migrating the codebase to using `#frozen_string_literal: true` in order to prevent unnecessary string allocations. Unfortunately, only 1 that I saw has been merged and it only updated 1 file. Can any of the maintainers speak to why the others haven't gotten merged? I'm willing to help out with any extra changes desired to make this happen.

https://github.com/rack/rack/pull/1182
https://github.com/rack/rack/pull/1023

cc: @pat @twalpole (thanks for your PRs!)

**Comment by oniofchaos** [comment]
I see https://github.com/rack/rack/pull/1203 got merged but it doesn't look like it's in any of the tagged versions?

**Comment by twalpole** [comment]
@oniofchaos Maintainers just didn't seem interested

**Comment by oniofchaos** [comment]
@tenderlove thanks for merging #1182, would there be interest in a PR that adds the pragma to more files? If so I am happy to submit.

**Comment by tenderlove** [comment]
@oniofchaos yes, I'm interested in adding the pragma directive to all of Rack.

**Comment by tenderlove** [comment]
I think everything has the frozen string directive.  Can this be closed?
