### ISSUE TITLE
Document maintainership

### ISSUE THREAD

**Issue by leahneukirchen** [rack/rack#1245]
I just update README.rdoc and I think the contents are quite outdated.

The Core Team should list the actual current committers, resp. people on rack-core;
also we should extend the Gem metadata to a relevant set of authors.

**Comment by fxn** [comment]
Don't know off the top of my head... maybe ask in the Contributors room?

**Comment by rafaelfranca** [comment]
@yhirano55 is doing some good work related to documentation on Rails, so maybe he may want to help us here?

**Comment by yhirano55** [comment]
It's my pleasure. I do my best.

**Comment by Drenmi** [comment]
> I'll make a pass through it, but it would be nice if we had more documentation focused folks on the team.

@tenderlove: I've been keen to help since your Request & Response talk at RDRC, but haven't had the time. Work arrangements have changed though, and I'd be happy to help out in any capacity.

**Comment by tenderlove** [comment]
@Drenmi yes please!  TBH, I would like to eliminate `HISTORY` in favor of using commit history.  The thing I think would be most useful for end users is a `NEWS` file that contains more high level information.  I don't think we need to tell everyone about every single commit, but we definitely need to communicate new features / bug fixes / security fixes.

We could definitely use help digesting the commits in to something easily consumable by people using the library.  What do you think?

**Comment by Drenmi** [comment]
@tenderlove I was thinking the same thing. I’m flying back from Ruby Conference Taiwan today. Was hoping to see you here, but I’ll drop you an e-mail or a ping when I’m home and have looked into it.

**Comment by jeremyevans** [comment]
I updated the README to add Samuel and me to the core team.  I'm not sure whether all other people listed as core team members are still active.  If not, they should be moved to the Alumni section.  Looking at the commit log, it seems like the following people may no longer be active, using month of last commit:

* James Tucker (March 2016)
* Josh Peek (June 2011)
* Jose Valim (March 2012)
* Michael Fellinger (May 2016)
* Konstantin Haase (February 2015)

Is it OK if I move these people to the Alumni section?

Regarding the gem metadata, do we want to list all current core team members under authors?  If so, I can update the gem metadata authors after fixing the README.

**Comment by jeremyevans** [comment]
@rafaelfranca fixed the README in 256ea3e20993076f9749fd17f6fd91f0ded0e1e7.  The gemspec has not been updated, though.  Do we want to update the gemspec to reflect the core team in the README?

**Comment by jeremyevans** [comment]
The gemspec hasn't been updated, and since nobody responded positively about updating it. I'm going to leave the gemspec alone and close this now.

**Comment by rafaelfranca** [comment]
It is a good question about the gemspec. In the past we only appended to the list of authors but that list would be huge. I'm not against matching the core team in the gemspec. @tenderlove @matthewd what do you think?

**Comment by tenderlove** [comment]
My only concern is that I don't want to create a situation in which the original author of Rack is removed from the gemspec.  If Leah ever decides to leave the core team, I'd rather not remove her from the gemspec (unless that's what she wants).  So making "gemspec" == "core team" makes me slightly uncomfortable.

**Comment by jeremyevans** [comment]
According to the README, Leah already left the core team.  But I agree with you that she should be kept as a gem author unless she would prefer otherwise.

**Comment by tenderlove** [comment]
In that case I'm fine with changing the gemspec (I don't particularly care other than my comment above)
