### ISSUE TITLE
Retire rack.github.io site

### ISSUE THREAD

**Issue by antonpaisov** [rack/rack#1263]
When a person visits https://github.com/rack/rack, the description says "a modular Ruby webserver interface http://rack.github.io/".
However, the rack.github.io site is seriously out of date with the latest post in news dating "February 7th, 2013" and the latest release marked as 1.4.1.
This is very confusing.
Given that https://github.com/rack/rack.github.com is basically a static HTML page with hardcoded content (meaning that neither releases nor other content fetched from outside) and it seems that no one is interested in updating and maintaining it, I suggest it's better to remove the repo and the site altogether and keep all the related info in the main repo/documentation.

If, however, someone would be willing to update/maintain rack.github.io, that person would need to make a new site anyways.

Opinions?

**Comment by yhirano55** [comment]
I'm going to update rack.github.com in the near future. I feel it's not good to maintain with hardcoding, so I'm going to propose that we adopt static generator like Jekyll (like https://github.com/rails/homepage)

**Comment by antonpaisov** [comment]
@yhirano55 cool! When I saw the site I also thought about making a completely new version with something like Jekyll :)
One of my concerns is that there's no CHANGELOG (or I haven't found one) at the repo. This fact made me also think that if the basic info is not supported in the repo it will be twice as hard to keep the separate site up to date. Hope that I'm wrong with this assumption :)

**Comment by chneukirchen** [comment]
Reminder that the rack homepage existed before Github was in use. :)

I think it makes sense to kill it and just redirect to this repo and fill the README with the appropriate info.

There is a HISTORY.md file, but it's not maintained anymore it seeems.

**Comment by antonpaisov** [comment]
IMO having README and CHANGELOG is most important and is actually enough.
I think if there will be a separate site (which I still think is not needed anymore) - it would basically be a page that combines README and CHANGELOG, or what else could there be?

On a side note - is there a quick way to create and fill RELEASES.md for rack?

**Comment by yhirano55** [comment]
> I think it makes sense to kill it and just redirect to this repo and fill the README with the appropriate info.

+100

**Comment by yhirano55** [comment]
@chneukirchen This repo's Wiki is quite old, too. Do you have the plan delete it?

**Comment by antonpaisov** [comment]
@yhirano55 yeah, I also think that would make sense.

In general, I think the approach of getting to the MVP of up to date information with `readme.md`, `releases.md` and `contributors.md` is the best here.

So now someone with an admin access to the repo just needs to do that :)

**Comment by ioquatix** [comment]
Can we come to a consensus on what to do here?

- Kill or update the website.
- Kill or update the wiki.

Please let me know your thoughts.

**Comment by leahneukirchen** [comment]
My opinion above stands. (Please don't break the URL tho, add a static redirect to the repo README.)

**Comment by leahneukirchen** [comment]
The wiki can also go.

**Comment by ioquatix** [comment]
Okay the website has been nuked.

@leahneukirchen can you make me and @tenderlove an admin of the rack org if possible?

**Comment by ioquatix** [comment]
cc @raggi :)

**Comment by antonpaisov** [comment]
@ioquatix I guess we can close the issue now? 🙂

**Comment by ioquatix** [comment]
I wanted to rework the wiki into the README there are some good links. If anyone has time to review the content and make a PR that would be great.
