### ISSUE TITLE
Clarification regarding `Rack::Request#[]`

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1277]
This method issues a warning that it will be deprecated.

But it's used in a lot of code.

What is the reason for it's deprecation and what is the timeline for removal?

I couldn't find any documentation regarding this.

It's a convenient shortcut.

**Comment by twitnithegirl** [comment]
It was moved into helpers about 2 years ago and looks to me like it's not so much that it will go away any time soon just that it's discouraged in lieu of `Request.params[]`. Looks like @sgrif made the original change. Perhaps he can dig in his memory bank and remember why?

**Comment by sgrif** [comment]
I think Aaron and I were pairing on something but I don't remember specifically why. Either way, you should use `request.params[]` as the deprecation warning says. I would guess it'll be removed in the next major version

**Comment by ioquatix** [comment]
It's basically just an alias for `params`.

https://github.com/rack/rack/blob/e2793b256e618e1a796ab639b4050f768cace12d/lib/rack/request.rb#L426-L444

I really like it as it makes code short and concise.

**Comment by twitnithegirl** [comment]
@ioquatix if the issue is that you want to be able to convert to future versions without changing this everywhere, while I think you should just make the necessary changes now or at upgrade, nothing stops you from aliasing this yourself from your own app.

**Comment by matthewd** [comment]
To me, it's confusingly ambiguous because there's more than one thing it could reasonably be indexing: most notably, the `env` that the Request is wrapping, but also the headers.

That's why _I_'d be inclined to remove it, at least.

**Comment by ioquatix** [comment]
> if the issue is that you want to be able to convert to future versions without changing this everywhere, while I think you should just make the necessary changes now or at upgrade, nothing stops you from aliasing this yourself from your own app.

For existing use cases, I'm not sure what we gain by removing this API. That was really my original question. Basically, once this API is removed, I need to make a lot of changes (I'm sure I'm not the only one), but I'm not sure to what end anyone benefits from this removal.

**Comment by twitnithegirl** [comment]
Sorry to overload you with pings @tenderlove but I was wondering if you had thoughts on this, particularly as far as when one might expect this behavior to retired.

**Comment by ioquatix** [comment]
Removing an API would need to be a major version bump, so maybe Rack 3.0?

**Comment by tenderlove** [comment]
Ya, I don't expect we'd remove this until 3.0.  My personal expectation is that `Rack::Request#[]` would reach in to `env` (or at least give you CGI env stuff), and the ambiguity that @matthewd points out is why I want to remove it.  @ioquatix I'd like something shorter than `Rack::Request#params[]`, but more "discoverable" ("discoverable" == "I don't need to read the docs to understand the intention") than `Rack::Request#[]`, and I'm open to suggestions.  I'd also like it if the method didn't return the whole params hash like `Rack::Request#params` does.

**Comment by jeremyevans** [comment]
I think if we are planning on deprecating this in Rack 3, the warning should be emitted even in non-verbose mode at some point before Rack 3.  I'm not sure if that point is now, but the sooner the better in my opinion.  Since 2.1 has already been released, I think 2.2 (master) would be a good time to do that.

**Comment by ioquatix** [comment]
Great. The only thing we haven't done is:

> I'd like something shorter than Rack::Request#params[], but more "discoverable"
