### ISSUE TITLE
Feature request: optional delimiter for add_header

### ISSUE THREAD

**Issue by jamesarosen** [rack/rack#1298]
Many headers are comma-delimited, so the existing `add_header` implementation (which always uses `','`) works great.

But some headers are space-delimited. It would be lovely to be able to provide a delimiter when appending to a header:

```rb
add_header 'My-Header', 'a-value', ' '
```

**Comment by rafaelfranca** [comment]
makes sense. wants to open a pr?

**Comment by jamesarosen** [comment]
Will do!

**Comment by jamesarosen** [comment]
PR rejected.
