### ISSUE TITLE
Does the the Rack::Multipart::MULTIPART RegExp intentionally exclude commas?

### ISSUE THREAD

**Issue by rks** [rack/rack#1300]
The multipart [boundary parsing regular expression](https://github.com/rack/rack/blob/master/lib/rack/multipart.rb#L15) does not allow commas in the boundary string.

I have to accept requests from [an HTTP client](https://www.mathworks.com/help/matlab/ref/matlab.net.http.io.multipartformprovider-class.html) that may include commas in multipart boundary strings. AFAICT, commas are allowed in the boundary:

[RFC 2046](https://tools.ietf.org/html/rfc2046#section-5.1.1), [RFC 1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html):
```
boundary := 0*69<bchars> bcharsnospace

bchars := bcharsnospace / " "

bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
                 "+" / "_" / "," / "-" / "." /
                 "/" / ":" / "=" / "?"
boundary := 0*69<bchars> bcharsnospace 
```

Is Rack's behavior here intentional? If not, I can look into putting together a PR to fix.

**Comment by matthewd** [comment]
Seems original from 4fe5360acf4f1aa680ee00df589bba10b0b56634. I think it needs to change to handle quoted and unquoted values separately.

**Comment by rks** [comment]
I was able to fix this in client code; closing this issue.
