### ISSUE TITLE
Host header doesn't exist for HTTP/2

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1304]
HTTP/2 does away with the `host` header in favour of the `:authority` header where possible.

This is going to cause issues in places like:

https://github.com/rack/rack/blob/5559676e7b5a3107d39552285ce8b714b672bde6/lib/rack/request.rb#L237

An example of this problem was reported to `falcon` a HTTP/2 server for rack applications: https://github.com/socketry/falcon/issues/16

The best solution I can think of, is require that the `:authority` header be written to `env['HTTP_HOST']`.

That being said, maybe it would be better to have a different variable, e.g. `ev['REQUEST_AUTHORITY']`.

**Comment by jeremy** [comment]
https://http2.github.io/http2-spec/#rfc.section.8.1.2.3
> An intermediary that converts an HTTP/2 request to HTTP/1.1 MUST create a Host header field if one is not present in a request by copying the value of the :authority pseudo-header field.

That solution seems appropriate, considering Falcon as an intermediary to the upstream HTTP/1.1 Rack app. (Since HTTP/1.1 requires a Host header but HTTP/1.0 does not, it goes unstated in the Rack spec.)

**Comment by ioquatix** [comment]
@jeremy Thanks for that clarification. It makes sense given the RFC.

Are rack applications explicitly providing an HTTP/1.1 like interface? Is that actually documented anywhere?
