### ISSUE TITLE
Rack::Session::Memcache#test_0009_maintains requires UTF-8 set

### ISSUE THREAD

**Issue by pvalena** [rack/rack#1305]
```
  1) Failure:
Rack::Session::Memcache#test_0009_maintains freshness [/builddir/build/BUILD/rubygem-rack-2.0.5/usr/share/gems/gems/rack-2.0.5/test/spec_session_memcache.rb:115]:
Expected "{\"counter\"=>3}" to include # encoding: UTF-8
"\"counter\"=>1".
```
Can be worked around by `export LC_ALL=en_US.UTF-8`.

**Comment by jeremyevans** [comment]
This test was removed in Rack 2.1.  Now, `Rack::Session::Memcache` is just an alias of `Rack::Session::Dalli` (implemented by the dalli gem).  I don't think we are going to want to fix spec-only issues for rack 2.0 and below unless they affected the common case, so I'm going to close this.
