### ISSUE TITLE
Better scheme detection based on RFC7239

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1310]
It seems like `X-Forwarded-*` is officially deprecated in favour of `Forwarded: *=` as defined in https://tools.ietf.org/html/rfc7239

I believe would be a good idea for Rack to support this.

There is at least one area where modifications are required: `Request#scheme`.

There may be others.

I am happy to submit a PR, but I thought we should discuss this first.

**Comment by jeremy** [comment]
Positive on supporting `Forwarded` in preference to `X-Forwarded-*`, but without deprecation in Rack itself. RFC7239 has some notes on [forward transition](https://tools.ietf.org/html/rfc7239#section-7.4).

**Comment by ioquatix** [comment]
https://github.com/rack/rack/pull/1224

**Comment by jeremyevans** [comment]
This isn't a bug in rack, but a feature request, so I'm going to close this now.  Let's continue the discussion in #1423.
