### ISSUE TITLE
Why are CONTENT_LENGTH and CONTENT_TYPE different from every other header?

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1311]
So... in rack, most incoming headers are converted from `header-name` to `HTTP_HEADER_NAME`, except for `CONTENT_LENGTH` and `CONTENT_TYPE`.

Secondly, there are no constants to define these headers - `Rack::CONTENT_LENGTH` is `Content-Length` which doesn't match up with other constants.

I'm not sure what is the best way to fix this, but I propose for Rack 3.0 we normalise it better.

That means:

- We prefer `HTTP_CONTENT_TYPE` and `HTTP_CONTENT_LENGTH` where applicable.
- We fix/remove the constants.
- We update the related parts of the code.
- We could provide a legacy middleware which renames the keys.

**Comment by matthewd** [comment]
Most of those constants should go away in a `frozen_string_literal: true` world: they appeared in #737 #741, and were not intended for external use. (Though I'm sure they're being used that way, so we'll need to do so with caution.)

As for why those headers get special treatment: https://tools.ietf.org/html/rfc3875#section-4.1 (and its antecedents through https://tools.ietf.org/html/draft-robinson-www-interface-00#section-5 and beyond). It would _look_ more consistent to treat all HTTP headers identically, but we're following a much older, much more widely known, API -- inventing our own slight variation seems more likely to confuse.

**Comment by ioquatix** [comment]
@matthewd Thanks for those links, that explains pretty clearly what's going on and why. It makes sense to follow an RFC for CGI. Do you think we should add some links in the code next to those variables explaining where they come from?

Interestingly enough, it seems that in practice the situation is far from straight forward - I made this list just for my own edification:

- https://github.com/rack/rack/blob/master/lib/rack/handler/cgi.rb#L16
- https://github.com/rack/rack/blob/master/lib/rack/handler/fastcgi.rb#L47
- https://github.com/rack/rack/blob/master/lib/rack/handler/fastcgi.rb#L66-L67
- https://github.com/rack/rack/blob/master/lib/rack/handler/lsws.rb#L17
- https://github.com/rack/rack/blob/master/lib/rack/handler/scgi.rb#L38-L39

One interesting aspect of this is how HTTP/2 works. I think an updated CGI specification based on the HTTP/2 semantic model wouldn't be a silly idea.

Relevant to `CONTENT_LENGTH` is the fact that while HTTP/2 data frames are very similar to chunked encoding, HTTP/2 also allows content-length to be specified, while in HTTP/1 you cannot specify content length with chunked encoding.

`CONTENT_TYPE` is even more unusual, since it has very little bearing on any part of the protocol - at least in HTTP/1 `content-length` has a major affect on the actual IO performed. I took a look at the RFC but I can't understand why there is a special case for this field.

Here is how `CONTENT_LENGTH` is handled in Falcon: https://github.com/socketry/falcon/blob/589fe15ea6935ec32ce7c57c966a325e4b4ebc22/lib/falcon/adapters/rack.rb#L61-L63

The complicated thing is that if there is any kind of content coding, the length is stripped (because it's not valid).

As a suggestion, perhaps we can move the CGI constants into a submodule, e.g. `Rack::Constants`. This allows them to be reused more easily, and isolated from the main Rack code (unless desired). It could be an explicit `rack/constants.rb` and then users would pull it in, if you wanted to deprecated it, it would be easy to have a warning in that specific file.

**Comment by ioquatix** [comment]
Okay I will make a PR.

**Comment by matthewd** [comment]
I don't follow how we'd get people to start requiring that file without first deprecating the constants in-place... at which point I don't see a reason to move them elsewhere instead of just removing them outright.

**Comment by ioquatix** [comment]
I ended up embedding the constants into my own app. Maybe that's the best solution.
