### ISSUE TITLE
Branching / Release management explanation request

### ISSUE THREAD

**Issue by mikegee** [rack/rack#1312]
Our application depends on changes that were merged into master in April, but those changes are not in the released gem. [bundler-audit](https://github.com/rubysec/bundler-audit) is telling me to upgrade to 2.0.6 to resolve a vulnerability, but [master remains at 2.0.1](https://github.com/rack/rack/blob/master/lib/rack.rb#L23).

I'm can't make sense out of this repository's release management by looking at it. Could someone please clarify this for me?

![screen shot 2018-11-06 at 1 50 40 pm](https://user-images.githubusercontent.com/14068/48086531-144cfa80-e1cb-11e8-81e7-765bc923ccca.png)

**Comment by rafaelfranca** [comment]
Master is the 2.1 or 3.x release (not decided yet). 2-0-stable is the 2.0.x releases and the 1-6-stable is for 1.6.x releases.

**Comment by mikegee** [comment]
Thanks @rafaelfranca! Your change to the version in master resolves my problem https://github.com/rack/rack/commit/7eebdd63ab3e7f890a13eb127ccf28cc31d7d505
