### ISSUE TITLE
Rack::Static should automatically expand the root path

### ISSUE THREAD

**Issue by rosenfeld** [rack/rack#1316]
Hi, for a long while I've been fighting an unexpected issue with our application that rarely happens and in weird circumnstances. It was so confusing to me that I wasn't sure whether I should report it to Rack or Puma and ended up creating the issue on Puma:

https://github.com/puma/puma/issues/1642

After a while, some requests to a given static resource served by Rack::Static would return 404 and others would be successfully. Since we use a few Puma workers I guessed that one or a few of them might be affected by some bug in Puma, so I reported there. They suggested me to instrument's Rack's code, which I did, and could confirm `::File.file?(path)` was returning false for the failed requests.

Then I was thinking that most likely `Dir.pwd` is being changed in the application in some not often used requests, so the workers responding to that request would be affected. At least this is the only explanation I can think of so far. I've changed root to expand the path (`File.expand_path('public')`) and deployed the new version. I should know in a month or so whether or not the issue is fixed after this change, but I thought about suggesting the Rack team to improve the way Rack::Static works.

Rack could either introduce a backward-incompatible change that will raise an exception when root is a relative path, or print a warning when a relative path is passed or, what I think would be a better approach, expand that path during the middleware initialization to avoid dealing with such bugs.

I believe I'm not the first one to experience this issue and most likely won't be the last one. I suspect this could also explain this other bug, also reported to the Puma issues tracker:

https://github.com/puma/puma/issues/337

Would you accept a patch to expand the root path upon the middleware initialization?

**Comment by alexdowad** [comment]
@rosenfeld, as a side point, there's something you're missing here: "...so *the workers responding to that request* would be affected". Remember that the working directory is *process-wide* state, and Puma is a multi-threaded app server... so your problem could be caused by one Puma worker thread running `Dir.chdir` at the same time that a *different* worker thread is handling a request for a static file.

I believe that handling requests concurrently on multiple threads is within the confines of what the Rack API allows, so it seems to make sense to harden `Rack::Static` against problems caused by multithreading. Expanding out relative paths during middleware initialization would help to accomplish that.

**Comment by rosenfeld** [comment]
Hi @alexdowad, thanks for your feedback. Puma workers are separate processes. You may configure not only the max number of threads allowed in the pool in Puma, but also how many processes to use. Each spawned process is called a worker in Puma's terminology. Each process will serve up to the max number of configured threads per process. We use more than a single worker with Puma, that's why only the affected workers respond with 404 in the theory I created to explain the different responses.

Indeed our current use of Dir.chdir is not thread-safe, as I just noticed. I'll fix that next week. The easiest would be to wrap it in a mutex, but actually I will instead create a separate script to call that will then change the directory before running the commands, because I already have to call an external application in the Dir.chdir block. Since I use Dir.chdir with a block it should get back to the original pwd after running the block, so maybe there's some Ruby bug here preventing the pwd from being restored under certain conditions, since once the pwd is changed it's never returned back to the original one when this bug is triggered. There's no usage of Dir.chdir in the non-block mode.

I don't want to wrap that block in a mutex because we run a command to convert from pdf to HTML and it could take quite a few seconds to complete and I don't want to pause other requests for that long, so I'm going to wrap that command in another script that will then perform the "cd" command to switch to the target temporary directory instead of doing that with Dir.chdir which is not thread-safe.

But I guess I wouldn't find this bug without your valuable input, so I'm glad you did, thanks :)
