### ISSUE TITLE
Array of hashes with array index should be parsed to array

### ISSUE THREAD

**Issue by choallin** [rack/rack#1319]
I have a html form with an array of hashes. One input field is of type radio. If I make the names of my input fields the standard way, e.g. "name='foo[][bar]" for all my radio buttons I can, of course only check one button from the whole list and not from each row which would be the desired behaviour.  

If on the other hand I use an index in my names, e.g. "name='foo[0][bar]'" than the html form is working, but rack is parsing the params into an hash instead of an array. (Which is for the most cases similar enough, but I do have some problems because of this)

Is this a known restriction, and shoul I live with wthis, or is this a bug because a html form with radio buttons can simply not work with this?

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is the know restriction. A lot of applications already rely on this behavior and changing this would cause a lot of silent breaking changes.
