### ISSUE TITLE
Latest rack that support ruby 1.8.7 ?

### ISSUE THREAD

**Issue by hadan** [rack/rack#1324]
May I know what latest rack version that compatible with ruby 1.8.7 ( and rails 2.3) ?
Thank you

**Comment by mikegee** [comment]
[Rails 2.3](https://rubygems.org/gems/actionpack/versions/2.3.18) depends on `rack ~> 1.1.0`. The highest version of Rack that would allow is 1.1.6.

I don't know if Rack 1.1.6 runs on Ruby 1.8.7 or not, but that should be easy to check.

**Comment by jeremy** [comment]
Rack 1.1.6 supports Ruby 1.8.7. (Rack 2.0.0 dropped Ruby 1.8.7 support.)

**Comment by hadan** [comment]
So theoretically, rack 1.6 should still support ruby 1.8.7 right?

Is this good enough to check if certain version of rack  can run in certain ruby version? 
`ruby -Ilib lib/rack/lobster.rb`

Or should I run full test suite of rack?
