### ISSUE TITLE
Feature request: defaults from ENV variables

### ISSUE THREAD

**Issue by MyBartosz** [rack/rack#1339]
Current `defaults` flow:

1. get value from command line: for example `-p 4000`
2. fallback: default value `9292`

desired flow:

1. get value from command line: for example `-p 4000`
2. fallback: `ENV['RACK_PORT']`
2. fallback: default value `9292`

___ 

In the wiki there is suggestion to use special comment in `config.ru` to force the port via configuration
```ruby
#\ -w -p 3000
```

but I can't parse string in this comment

:boom: 
```ruby
#\ -w -p ENV['RACK_PORT`]
```
:boom:  
___
I just loaded my `.env` configuration in `config.ru`... then I did small change to the defaults behavior in commit  https://github.com/MyBartosz/rack/commit/15d83f2f4e8c01f875f6791002065fb5fc16e3f7

just for the naming consistency in my `.env` file I have:
```ruby
RACK_HOST= ...
RACK_PORT= ...
```
Inline `rackup` options flow remains untouched

In my project I just needed `port` and `host` from `ENV`

What about more `defaults` covered through `.env` like:
```/bin/bash
RACK_VERBOSE=true
RACK_DAEMON=true
RACK_PID=/path/to/server.pid
RACK_SOCKET=(unix | ssl | tcp)
...
```

and more ?

**Comment by MyBartosz** [comment]
There is **right scenario** for `rackup` with `port` and `host` "**extracted**" from default server configs like `config/puma/production.rb`

It's very handy to have `-p` and `-h` options when you build webapp proxy layer then commands to spread instances like:
```/bin/bash
rackup -p 3001 ...
rackup -p 3002 ...
rackup -p 3003 ...
````
works like a ham

in this case the `RACK_HOST` and `RACK_PORT` both have no meaning :disappointed: 

Is there any scenario for `rackup` where this feature will shine :question: :question: :question:

:no_entry: After putting alive the proxy layer I'm not convince anymore :no_entry: 


___
:thinking: even tremendous stupidity didn't prevent me from thinking :thinking:

**Comment by ioquatix** [comment]
Please make a PR if you feel this issue warrants further attention. I think the plan in Rack 3.0 is to remove everything except for the WEBRick adapter and provide better points of integration with 3rd party servers. Things like FCGI are dead, for example. So, it doesn't make much sense having it in Rack core.
