### ISSUE TITLE
TypeError in Request.params method if POST is nil

### ISSUE THREAD

**Issue by Utopism** [rack/rack#1340]
With Redmine V2.6.1 and rack V1.4.7 when a form is submitted with a Post Request the redirected page triggers a TypeError because nil can't be merged to a hash.

In **lib/rack/request.rb** in the params method, could you introduce a defensive test like this :
```ruby
    # The union of GET and POST data.
    def params
      # fix : || {} if self.POST is nil
      @params ||= self.GET.merge(self.POST || {})
    rescue EOFError
      self.GET
    end
```
Thanks a lot

**Comment by jeremyevans** [comment]
I think Rack 1.4 is no longer supported. I think only Rack 1.6, 2.0, and 2.1 are supported now.  I don't think `self.POST` can return `nil` anymore, it either returns a hash or raises.  If you think this is still a bug in a supported version, please submit a failing test or a self contained example showing the problem.
