### ISSUE TITLE
Add REQUEST_URI to linter?

### ISSUE THREAD

**Issue by bryanp** [rack/rack#1342]
Should `ENV["REQUEST_URI"]` be added to the linter? Until recently I had assumed it was guaranteed to have a value, but after a bit of research it seems that `REQUEST_URI` is only provided by some application servers (e.g. puma). Looking to clarify if this is a value that can be expected in the Rack ENV, and if so, propose adding it to the linter.

**Comment by ioquatix** [comment]
It would be good to get clarification on this.

**Comment by jeremyevans** [comment]
As this is not listed in SPEC (https://github.com/rack/rack/blob/master/SPEC), I don't think rack makes any guarantee that the key is required.  Therefore, I do not think it is appropriate for the linter to check this.  There should be no need for the entry, even on the servers that provide it, as you can recreate it using `SCRIPT_NAME`, `PATH_INFO`, and `QUERY_STRING`.

**Comment by ioquatix** [comment]
A couple of servers have standardised it and applications now depend on it... We might need to add it to the SPEC.

**Comment by ioquatix** [comment]
@bryanp you originally raised this issue, if you believe it warrants adding to the SPEC, can you please make a PR for further discussion.

**Comment by ioquatix** [comment]
Also, as a counter point, if this is not added to the SPEC, do you believe I should remove it from Falcon to prevent confusion?

**Comment by jeremyevans** [comment]
@ioquatix I don't think you should necessarily remove it from Falcon simply because it is not in SPEC.  Many webservers include env entries in addition to the ones required by SPEC.  SPEC is the minimally required env entries (and in some cases the behavior of those entries), webservers can provide additional entries as they see fit.

**Comment by bryanp** [comment]
I don't think it needs more discussion--the clarification was helpful though so thanks for the discussion! And I agree with @jeremyevans, leave it in Falcon.

**Comment by ioquatix** [comment]
If it’s not in the SPEC, some new server will miss it.

**Comment by bryanp** [comment]
I don't think that matters much if `REQUEST_URI` isn't a concern of Rack. It's a sort of unofficial convention, you could say. There's an argument to be made that requiring `REQUEST_URI` would be useful to end users, but I'm not sure how best to navigate what could be useful from what Rack should ultimately be concerned about.

**Comment by ahx** [comment]
We are using REQUEST_URI to get the fragment (`#bar` in `/foo#bar`) of the request URI. AFAIK REQUEST_PATH does not include the fragment. So I think it makes sense to add REQUEST_URI that to the spec.
