### ISSUE TITLE
Question: set session cookie in response header

### ISSUE THREAD

**Issue by FilippoProjetto** [rack/rack#1347]
Hi all, 

I am having some issues understanding when the cookie gets reset in the context of session management. 

In particular, reading the following comment: https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L370-L371 I would assume that if I set the expires_after option, then the cookie setting is skipped. However, the if condition seems to do the opposite. Indeed, I would have expected something like: 

`if request.cookies[@key] != cookie[:value] || !cookie[:expires]`

Am I right? What's the intended behaviour? 

Also, it was not clear to me from the documentation that the cookie expires after a certain amount of time from the last activity and not from the login. Could you confirm that?

Thanks!

**Comment by jeremyevans** [comment]
Any of the following options force a session to be committed with the request: :max_age, :renew, :drop, :defer, :expire_after.  When a session is committed with the request, the expires settings is from the time of commit, not the time of login.  Note that "time of login" is not a concept related to cookie expiration.  The most similar idea would be the time of session cookie creation, but that's not something that rack's session cookie support tracks (rack-deadline adds support for it).  Basically, expire_after affects the cookie generated, which will affect how browsers will treat the cookie. It does not skip the setting of the cookie, use the :skip option if you want that.

I hope that answers your questions.  I'm going to close this now.
