### ISSUE TITLE
ENV vars are being set from within the code

### ISSUE THREAD

**Issue by natetech333** [rack/rack#1349]
File: urlmap.rb

ensure
 75       env[PATH_INFO]   = path
 76       env[SCRIPT_NAME] = script_name
 77     end

This is causing some kind of conflict with the devise gem. I am still debugging the incompatibility. My Rails config does not set PATH_INFO. And devise is sending my users to PATH_INFO after they sign in.

PATH_INFO is being changed from the root path to the devise sign in path somewhere between the devise gem code and rack code. I wanted to bring this up because I don't think code should ever set an ENV var from within the code. ENV vars should be setup from the config. And they should be frozen. Am I wrong?

**Comment by rafaelfranca** [comment]
That `env` there is not the `ENV`. `env` it is a hash that belongs to rack, while `ENV` is the OS environment.

**Comment by natetech333** [comment]
Please ignore my question. I thought env['PATH_INFO'] was a config setting. It's a little confusing because we use env to retrieve information about the environment that changes like the current url and also to retrieve config info.

**Comment by natetech333** [comment]
Can I do a pull request to change the env variable to rack_env ?

**Comment by rafaelfranca** [comment]
`env` is a know name in the rack community, I think renaming will do more harm than good. The environment that contains config is called `ENV`, all with capital letters. Closing since this is not an issue. Thank you so much for opening it.
