### ISSUE TITLE
Support for SameSite=None cookies

### ISSUE THREAD

**Issue by hennikul** [rack/rack#1359]
I have implemented support for the new "None" value for SameSite on cookies in this PR:
https://github.com/rack/rack/pull/1358

We are using Rack with Ruby on Rails for www.aid.no, one of the largest ID providers for online newspapers in Norway. We rely on a third party session cookie that is set in the Rails application on the different newspaper domains our customers consume content on. Google has recently announced that setting cookies for use as a third party cookie with Chrome will require the cookie to be marked with SameSite=None, the default behavior will be the current SameSite=Lax setting. We need to have a solution ready before this release is out.

My understanding is that the new version will be released at the end of July, based on this page:
https://web.dev/samesite-cookies-explained/

According to Google, most other languages has added support for this value already. It can also be found in the latest version of the spec:
https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03

**Comment by jeremy** [comment]
Closed by #1358
