### ISSUE TITLE
Rack::Utils.best_q_match with more than 2 mime types seems returning wrong value

### ISSUE THREAD

**Issue by krzysiek1507** [rack/rack#1367]
According to this comment, https://github.com/rack/rack/blob/d671a0c3379bc05f17e3f670d943c6243c333df0/test/spec_utils.rb#L393 the following code should return...? What it should return? `text/plain` or `text/html`?
Currently it returns `text/app` so none of them.
```ruby
Rack::Utils.best_q_match("text/plain,text/html,text/app", %w[text/html text/app text/plain])
=> "text/app"
```

**Comment by krzysiek1507** [comment]
```ruby
[2] pry(main)> Rack::Utils.best_q_match("text/plain,text/html", %w[text/html text/plain])
=> "text/html"
[3] pry(main)> Rack::Utils.best_q_match("text/html,text/plain", %w[text/html text/plain])
=> "text/plain"
```

Does it work as expected?

**Comment by ahorek** [comment]
yes, the preference is in reverse order https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by krzysiek1507** [comment]
@ahorek I can't see such information on this page.

**Comment by ahorek** [comment]
you're right, it doesn't say anything about the order of types with the same preference
**Accept: text/html,text/plain**
based on this information I think both responses (html/text) are correct. None of them has the highest priority.

on some Ruby implementations the order is undefined https://bugs.ruby-lang.org/issues/1089

windows
```
Rack::Utils.best_q_match("text/plain,text/html,text/app", %w[text/html text/plain])
=> "text/plain"
```

linux
```
Rack::Utils.best_q_match("text/plain,text/html,text/app", %w[text/html text/plain])
=> "text/html"
```
maybe it should be documented somewhere...
https://github.com/rack/rack/blob/d671a0c3379bc05f17e3f670d943c6243c333df0/test/spec_utils.rb#L395
