### ISSUE TITLE
Release Multi-Mapping Support

### ISSUE THREAD

**Issue by tpendragon** [rack/rack#1387]
https://github.com/rack/rack/pull/1187

Support for multiple X-Accel-Mappings was merged into master quite some time ago, but never released. Could we get this put into 2.x?

Thanks!

**Comment by gsar** [comment]
@rafaelfranca @eileencodes  is a rack release in the works? there seem to be a number of fixes on `master` that are worth releasing. setting `SameSite=None` on cookies currently is not possible with 2.0.7 and this is going to become important as Chrome is enforcing `SameSite=Lax` when not set explicitly in Jan 2020, which is just a couple of months away.

**Comment by jrgns** [comment]
Yes, please, can we get a new release? The last one is already yonks old.

**Comment by firien** [comment]
this was not included in v2.0.8 released 2019/12/18

**Comment by ioquatix** [comment]
@tenderlove said he would release 2.1.0 but I don't know what the timeframe for that is. I hope this is included in that release. If it was merged into master, it should be on track for that release.

**Comment by jrgns** [comment]
@firien 2.0.8 was a security release. only a single commit was released.

**Comment by tenderlove** [comment]
@ioquatix I think we can ship pretty much any time now.  I wanted to wait until we got that security fix out the door, but since that's done I think we're good to go.

I'm on vacation right now, so I'm slightly worried about shipping something when I can't give more of my attention to the Internet.  Can I suggest we ship 2.1.0 on Jan 6 (or that week)?

**Comment by ioquatix** [comment]
That’s fine by me!

**Comment by tenderlove** [comment]
👍 I'll ship that week then!

**Comment by jeremyevans** [comment]
2.1.0 was released yesterday, so I think this can be closed.
