### ISSUE TITLE
Session id generation and usage is racy

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1406]
```ruby
#!/usr/bin/env ruby
​
require 'rack/session/pool'
​
# This just increases the chance of a collision.
module Rack
  module Session
    class Abstract::Persisted
      def generate_sid
        rand(2**16).to_s(16)
      end
    end
  end
end
​
store = Rack::Session::Pool.new(nil, secure_random: false)
pool = store.instance_variable_get(:@pool)
​
session_data = {"oh" => "my!"}
​
threads = []
​
mutex = Mutex.new
​
1000.times do
  threads << Thread.new do
    while true
      # This replicates the essential parts of Persisted#commit_session
      request = Rack::Request.new({
        'rack.multithread' => true
      })
      
      session = Rack::Session::Abstract::SessionHash.new(store, request)
      options = session.options
      
      sid = store.generate_sid
      
      session_id = store.delete_session(request, sid, options)
      
      if pool.key?(session_id)
        puts "Generated SID #{sid} was already used!"
      end
      
      store.write_session(request, session_id, session_data, options)
      
      unless pool.key?(session_id)
        puts "Generated SID #{sid} was deleted!"
      end
    end
  end
end
​
threads.each(&:join)
​
# >./rack.rb
# Generated SID f577 was already used!
# Generated SID b29 was deleted!
# Generated SID 1eb3 was deleted!
# Generated SID d2b1 was deleted!
# Generated SID 6b9e was deleted!
```

This code replicates `commit_session`.

There are race conditions between generating a session id and using it. Because of that, if two threads generate the same session id, they can clobber each other later in the method. In the worst case, this would mean that a user session ends up with the wrong user.

The severity of this issue is low, because it is:

- reasonable to assume that collisions between session ids are limited
- other validations (like user agent or IP address checks) can detect the incorrect allocation of session state to a different browser.

That being said, the logic of sessions is technically racy and we should consider whether it needs to be fixed. While I only considered the memory store, I believe it can affect other implementations.

I discussed this with @tenderlove and we decided we decided the impact of this issue on production systems is minimal hence the public disclosure of the issue.

**Comment by ioquatix** [comment]
I've done some further investigation.

My initial report only applies to code paths that generate session ids without updating `@pool`, which requires `renew: true`, e.g.

```
use Rack::Session, renew: true
```

I don't know if there are other code paths which can trigger this behaviour, but I haven't found any yet - normal code path is okay.

The problem in `commit_session` occurs when you get to :

```
session.send(:load!) unless loaded_session?(session)
```

At that point, it's possible to have a valid session id without it being in the pool which allows another session to allocate the same session id because `generate_sid` can generate the same id if it's not in the `@pool` already: `break sid unless @pool.key? sid`.

Probably the correct option is not to reuse the session id after deleting it. I'll submit a PR to that effect.

**Comment by ioquatix** [comment]
Noticed this:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/30030/68911909-e4e7ab00-0799-11ea-9567-b3e3381c29dd.png">

Seems like it might be related.

**Comment by jeremyevans** [comment]
@ioquatix regarding that test issue, see #1305.

**Comment by jeremyevans** [comment]
@ioquatix Were you able to submit a PR for not reusing the session ID after deleting it?

**Comment by ioquatix** [comment]
I will circle back to these issues but I haven't had time yet. I have a bunch on my plate right now.

**Comment by ioquatix** [comment]
This is probably fixed by <https://github.com/rack/rack/pull/1620>.
