### ISSUE TITLE
Time to release 2.0.8?

### ISSUE THREAD

**Issue by nougad** [rack/rack#1410]
The last release for 2.0.7 was beginning of April and a lot of changes accumulated since then. There are ~350 commits in master which are not included in 2.0.7. Also the important cookie expiry format fix is waiting for release since a couple of years: https://github.com/rack/rack/issues/1100

Whats the status? Should people use master branch to get fixes or is it time for a 2.0.8/3.0.0 release?

**Comment by rafaelfranca** [comment]
Thank you for the suggestion. It is time for a released when the maintainer decide it is.

**Comment by ioquatix** [comment]
I agree, it would be great to make 2.0.8 release! Do we have a milestone for it and are there outstanding issues?

**Comment by ioquatix** [comment]
Also, I wonder given all the changes, should it be a 2.1.0 release - it's no longer just a patch release if there are new interfaces/surface area.

**Comment by ioquatix** [comment]
Sorry, did not mean to set a milestone... That being said, maybe we should clear up the old milestones.

**Comment by rafaelfranca** [comment]
master is 2.1.0 already isn't? I think there are a few breaking changes there already, so I'd double check before a release.

**Comment by ioquatix** [comment]
@tenderlove do you have any time to help with this?

**Comment by tenderlove** [comment]
Ya I can take a look today

**Comment by tenderlove** [comment]
I looked through most of the diffs.  I think we should call master `2.1.0`, but otherwise it looks good.

**Comment by ioquatix** [comment]
Okay great! Do you want to handle the release?

**Comment by nougad** [comment]
Thank you for looking into this! Should the issue get reopened?

Does something speak against including https://github.com/rack/rack/pull/1144 or does the commit require a major version bump?
