### ISSUE TITLE
Rack gem currently does not include '491' HTTP error status code. Please include the same.

### ISSUE THREAD

**Issue by kvgana** [rack/rack#1425]
Rack gem currently does not include '491' HTTP error status code. Please include the same.

**Comment by ioquatix** [comment]
Can you make a PR?

**Comment by mikegee** [comment]
I can't find any evidence that 491 is a legitimate HTTP response code. Please include a link to supporting documentation in the PR.

https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by ioquatix** [comment]
It looks like it comes from SIP: https://en.wikipedia.org/wiki/List_of_SIP_response_codes

As this is probably out of scope for Rack, I am closing this issue, however please feel free to submit a PR with the documentation as requested so we can consider it.
