### ISSUE TITLE
Support SameSite: None

### ISSUE THREAD

**Issue by hennikul** [rack/rack#1451]
On February 4th 2020 Google will release a new Chrome version (80) that changes default behavior of SameSite flag on cookies. More info here:
https://www.chromestatus.com/feature/5088147346030592
https://digiday.com/media/what-is-chrome-samesite/

For sites implemented using Rack to work with party cookies a new release of Rack is needed. This release needs to include the following patch:
https://github.com/rack/rack/commit/c859bbf7b53cb59df1837612a8c330dfb4147392

Will there be a new Rack-release in time for the new Chrome release?

**Comment by ahorek** [comment]
it's planned for the next week https://github.com/rack/rack/issues/1387
