### ISSUE TITLE
Rack 2.1.0 breaks ActiveStorage

### ISSUE THREAD

**Issue by thedanbob** [rack/rack#1464]
I submitted [this issue](https://github.com/rails/rails/issues/38214) to Rails and they sent me here.

Rack::File (now Rack::Files) no longer accepts nil as a first parameter per this commit: https://github.com/rack/rack/commit/8f85307711ca5e7a4729641fda1552890ffa129a. `File.expand_path` throws a TypeError.

This breaks the ActiveStorage file server: https://github.com/rails/rails/blob/master/activestorage/app/controllers/concerns/active_storage/file_server.rb#L6

**Comment by ioquatix** [comment]
What do you think is the right behaviour?

- Do nothing - nil is not a valid root path.
- Allow nil root path - potentially other operations broken (although maybe not in practice).

I'm not quite sure what is the right way forward. We did break backwards compatibility.

**Comment by rafaelfranca** [comment]
I think we should keep `nil` being a valid path, at least in 2.1. It works today for Active Storage use case.

**Comment by ioquatix** [comment]
Okay I can make a PR.

**Comment by rafaelfranca** [comment]
👍
