### ISSUE TITLE
CHANGELOG is missing 2.1.0

### ISSUE THREAD

**Issue by Aupajo** [rack/rack#1467]
The [CHANGELOG](https://github.com/rack/rack/blob/master/CHANGELOG.md) doesn't currently indicate what's changed between 2.0.8 and 2.1.0.

**Comment by ioquatix** [comment]
Do you have time to make a PR? I'm currently up to my neck in bug hunting.

**Comment by ioquatix** [comment]
Here is a good start: https://github.com/rack/rack/blob/master/CHANGELOG.md#unreleased

**Comment by Aupajo** [comment]
@ioquatix Can do! How do I know what went into 2.1.0? Is it okay to move everything in “Unreleased” to 2.1.0?

**Comment by ioquatix** [comment]
@Aupajo yes that should be good, and also there should be a few (like 2-4) oustanding PRs on the 2.1.0 tag which are not in that list.

**Comment by Aupajo** [comment]
Great. I'll hunt for them and open a PR.
