### ISSUE TITLE
Clarify: Should we use Rack::File or Rack::Files

### ISSUE THREAD

**Issue by DannyBen** [rack/rack#1473]
Can someone please clarify the intentions in regards to `Rack::File` and `Rack::Files`?

Here are the confusing facts:

- There was a [7 year old pull request](https://github.com/rack/rack/pull/305) that changes `File` to `Files`, which was just recently merged.
- There is a [deprecation warning](https://github.com/rack/rack/blob/2.1.0/lib/rack/file.rb) in the currently released 2.1.0 version.
- The deprecation warning [seems to be removed in master](https://github.com/rack/rack/blob/master/lib/rack/file.rb), but `File` is still an alias to `Files`.

So - should we use `Rack::File` or `Rack::Files`? Will they both stay for the foreseeable future, or is `Rack::File` just here for backwards compatibility, and should be considered deprecated?

For reference, `Rack::File` was used in sidekiq, and [we were not sure if this should be changed or not](https://github.com/mperham/sidekiq/pull/4424).

**Comment by ioquatix** [comment]
Use `Rack::Files`. Because `Rack::File` is confusing when used in combination with `::File`. The removal of the deprecation notice sends the wrong message. It's definitely deprecated and will be removed in Rack 3.x.
