### ISSUE TITLE
Prevent SameSite=None header if the browser will fail to parse it

### ISSUE THREAD

**Issue by myxoh** [rack/rack#1503]
Recently Rack introduced the ability to set the flag: `same_site: none`

https://github.com/rack/rack/pull/1358

As part of the discussion https://github.com/bnorton shared a gist  https://gist.github.com/bnorton/7dee72023787f367c48b3f5c2d71540f based on the rules and guidelines of the Chromium team => https://www.chromium.org/updates/same-site/incompatible-clients

I believe we should upstream that gist so that we automatically prevent sending the `:none` header if the browser will fail to parse it.

Ideally it would be nice if the users of rack could just set the cookies without having to worry about the user agent.

Thoughts?

**Comment by rafaelfranca** [comment]
It is not responsibility of Rack to deal with browser compatibility. If the developer set the option, rack should send it. The application that should be checking if the option should be set or not.
