### ISSUE TITLE
Rack > 2.0.8 [400-499] Response Body Empty

### ISSUE THREAD

**Issue by kjanoudi** [rack/rack#1520]
For any error from 400, 401, 404, etc, the response body received is empty. The curious thing is that curl seems to return a response, but Postman, chrome browser, etc do not.

![image](https://user-images.githubusercontent.com/4011484/73117524-deea1500-3f14-11ea-8243-c05348ecc8ca.png)

**Comment by ioquatix** [comment]
That’s strange can you give a small repro?

**Comment by andreas-sotnik-2k19** [comment]
@kjanoudi @ioquatix 

I have the same issue in several of my apps after I updated rack version in my Gemfile.

In logs I see something like:

![Screenshot 2020-01-29 at 15 32 10](https://user-images.githubusercontent.com/47086665/73360932-959b1c00-42ac-11ea-9838-b5ea6e08f61e.png)

and

![Screenshot 2020-01-29 at 15 36 15](https://user-images.githubusercontent.com/47086665/73361181-1a863580-42ad-11ea-91b7-e26133d7c0c3.png)

When I comment out the following line from application.rb (in my Rails app) everything starts to working well:

`config.middleware.insert_after ActionDispatch::Static, Rack::Deflater`

I guess it's not a solution but a temporary "patch" to prevent apps from failing...

Sorry I'm not giving more details as I don't really understand in what direction to look here.

**Comment by caifara** [comment]
In (all) versions of Rack > 2.0.8 (tested until 2.1.2) we have some (activeadmin) pages rendering incomplete html.

The response object contains the complete expected html, but the response in the browser shows incomplete html mid-tag. Example:

````
<! –– valid html -->
<div class="some_cla
`````

**Comment by jeremyevans** [comment]
@caifara It sounds like you have an application that sets the Content-Length header incorrectly, which is a bug in the application.  Previously Rack::Response would end up overwriting the Content-Length header, but now it does not, so the bug in the application is now exposed.  You should fix the application to set the Content-Length header correctly. I'm not 100% sure that is the issue, but based on the limited information you provided, that is my best guess.

**Comment by kjanoudi** [comment]
I'm not sure but it doesn't sound like any of the three issues mentioned here are directly related. However,  i know i was never setting the content-length header manually on my responses. I will try to get a way to reproduce it set up in the next week or two

**Comment by ioquatix** [comment]
In the error messages provided above, it looks like body is nil. Is that acceptable in the SPEC? I would assume it's okay, but maybe we need to revisit that.

**Comment by ioquatix** [comment]
`Rack::Response` does the following:

```
      # Keep track of whether we have expanded the user supplied body.
      if body.nil?
        @body = []
        @buffered = true
        @length = 0
```

**Comment by ioquatix** [comment]
A casual reading of the `Rack::Response` code does not show an obvious way that it can return a nil body.

**Comment by jeremyevans** [comment]
A `nil` body violates SPEC unless you define `NilClass#each`. 

Looking at `Deflater`, it sets `@body = nil` in `close`.  So unless `nil` is returned by the app, one other way this could happen is if `close` was called before `each` (though looking at the code I'm not sure how that could happen).

There is no clear indication any of the problems mentioned in this issue are due to a bug in Rack, and therefore I think this issue should be closed.

**Comment by ioquatix** [comment]
If someone can provide a repro, please open a new issue. Thanks for your effort.
