### ISSUE TITLE
Symbols missing

### ISSUE THREAD

**Issue by Lewiscowles1986** [rack/rack#1534]
In looking to update capybara, we get a new Rack version. For some unknown reason this results in rack internals we are using not working 

https://github.com/rack/rack/compare/2.0.8...2.1.1

* https://github.com/rack/rack/blob/b40583b4abfd6d16381308ed421a4751562fa91d/lib/rack/utils.rb#L560
* https://github.com/rack/rack/blob/799a520a015de5938bc01faa8e90b76589c6e7d3/lib/rack/utils.rb#L566

I believe it may be something around here

* https://github.com/rack/rack/compare/799a520a015de5938bc01faa8e90b76589c6e7d3..b40583b4abfd6d16381308ed421a4751562fa91d#diff-7c1a24d5b2fe58a6f925c7cacc6c55e7R558

Error (after changing :bad_request to 400 literal)

```
ArgumentError:
  Unrecognized status code :error
```

Error (initial)

```
ArgumentError:
  Unrecognized status code :bad_request
```

**Comment by Lewiscowles1986** [comment]
I experimenting with reverting

```
    def status_code(status)
      if status.is_a?(Symbol)
        SYMBOL_TO_STATUS_CODE.fetch(status) { raise ArgumentError, "Unrecognized status code #{status.inspect}" }
      else
        status.to_i
      end
    end
```

**Comment by jeremyevans** [comment]
`Rack::Utils::SYMBOL_TO_STATUS_CODE[:error]` doesn't exist (`:internal_server_error` instead of `:error` should work).  `:bad_request` should work, though.

Can you please submit a failing test or a minimal self contained example showing the error?

**Comment by Lewiscowles1986** [comment]
Looks like it's [this](https://github.com/rack/rack/pull/1034) and I've misunderstood the original PR comment on our internal repo... Leading to the erroneous conclusion none of the statuses work.

**Comment by cycomachead** [comment]
I don't necessarily have a problem with this change, but I do wish this would have been called out in the changelog a bit more clearly. IMO, it's a breaking change -- regardless of any semver talk, it would have been helpful if the change mentioned that rack will just blowup now. We seem to use `status: :error` in our app, which I don't really know the origins of. Easy enough to fix, but also breaks things a bit. That's all.

**Comment by jeremyevans** [comment]
@cycomachead This appears to be documented clearly in the changelog:

```
Make `Utils.status_code` raise an error when the status symbol is invalid instead of `500`
```

It's a bug fix, IMO.  Unfortunately, all bug fixes are incompatibilities.
