### ISSUE TITLE
Porting the SPEC file to Markdown

### ISSUE THREAD

**Issue by boazsegev** [rack/rack#1563]
IMHO, markdown will make the SPEC file easier to both read and maintain.

This is even more relevant now that the rack website appears to be no more than a link to the GitHub repo.

Thoughts?

**Comment by jeremyevans** [comment]
SPEC is already in RDoc format, so I see no point in changing it to Markdown.  However, I think it does make sense to name the file SPEC.rdoc so that GitHub renders it nicer.  I'll submit a pull request for that.

**Comment by boazsegev** [comment]
Thank you @jeremyevans ,

The name change is definitely a great help for reading the SPECs online 👍🏻🙏🏻

IMHO, it will be easier to collaborate on a markdown document (if we're making changes for the 3.0 release), though I'm probably biased (my `rdoc` formatting abilities are really bad).

Thanks again. It reads much better now 🙏🏻

**Comment by ioquatix** [comment]
https://github.com/rack/rack/pull/1567
