### ISSUE TITLE
`SERVER_ADDR` is, it isn't mentioned in SPEC.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1570]
`SERVER_NAME` required per SPEC, so we should never get here.  Also, I'm not sure what `SERVER_ADDR` is, it isn't mentioned in SPEC.

_Originally posted by @jeremyevans in https://github.com/rack/rack/pull/1561/files_

So, should we remove it?

**Comment by jeremyevans** [comment]
I think we should remove support for `SERVER_ADDR`.

**Comment by ioquatix** [comment]
I will implement this in a subsequent PR.
