### ISSUE TITLE
Is `SERVER_PORT` required?

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1571]
`SERVER_PORT` is required, so I would leave it in the check a few lines above.  I do agree that we should check it is an integer.

_Originally posted by @jeremyevans in https://github.com/rack/rack/pull/1561_

Tests allow for it to be an empty string or not specified at all. The recent PR https://github.com/rack/rack/pull/1561 codifies this to `Rack::Lint`. Do we want to change this?

**Comment by jeremyevans** [comment]
As discussed, it may not make sense for unix sockets.  So we may want to say it isn't required, but if set it must be an integer.

**Comment by ioquatix** [comment]
Implemented.

**Comment by ioquatix** [comment]
I reverted this. There were a ton of specs that provided a string containing an Integer.

I think we can revisit this for 3.0.

**Comment by poloka** [comment]
Is a correction for this mistake being released shortly?

**Comment by ioquatix** [comment]
We made this optional in https://github.com/rack/rack/commit/2266e086b665e086295450a33ae0abcda0868453

So the answer is, no. It must be nil or convertible to an integer `to_i`.
