### ISSUE TITLE
Support TruffleRuby

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1579]
https://github.com/rack/rack/runs/434161173

cc @eregon 

What can I do to help?

**Comment by eregon** [comment]
Also filed as https://github.com/oracle/truffleruby/issues/1898.
We need to figure out what goes wrong and fix it.
Probable some incompatibility in TruffleRuby.

It might be worth trying a run with `truffleruby-head` as that has quite a few bug fixes.

**Comment by eregon** [comment]
With `truffleruby-head`, 3 failures instead of 5, that's nice: https://github.com/eregon/rack/runs/434669369

**Comment by eregon** [comment]
The last issue is `Rack::ShowExceptions#test_0002_handles exceptions with backtrace lines for files that are not readable`.

`refute_includes(res.body, 'bad-backtrace')` passes on MRI because StringIO#inspect does not show the contents of the StringIO, while it does on TruffleRuby:
```
Rack ENV:

MRI:
rack.errors | #<Rack::Lint::ErrorWrapper:0x00005648277a37b0 @error=#<StringIO:0x0000564827791ec0>>

TruffleRuby:
rack.errors | #<Rack::Lint::ErrorWrapper:0x3bd0 @error=#<StringIO:0x3b90 @__data__=#<StringIO::Data:0x3b98 @encoding=#<Encoding:UTF-8>, @lineno=0, @pos=78, @string="RuntimeError: foo\n\tnonexistant.rb:2:in `a': adf (RuntimeError)\n\tbad-backtrace\n">, @append=false, @readable=true, @writable=true>>
```

**Comment by eregon** [comment]
While convenient for debugging to see the contents of the StringIO, it's potentially information leaking that wouldn't happen on MRI, so we'll just use the same output as MRI for StringIO#inspect.

**Comment by eregon** [comment]
Tests pass with my fixes, I'll merge them to TruffleRuby and then do a PR here.

**Comment by ioquatix** [comment]
I agree with all your assessments.

StringIO could contain multi-mb of data so probably not best to print it out.

Maybe not bad to include some detailed information on `#inspect`, e.g. `#<StringIO:0x1234 4MiB UTF-8>` or something.

To be honest, the Rack spec seems flawed too.

I read some comments about the encoding. That also seems a bit whack.
