### ISSUE TITLE
Repurpose `rackup` Executable.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1594]
`rackup` tries to present a unified interface for servers.

- It uses a static list of named servers and tries them in order. That list makes it non-trivial for new servers to gain traction (since they need to get in the list).
- It doesn't expose options for TLS, etc which have become a requirement for HTTP/2.
- It doesn't expose enough controls for servers which provide advanced mechanisms for concurrency.

My suggestion would be, if we do decide to keep `rackup`, that we actually limit it to the included `webrick` server only. The concept of `Rack::Handler` should be deprecated and removed.

**Comment by ioquatix** [comment]
Also, now that I think about it, maybe it's even possible to move this to a `rack-handler` gem.

**Comment by boazsegev** [comment]
I agree that `rackup` is less than ideal and perhaps could be bundled in an external gem.

However, some of it's shortcomings are not that terrible.

> It doesn't expose options for TLS, etc which have become a requirement for HTTP/2

IMHO, it's not a big issue.

Applications that require TLS can use the command line of their server of choice. This concern is mostly deployment specific and doesn't often affect development.

Besides many applications (certainly all of the ones I deployed) run behind an additional TLS layer such as nginx / apache with a reverse proxy (not to mention that sometimes a load balancer is tossed into the mix) - so they don't always run HTTPS on the internal network (though they probably should).

> It doesn't expose enough controls for servers which provide advanced mechanisms for concurrency.

Very good point. It would be wonderful to solve this.

As a workaround, maybe allow `rackup` to accept foreign arguments - this would (at least) allow a server to accept arguments that `rackup` doesn't support.

**Comment by jeremyevans** [comment]
> As a workaround, maybe allow `rackup` to accept foreign arguments - this would (at least) allow a server to accept arguments that `rackup` doesn't support.

`rackup` supports this via the `-O` option.  Not sure about other handlers, but the puma handler does handle it (this is from the `rackup -h` output):

```
Server-specific options for Rack::Handler::Puma:
  -O Threads=MIN:MAX       min:max threads to use (default 0:16)
  -O Verbose               Don't report each request (default: false)
```

I think `rackup` should stay with rack for backwards compatibility.  I do think we should drop handlers with dependencies that are not included in Ruby.  The other handlers we don't really test and are not in a good position to maintain.

The static list of servers is only used to select a default.  If you pass a specific server, rack will use it.  I agree the static list gives a preference to specific servers, and that isn't fair.  Maybe we can just remove the list and make webrick the default, since that is the only one we know for sure will be available.  That will probably cause people to complain, though.

**Comment by boazsegev** [comment]
Thank you @jeremyevans for the quick reply.

The `-O` option might (AFAIK) add options to the `opt` hash, but it doesn't allow servers to read command line arguments.

When trying `-O -t 1`, the execution fails with: `configuration ./1 not found`

When trying `-O -t=1` (iodine supports both variants), the option is ignored.

IMHO, this is not really the same as allowing server handlers to read command line arguments.

Perhaps it would make sense to allow `--` (or `-O --`)  and allow all arguments after the `--` to "pass through", safely ignored?

**Comment by jeremyevans** [comment]
Considering `webrick` is no longer in stdlib, we cannot be sure that any web server is available.  I vote for just leaving things as-is for backwards compatibility, and closing this.

**Comment by ioquatix** [comment]
I'm not really happy with the status quo.

**Comment by jeremyevans** [comment]
Well, let's address the points in your original post:

> * It uses a static list of named servers and tries them in order. That list makes it non-trivial for new servers to gain traction (since they need to get in the list).

You can use a handler not on the list.  There's no ability to avoid a default list without forcing the user to specify a handler every time, which seriously hurts usability.

> * It doesn't expose options for TLS, etc which have become a requirement for HTTP/2.

In the cases where rackup is normally used, these aren't needed.  Handlers can add their own options to handle it.  I'm not opposed to adding options if you want to add these options.

> * It doesn't expose enough controls for servers which provide advanced mechanisms for concurrency.

In the cases where rackup is normally used, these aren't needed.  Handlers can add their own options to handle it. I'm not opposed to adding options if you want to add these options.

> My suggestion would be, if we do decide to keep `rackup`, that we actually limit it to the included `webrick` server only. The concept of `Rack::Handler` should be deprecated and removed.

I think limiting it to webrick no longer makes sense as webrick has been removed from stdlib.

> I'm not really happy with the status quo.

Well, we can add support for the options you want to add.  As long as the existing behavior continues to work.  We shouldn't break backwards compatibility without a very good reason to do so.

**Comment by simi** [comment]
IMHO rackup is still very useful for super simple apps for local testing.

> It uses a static list of named servers and tries them in order. That list makes it non-trivial for new servers to gain traction (since they need to get in the list).

This approach can be reversed as well. We can make the implementation to the server side and assume just by using handler what to call. For example when starting `rackup -s Puma`, we can assume `Puma.start_rack` is available and pass all info needed in there. That will eliminate any handlers in `rackup`. We can keep only webrick one, keep it default and gracefully fail when no `-s` is passed and WEBRick is not present (with simple command `gem install webrick:x.y.z` suggestion to install it).

On the otherside, you can get the same effect (super fast locally running the app) using puma directly, since it by defaults load `config.ru` as well. And for development you still need to use reloader like `shotgun` gem.

Giving up on `rackup` is maybe really easier.

**Comment by jeremyevans** [comment]
@simi It sounds like you are proposing the same thing as @ioquatix , removing puma and falcon from `Rack::Hanlder::SERVER_NAMES`.  We already only ship webrick and cgi handlers (the other handlers are already server-side).  I don't see the point of removing puma or falcon from the list of default servers.  If you have puma and/or falcon installed, what's the advantage to the user of using webrick?

**Comment by ioquatix** [comment]
1. I think gems should register handlers into the list or we should use a `Class#subclasses` style approach (or constants, etc).
2. Should we discourage using `rackup` for production usage? I'm all for easy to get started, provided we don't over-complicate the command. I think we should reduce the internal option handling and instead delegate this to the handler.
3. `rackup` is the only piece of code that refers to `RACK_ENV` and I think if we can remove it we remove a huge cognitive burden on all downstream code that tries to deal with this.
4. I don't think `rackup` should deal with daemonization or pid files, this is largely the responsibility of process managers and they do a **much** better job of this. As a consequence, we should remove it and always just run in the foreground/defer to the specific handler implementation.

**Comment by boazsegev** [comment]
Reading through this thread again, I came to the opinion that it would be best to leave `rackup` as is for backwards compatibility and let it slowly fade away (and perhaps eventually deprecated).

My biggest reason for this is that **the most commonly used servers provide their own CLI, while maintaining `rackup` support forces some code duplication** (and extending `rackup` further could force more code duplication).

The current `rackup` is good enough for maintaining backwards support. Supporting less features only encourages developers to migrate to the CLI shipped with the server (which one would assume to be the better option).

I hope my reasoning helps the discussion.

**Comment by jeremyevans** [comment]
> 1. I think gems should register handlers into the list or we should use a `Class#subclasses` style approach (or constants, etc).

How do you propose this should work?  I would like an approach that avoids the disaster that is minitest plugins (which use a similar idea).

> 2. Should we discourage using `rackup` for production usage? I'm all for easy to get started, provided we don't over-complicate the command. I think we should reduce the internal option handling and instead delegate this to the handler.  

I'm fine adding language stating rackup is designed for development usage.  I don't think removing options makes sense, unless the options are currently buggy or not working correctly.  Similarly, I don't think adding features is a good idea either.  I'm not in favor of encouraging new use, but I want to avoid breaking existing use.

> 3. `rackup` is the only piece of code that refers to `RACK_ENV` and I think if we can remove it we remove a huge cognitive burden on all downstream code that tries to deal with this.

I don't think anything we do with rackup will reduce a cognitive burden on downstream code.  For example, Roda uses RACK_ENV in certain cases, and I wouldn't be changing that regardless of what we do with rackup.

> 4. I don't think `rackup` should deal with daemonization or pid files, this is largely the responsibility of process managers and they do a **much** better job of this. As a consequence, we should remove it and always just run in the foreground/defer to the specific handler implementation.

I'm against breaking backwards compatibility just because you don't think it is a good idea.  I wouldn't use rackup for daemonization, but I don't want to break someone's environment if they do.

**Comment by ioquatix** [comment]
> disaster that is minitest plugins

care to elaborate? I don't think Rack should be a gate keeper on server selection (depending on installed gems makes more sense).

**Comment by jeremyevans** [comment]
IMO, we should not under any circumstances try to introspect installed gems and automatically load code from them.  Trying to require files, and handling load errors if they aren't present, is as far as we should go.

**Comment by ioquatix** [comment]
> IMO, we should not under any circumstances try to introspect installed gems and automatically load code from them.

Why not? Railties works this way right?

I don't see how this can be a problem for a tool like `rackup`?

**Comment by jeremyevans** [comment]
> > IMO, we should not under any circumstances try to introspect installed gems and automatically load code from them.
> 
> Why not? Railties works this way right?

No idea how Railties works, and no desire to find out.

> I don't see how this can be a problem for a tool like `rackup`?

I don't see a problem with the current design.  At least you know what your going to get.  With your approach, you have no idea what's going to happen, since any gem installed on the system could potentially ship a handler.  At least we pretty much trust puma, falcon, and webrick.

**Comment by ioquatix** [comment]
> I don't see a problem with the current design. At least you know what your going to get. With your approach, you have no idea what's going to happen, since any gem installed on the system could potentially ship a handler. At least we pretty much trust puma, falcon, and webrick.

That's not how it works, it's limited to the gems in your gemfile.

**Comment by jeremyevans** [comment]
I suppose I am OK with the approach only if you are ensuring that a Gemfile has been loaded, because that is at least a weak form of opt-in.  However, if a Gemfile is not used, such an approach should not be used.

**Comment by ioquatix** [comment]
> However, if a Gemfile is not used, such an approach should not be used.

What are your concerns? Security?

**Comment by jeremyevans** [comment]
Security is one issue.  Another is I may want rackup to use puma even if I have another gem installed that ships a rack handler.  Which handler is chosen should be reliable/deterministic, as it currently is.

**Comment by boazsegev** [comment]
> That's not how it works, it's limited to the gems in your gemfile

Why should this not be a concern for the server's code ([i.e., adding a handler when the gem is loaded](https://github.com/boazsegev/iodine/blob/a6d61cc0b5f2aafe3c387974968be4faf33c799d/lib/rack/handler/iodine.rb#L29-L33))?

**Comment by ioquatix** [comment]
> Why should this not be a concern for the server's code (i.e., adding a handler when the gem is loaded)?

That's pretty much what I believe we should be doing.

**Comment by jeremyevans** [comment]
@ioquatix  Honestly, I don't understand why you would want to make major changes to rackup to implement lookup in gems if you don't think it's useful and don't think people should be using it.

@boazsegev I'm fine with an approach where servers register handlers, and rackup uses the first registered handler.  It could even fall back to the current default list, so as not to break existing code.  That's very different than looking in gems (which is what minitest does to find plugins).

**Comment by jeremyevans** [comment]
> > Why should this not be a concern for the server's code (i.e., adding a handler when the gem is loaded)?
> 
> That's pretty much what I believe we should be doing.

I'm fine with that approach (where something else loads the gem, and rackup itself isn't looking through installed gems).  When I said I don't think we should do what Minitest does, I'm specifically referring to this type of approach: https://github.com/seattlerb/minitest/blob/fe3992e85b40792cf7bff2a876887d8d9e392068/lib/minitest.rb#L102-L110

**Comment by ioquatix** [comment]
@jeremyevans RubyGems already provides this functionality using `Bundler.require` which we should **consider** using. The goal here is to make it easy for users to install gem "my_fancy_server" and then run `rackup` and have it just work.

**Comment by jeremyevans** [comment]
Again, if `require`/`Bundler.require` loads the gem, and the gem registers a handler, that's a fine approach for me.  It's the `Gem.find_files("rack/handler/*.rb")` approach that I want to avoid.

**Comment by boazsegev** [comment]
@ioquatix - just to clarify, my comment was meant to point out that IMHO the current `rackup` approach works.

**Comment by jeremyevans** [comment]
If other servers want to override `rackup`'s default handler, they can include this code:

```ruby
Rack::Handler.regster 'my_server', 'MyServer::RackHandler'
ENV['RACK_HANDLER'] ||= 'my_server'
```

So I don't think any changes are needed to rackup or the rack handler code.  Rack handlers can use custom options per handler to handle TLS and/or concurrency options if they need to.

@ioquatix would you be OK with closing this?

**Comment by ioquatix** [comment]
I'm not completely satisfied with how we are provisioning and using `rackup`, however I'll restate my case on a new issue.
