### ISSUE TITLE
Move `rack.hijack` to a separate extension SPEC file

### ISSUE THREAD

**Issue by boazsegev** [rack/rack#1602]
I suggest that we open a `SPEC-extensions` folder and move the `rack.hijack` into this folder.

This will keep current Rack behavior and is only a semantic change.

**Why**?

This change will clarify the fact that the `rack.hijack` is an optional feature / extension, unlike the core Rack specification. This will promote users to test for the extension rather than assume it is supported.

This will make it easier to discuss updates / changes / additions to both the `rack.hijack` extension and any possible future alternatives (see #1600). Though, I would suggest, that experimental / development extensions be placed in a fork rather than the master branch.

This change will allow semantic versioning to be added to optional Rack extensions. i.e., `rack.hijack?` could answer to `1.0.0`, allowing users to test for the version of the specification that is supported.

**Comment by ioquatix** [comment]
Something like this actually makes a lot of sense to me, at least if I don't think about it too much.

**Comment by ioquatix** [comment]
Rack 3.0 will ship with a non-optional streaming model based on partial `rack.hijack`. I suspect but don't know for certain that we will eventually deprecate and remove `rack.hijack`. My preference is focus on core functionality rather than introducing an extension model that causes fragmentation.
