### ISSUE TITLE
Best approach for potential performance enhancements?

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1608]
I've been playing around with a query parser implemented in C using Ragel. It's a little bit tricky to compile... but it does perform pretty well:

```
Trenni::Native
  #parse_query
Warming up --------------------------------------
      Large (Trenni)    25.498k i/100ms
        Large (Rack)     3.838k i/100ms
Calculating -------------------------------------
      Large (Trenni)    273.636k (± 1.3%) i/s -      1.377M in   5.032654s
        Large (Rack)     39.295k (± 1.7%) i/s -    199.576k in   5.080407s

Comparison:
      Large (Trenni):   273636.4 i/s
        Large (Rack):    39294.8 i/s - 6.96x  slower
```

Showing a potential ~7x speedup in my initial benchmarks. Bearing in mind the URL encoding is not handled the same way.

There are several areas of Rack which involve parsing which are almost always faster (and more robust) when using Ragel. Ragel can also generate pure Ruby parsers, although they are a little bit messy and usually slightly slower than hand rolled regular expressions.

Anyway, I wonder if we made a dedicated gem for these parsers, some how they could be an optional part of Rack...? I don't really want to make Rack any bigger, so maybe it's nice if we moved some of the query parsing stuff out into a separate gem, with optional C extensions for improved performance.

**Comment by ioquatix** [comment]
Just for reference, here is the parser: https://github.com/ioquatix/trenni/blob/master/parsers/trenni/query.rl

Here is how it's used: https://github.com/ioquatix/trenni/blob/master/spec/trenni/query_spec.rb

Here is the benchmark: https://github.com/ioquatix/trenni/blob/1975b3a5e56741c478e3d5551f8364ad9357b3bf/spec/trenni/parsers_performance_spec.rb#L78-L97

**Comment by ahorek** [comment]
nice, I would just prefer an FFI extension which is more portable

**Comment by ioquatix** [comment]
FFI extension is slower because delegate performance is important. This is a streaming parser.

**Comment by ahorek** [comment]
interesting, here's the benchmark result for calling a simple C function
```
ruby ext 7.150M i/s
ffi ext  3.460M i/s
         2 times slower
```

the difference will be probably lower with a real example that actually computes something. But you're right, the overhead is unfortunately significant.

in that case, an optional gem would be the best

**Comment by jeremyevans** [comment]
I agree, an optional ruby extension gem would be best for this.  FFI seems portable, and is portable in the sense of CRuby/JRuby portable, but how portable it actually is to more niche operating systems depends on what code you are using and what assumptions you are making about types.

**Comment by jeremyevans** [comment]
I'm going to close this as I don't think we'll be making changes to rack itself to include the C extension.  I do look forward to seeing trenni or another external gem as a way to speed up the query parser.
