### ISSUE TITLE
Fails to build from source with unhelpful error if machine has low memory

### ISSUE THREAD

**Issue by utkarsh2102** [rack/rack#1623]
Hi there,

The following bug was reported against this library:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836543

Any idea how to go about it? Or what's the fix?

**Comment by jeremyevans** [comment]
First, this isn't a build error, it is an error when running the tests.  The tests may require more RAM, though 768MB seems a bit much.  On my OpenBSD machine, the tests run in under 128MB of memory.  Here's the `/usr/bin/time -l rake` output:

```
       11.57 real         6.97 user         1.23 sys
    113816  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    156536  minor page faults
         0  major page faults
         0  swaps
         9  block input operations
      1721  block output operations
        51  messages sent
        57  messages received
         6  signals received
      1522  voluntary context switches
        39  involuntary context switches
``` 

The `113816  maximum resident set size` indicates about 111MB of physical memory used.  If I use `ulimit -d 100000`, then i get test failures with `NoMemoryError`.

I think the simplest work around in this case is to not run the tests when building.

This could be a local issue. Can anyone else recreate this excessive memory usage?

**Comment by jeremyevans** [comment]
Closing as this doesn't appear to be a bug in rack.
