### ISSUE TITLE
How do you implement SameSite attribute for cookies in rails?

### ISSUE THREAD

**Issue by blackwellsmith** [rack/rack#1627]
Ok so I have searched and searched. May explanations on what is happening with SameSite. I can't find anything that shows me how or where to do that. It's like I am completely missing something. Can someone share some insight on how to set this attribute in Rails? Thanks!

**Comment by jeremyevans** [comment]
You probably want to ask on a Rails-specific help forum, since it is a Rails question.  In terms of the rack-specific API, you would use the `:same_site` option to `Rack::Utils#add_cookie_to_header`.
