### ISSUE TITLE
"response_body = Enumerator" streaming broken after taking off #each

### ISSUE THREAD

**Issue by lisbethw1130** [rack/rack#1628]
When upgrading Rack from 2.1.2 to 2.2.0, this commit #06d23735ca8ea82ec1a6abdb1cb9158454a00eb0 seems to break the streaming function.
Following is a simple rails controller

```
  def export
    filename = "orders-export-#{Time.now.to_formatted_s(:number)}"

    respond_to do |format|
      format.xls do
        set_streaming_header('application/vnd.ms-excel', "#{filename}.xls")
        self.response_body = Enumerator.new do |xls_row|
            5.times.each do
                xls_row << 123123
            end
        end
      end
  end

  def set_streaming_header(content_type, filename)
    headers.delete('Content-Length')
    headers['Cache-Control']       = 'no-cache'
    headers['Content-Type']        = content_type
    headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
    headers['X-Accel-Buffering']   = 'no'
  end
```

What happened now: will start sending packet after everything is rendered\
What we expected: will start sending packet after response_body being called with enumerator

Also, I have trace back compare with two different version

Rack 2.1.2
```
app/services/export.rb:21:in `block in export_xls'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:149:in `each'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:149:in `each'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:149:in `each'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:149:in `each_chunk'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:130:in `each'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:76:in `each'
gems/actionpack-6.0.0.rc2/lib/action_dispatch/http/response.rb:489:in `each'
gems/rack-2.1.2/lib/rack/body_proxy.rb:34:in `each'
gems/rack-2.1.2/lib/rack/body_proxy.rb:34:in `each'
gems/rack-2.1.2/lib/rack/body_proxy.rb:34:in `each'
gems/rack-2.1.2/lib/rack/body_proxy.rb:34:in `each'
gems/rack-2.1.2/lib/rack/body_proxy.rb:34:in `each'
gems/puma-3.12.1/lib/puma/server.rb:793:in `handle_request'
gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Rack 2.2.0
```
app/services/export.rb:21:in `block in export_xls'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:149:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:149:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:149:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:149:in `each_chunk'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:130:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:76:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/http/response.rb:489:in `each'
rack (2.2.2) lib/rack/body_proxy.rb:41:in `method_missing'
rack (2.2.2) lib/rack/etag.rb:67:in `digest_body'
rack (2.2.2) lib/rack/etag.rb:31:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call' 
```

as you can see that the #each method in body_proxy which rely on streaming was missing.

Is there another way to streaming text (such as csv or xml) without relying on #each in body_proxy? or whether this method should re-added?

Thanks for the help

**Comment by jeremyevans** [comment]
The commit you mentioned removes `BodyProxy#each`, but the resulting `#method_missing` code does the exact same thing (no behavior change).  From the backtrace you provided, you see that the same upstream each method is called in both places.  

Looking at the backtrace, in Rack 2.2, you have a bunch of middleware that I don't see in Rack 2.1.   In the Rack 2.2 backtrace, looks like the ETag middleware is causing the issue.  If you load the ETag middleware in the Rack 2.1 code, do you get the same behavior?  Alternatively, if you drop the ETag middleware in Rack 2.2, does that fix the issue?  It does make sense that the ETag middleware would eagerly load the body in order to calculate the ETag, that doesn't seem like a bug to me.

**Comment by lisbethw1130** [comment]
I tried to run in rack 2.2 with each method back, and the problem still happened, so yeah, I think I am going to dig into the etag middleware
thanks @jeremyevans , I will update here if anything found

**Comment by lisbethw1130** [comment]
Hey, the root cause is as same as https://github.com/rack/rack/issues/1619
I add `headers['Last-Modified'] = '0'` and it skip etag middleware to reconstruct body, and works!

I will close issue, thanks for everyone ;)

**Comment by ioquatix** [comment]
`Rack::ETag` is basically causing a ton of problems for streaming. Because it doesn't know that the body might be streaming/real time.
