### ISSUE TITLE
Rack::Mock#parse_cookies_from_header does not follow SPEC

### ISSUE THREAD

**Issue by mpalmer** [rack/rack#1629]
From SPEC:

> The header must respond to each, and yield values of key and value.

However, [Rack::Mock#parse_cookies_from_header](https://github.com/rack/rack/blob/master/lib/rack/mock.rb#L234) calls `has_key?` on the headers.  As such, this breaks any Rack application which takes the spec at its word, and provides another object which responds to `each` and yields values of key and value (such as, for instance, an array of two-element arrays representing header names and values).

**Comment by ioquatix** [comment]
It should use `Rack::Utils::HeaderHash` probably.

**Comment by ioquatix** [comment]
@mpalmer do you want to submit a PR? Try wrapping the headers in `Rack::Utils::HeaderHash[headers]`.

**Comment by mpalmer** [comment]
Yes, I can whip up a PR.  I was thinking of just iterating the `original_headers` looking for the `cookie` ones; that seems like it'd be less overhead than converting to a `HeaderHash` just to pluck one (known) key out.  Since it's for tests, though, I'm assuming that any difference would be negligible.

**Comment by mpalmer** [comment]
A wild PR appears!  It strikes!

**Comment by ioquatix** [comment]
HeaderHash is memoized can you please check if in the typical case it can be almost a no-op.

**Comment by mpalmer** [comment]
If I'm understanding you correctly, then yes, if what gets passed into the `MockResponse` is already a `HeaderHash`, then there's no overhead of re-parsing, so it should be practically a no-op.  My PR uses `HeaderHash[]`, so it will benefit from this.

**Comment by ioquatix** [comment]
Sorry, was putting kids to bed, that makes sense!
