### ISSUE TITLE
chore: Remove unused CircleCI integration

### ISSUE THREAD

**Issue by olleolleolle** [rack/rack#1633]
When opening a PR, a quick-but-wrong CircleCI build result presents itself.

Current:

- configuration file has been removed
- all is migrated to GitHub Actions
- all CircleCI builds fail

Proposed:

- remove the CircleCI integration

**Comment by jeremyevans** [comment]
I agree with the proposal.  Unfortunately, I don't think I have the necessary permissions to do this.

**Comment by tenderlove** [comment]
I will pull it!

**Comment by tenderlove** [comment]
Should be removed.  LMK if it's still building and I'll take a closer look
