### ISSUE TITLE
Echo'ing path

### ISSUE THREAD

**Issue by Lewiscowles1986** [rack/rack#1634]
I deployed someone else application to https://ca3db-lcowles-test.herokuapp.com/, source https://github.com/Lewiscowles1986/ca3db-ruby/tree/heroku and it seems to be echo'ing 404 URL paths to the browser. Is there a way to turn this off?

**Comment by jeremyevans** [comment]
I'm not sure.  It looks like the application you are using is a Sinatra application.  Is there a reason you think that rack is causing the issue you are experiencing?  If so, can you put together a minimal self contained example showing the problem as in inline config.ru file?

**Comment by Lewiscowles1986** [comment]
To be honest, I'd assumed this as https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L328-L337 doesn't seem to output the body anywhere. I'll try to reproduce, but one of the reasons I raised the ticket is because I have no idea where it's coming from

**Comment by Lewiscowles1986** [comment]
Found it, your right and apologies. It is in sinatra one level up in the route_missing handler

```
rackup -s puma -o 0.0.0.0 -p 8080 -E production -d
```

showed me which file line was creating the response

```
Exception `Sinatra::NotFound' at /home/lewis/.rvm/gems/ruby-2.6.3@ca3db/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1054 - GET /
127.0.0.1 - - [04/Apr/2020:00:36:35 +0100] "GET /?page=1 HTTP/1.1" 404 5 0.0406
```
