### ISSUE TITLE
Old file in gem

### ISSUE THREAD

**Issue by Alexwell** [rack/rack#1637]
Hello, there is an old version of the `rack/lib/rack/session/cookie.rb` without `require 'delegate'` in current gem version.
Last version of this file in github repository contain this require https://github.com/rack/rack/blob/f9ad97fd69a6b3616d0a99e6bedcfb9de2f81f6c/lib/rack/session/cookie.rb#L8 

But in last version of gem it missing https://rubygems.org/gems/rack/versions/2.2.2
```
require 'openssl'
require 'zlib'
require_relative 'abstract/id'
require 'json'
require 'base64'

```
Please, check source code of gem.

**Comment by ioquatix** [comment]
I think this will be fixed in the next release, apologies if it cause you any problems. Thanks for reporting the issue.
