### ISSUE TITLE
Parsing options from the first comment line is deprecated!

### ISSUE THREAD

**Issue by qortex** [rack/rack#1639]
What is the suggested alternative?

I want to specify an option server in my config file (`--quiet` in my case) and don't want to type it each time I do `rackup` as in `rackup --quiet`.

Putting the option in my `config.ru` was nice. What is the better alternative?

**Comment by jeremyevans** [comment]
Currently there is not an alternative.  Other than being very ugly, the deprecated option parsing also ties the `config.ru` file to a specific server implementation, when the ideal is to have a `config.ru` file that works with all rack webservers.

If we were going to add it back, maybe we could use something like:

```ruby
# in config.ru
server_options '--quiet'
```

That would fix the ugliness, but would still result in a `config.ru` file tied to a specific webserver implementation.  I'm not in favor, but let's see what other people think.

**Comment by qortex** [comment]
Ah yes I see the point.

Although here, I'm doing that just to control the [default middlewares injected](https://github.com/rack/rack/blob/f9ad97fd69a6b3616d0a99e6bedcfb9de2f81f6c/lib/rack/server.rb#L253).

So I guess it's not too dependant on the specific servers, what do you think?

For now, I mimic'ed my own `rackup` start script with inspiration from `server.rb`:
```ruby
require 'rack'
environment = ENV['RACK_ENV'] || 'development'
default_host = environment == 'development' ? 'localhost' : '0.0.0.0'

# Standard default options
options = {
  environment: environment,
  pid: nil,
  Port: 9292,
  Host: default_host,
  AccessLog: [],
  config: 'config.ru'
}

# Adding my option
options[:quiet] = true

Rack::Server.start(options)
```

**Comment by jeremyevans** [comment]
Your code is specific to `Rack::Server`.  My point was `config.ru` files are often processed by webservers directly (e.g. unicorn), without using `Rack::Server`, and those servers may use different command line options.

**Comment by qortex** [comment]
Ah ok thanks for the explanation.
I'm indeed not very clear on this matter since Puma is automagically started since it is installed. Will have to dig to find how all of this is hooked up together. But it's outside the scope of this issue :)

I might just close it since it's desired behaviour.

**Comment by qortex** [comment]
**Follow-up**: Ah ok got it, it's done through `handler.rb` where servers are tried by chance and first one being installed is started.

So yes, being specific to rack server, maybe adding a config file such as `.rack-server` could be an idea to decouple from `config.ru`.

**Comment by ioquatix** [comment]
Puma already has it's own configuration file.

**Comment by qortex** [comment]
Yeah right. Just entering the ecosystem, I got the terminology mixed up because:
Rack **server** launched through `rackup` actually starts an HTTP **server**, that it calls **Handler**. It chooses the **handler** just by looking at the first one installed in a pre-defined list.

The **rackup** config is passed down to the real **server** (or **handler** that is) after injecting a few middlewares.

This automagic got me confused although it's perfectly logic once you get the moving parts.

Here is a deprecation message that would have helped me to figure this out on my own:

> Parsing options to rackup from the first comment line in rack config file is deprecated since this file should remain independent from the webserver you use. If you want to use rackup to boot your webserver, please use the `Rack::Server.start` entry point and pass your options. If you want to use a specific webserver (puma, unicorn, ...), pass the options directly in their config file.
