### ISSUE TITLE
test failure on HP-PARISC: Rack::Utils#test_0013_raise an exception if the params are too deep:

### ISSUE THREAD

**Issue by DerDakon** [rack/rack#1640]
Test output:

```
Error:
Rack::Utils#test_0013_raise an exception if the params are too deep:
SystemStackError: stack level too deep
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `each'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `to_h'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:205:in `block in to_h'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `each'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `to_h'
[…]
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:205:in `block in to_h'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `each'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:199:in `to_h'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/query_parser.rb:76:in `parse_nested_query'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/lib/rack/utils.rb:103:in `parse_nested_query'
    /var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/test/spec_utils.rb:129:in `block (2 levels) in <top (required)>'


rails test var/tmp/portage/dev-ruby/rack-2.1.1/work/ruby25/rack-2.1.1/test/spec_utils.rb:122
```

Common pitfall: the stack on HPPA machines grows _upwards_. This one is Gentoo Linux

**Comment by leahneukirchen** [comment]
Apparently the stack on HPPA is not enough to do 100 recursion levels.

1) Perhaps something like 16 is a better default?
2) QueryParser#parse_nested_query should catch SystemStackError

**Comment by DerDakon** [comment]
The size is not unusual, I never had problems with it. Usually it's the direction that causes issues as getting the bottom of the stack is constant and always returns the _first_ address of the stack, but not the current one.

**Comment by leahneukirchen** [comment]
Well, the stack order is a Ruby issue, not a Rack problem.
Which version of Ruby is that?

I don't see benefit in allowing 100 times nested query parameters.

Can you run `ruby -e 'def r(n); p n; r(n+1); end; r 1'` and show how big it gets?
Does it get more when you `export RUBY_THREAD_VM_STACK_SIZE=1000000`?

The output of `ulimit -s` would be interesting too.

**Comment by DerDakon** [comment]
Without: 11911
With: 22803
ulimit -s: 8192

**Comment by leahneukirchen** [comment]
Weird, here on x86_64 I get 10918 but it runs that test fine.

**Comment by mikegee** [comment]
@DerDakon did you elide many lines of duplicated output with `[…]` in the original post here, or did ruby do that? If you did, how many lines where there? (around 100 or over 10,000)

**Comment by DerDakon** [comment]
The first 'each' is in line 41, the 'parse_nested_query' is in line 166 of the log.

**Comment by jeremyevans** [comment]
This should be easy to work around on HA-PARISC by setting:

```ruby
Rack::Utils.default_query_parser = QueryParser.make_default(65536, 16)
```

While I agree that 16 levels "ought to be enough for anybody", I guess we should consider cases larger than that.  Maybe 32 levels?  I'll submit a PR for that.
