### ISSUE TITLE
digest_body() fails on a [nil] response

### ISSUE THREAD

**Issue by effleurager** [rack/rack#1647]
When calculating the ETag for a `[nil]` response, [`digest_body([nil])`](https://github.com/rack/rack/blob/145a0c5f41ce1fef18edc9807701655ddd717c06/lib/rack/etag.rb#L64) will fail as the parts of a body are assumed to be non-`nil`.

**Comment by jeremyevans** [comment]
`[nil]` is an invalid response body.  Rack SPEC requires the response body respond to `each` and yield only strings, and `nil` is not a string.  So this isn't a bug.  I don't think we should make changes to middleware that ship with Rack to handle invalid response bodies.
