### ISSUE TITLE
Rack::MockResponse abuses Rack::Utils::HeaderHash by using fetch

### ISSUE THREAD

**Issue by kwerle** [rack/rack#1650]
MockResponse has the lines
```
      if original_headers.has_key? 'Set-Cookie'
        set_cookie_header = original_headers.fetch('Set-Cookie')
```

original_headers is a HeaderHash.  HeaderHash is private; internally it claims to be case insensitive - and it mostly is.  However, its fetch method is not.

The following test will fail:
```
describe Rack::Utils::HeaderHash do
  it 'fetches case insensitively' do
    h = Rack::Utils::HeaderHash.new("ETag" => "Boo!")
    h.fetch('ETag').must_equal 'Boo!'
    h.fetch('Etag').must_equal 'Boo!' # KeyError: key not found: "Etag" - sad panda
  end
```

Changing the upper line to `original_headers['Set-Cookie']` resolves the issue.  And you've already established that Set-Cookie exists as a key (though in my case it's 'set-cookie' - which is why I'm here).  So you really don't need to use .fetch to blow it up if it's missing.

I'm happy to submit a PR for a change - but I'm not sure what to fool with.  HeaderHash is kind of lying about being case insensitive, but it's private.

**Comment by kwerle** [comment]
Hmm.  I guess this probably relates to #1592

**Comment by ioquatix** [comment]
Can we just replace it with:

```ruby
set_cookie_header = original_headers['set-cookie']
```

?

**Comment by kwerle** [comment]
Yes, any capitalization of `original_headers['Set-Cookie']` would do the trick.

**Comment by ioquatix** [comment]
We should consider adding a fast path for normalised (lower case) headers.

**Comment by jeremyevans** [comment]
`HeaderHash#fetch` was made case insensitive in #1670, so I think this can be closed.
