### ISSUE TITLE
Form data parsing empty array

### ISSUE THREAD

**Issue by joaquinco** [rack/rack#1651]
I'm trying to submit an empty array to a rails application (rails 5.2.3, rack 2.0.9), and I'm getting an array with an empty string in params. The form is built with javascript usign `FormData()` and it's sent as multipart.

Is this the expected behavior?

As an example, to be clear:
I'm sending tags from the web app: `a = new FormData(); a.append('tags[]', '')` and getting `Parameters: { "tags" => [""] }` in the controller

**Comment by jeremyevans** [comment]
Yes, this is the expected behavior.  `?tags[]=a` results in `['a']`, and `?tags[]=` results in `['']`.  You cannot submit an empty array or an empty hash using Rack's parameter parsing as far as I know.
