### ISSUE TITLE
Proxy all (or at least more) methods on Rack::RewindableInput?

### ISSUE THREAD

**Issue by doriantaylor** [rack/rack#1668]
Running up to an issue with `Rack::RewindableInput` where I have a construct that looks like:

```ruby
    content = case content
              when nil          then self.content
              when IO, StringIO then content
              when String       then StringIO.new content
              when Pathname     then content.open('rb')
              when Proc         then content.call
              when -> x { %i[read seek pos].all? { |m| x.respond_to? m } }
                content
              else
                raise ArgumentError,
                  "Cannot scan content of type #{content.class}"
              end
```
What this thing does is effectively coalesce the input into an `IO`-like object (or at least something that quacks like one). Problem is `Rack::RewindableInput` does not implement `seek` or `pos`/`tell` despite the proxied `Tempfile` class implementing them, nor does it inherit `IO` (although neither does `Tempfile` apparently). As such, I found myself writing the following monkeypatch:

```ruby
# Rack::RewindableInput doesn't provide the full complement of methods
# of the object it proxies
class Rack::RewindableInput

  # not sure if this is a good idea or a terrible one
  def respond_to? sym
    # of course we can't query the proxy object until we bootstrap it
    make_rewindable unless @rewindable_io
    @rewindable_io.respond_to?(sym) || super(sym)
  end

  # make sure we don't redefine method_missing if it already exists
  unless self.instance_methods.include? :method_missing
    def method_missing which, *args
      # do this now
      make_rewindable unless @rewindable_io

      # toss if the proxy object doesn't respond (& mimic original error)
      raise NoMethodError,
        "undefined method #{which} for #{self.inspect}:#{self.class}" unless
        @rewindable_io.respond_to? which

      # inline the method so this doesn't get called again
      self.class.define_method which do |*args|
        # do it here too for parity
        make_rewindable unless @rewindable_io
        @rewindable_io.__send__(which, *args)
      end

      # don't forget to actually invoke it this time around too
      @rewindable_io.__send__(which, *args)
    end
  end
end
```
I can't tell if this is a great idea or a terrible one, but it seems like `Rack::RewindableInput` could use the full complement of methods available to its proxy object so it can at least be duck-typed.

Thoughts?

**Comment by ioquatix** [comment]
RewindableInput will be getting removed. Does that impact your proposal?

**Comment by doriantaylor** [comment]
I'm not committed to it, as long as I can have a seekable IO-looking thing for request bodies when running under FastCGI. What's it being replaced with?

**Comment by ioquatix** [comment]
We have removed FastCGI from the Rack core (however we could consider reintroducing it as a gem, e.g `rack-fcgi`). Can you explain why you are still using fcgi?

The replacement is streaming input but it's not seekable. If you want seekable input you will need to implement your own buffer either on disk or in memory.

**Comment by doriantaylor** [comment]
FastCGI as opposed to just a straight reverse proxy? Can't remember; there are probably "reasons". Should one just assume that request content would not be seekable across the board? (I mean, of course it isn't if it is coming off the wire, but the general pattern of slurping request content into a temp file…)

**Comment by jeremyevans** [comment]
If we are removing RewindableInput, then it doesn't make sense to try to improve it.  I see that not requiring rewindable input is discussed in #1148.   However, in that discussion it seems like rewindable input would go from a spec requirement to being an optional middleware, in which case we would probably still ship RewindableInput in Rack 3, with a middleware that uses it.

Supporting `seek` restricts RewindableInput's implementation.  It would work with the current implementation but could make future changes more difficult.  For example, let's say we changed the implementation such that `each` returned data without creating a tempfile, but retained a copy of each yielded string in an array in memory.  Then if rewind is called, it iterates over the array until the end of the array, at which point it starts reading again from the input stream.  This is a rewindable approach that is not directly seekable.

Once rewindable input is no longer required by the spec, it might be best to implement this as a separate SeekableInput with middleware.

**Comment by doriantaylor** [comment]
I like the idea of a middleware for seekable input.

**Comment by ioquatix** [comment]
We will be removing `rewind` from `rack.input` in the spec.
