### ISSUE TITLE
Check HTTP_X_FORWARDED_FOR first instead of REMOTE_ADDR

### ISSUE THREAD

**Issue by krim** [rack/rack#1669]
According to the https://github.com/rack/rack/commit/250cde152b186e43dde264cf16808abfd459d394 (the first commit when the behavior was changed).
There was a comment from [fredv](https://github.com/rack/rack/commit/250cde152b186e43dde264cf16808abfd459d394#commitcomment-1457043).
> Is this going to be changed again, or not - or is there another active discussion on this? Has using the HTTP_X_FORWARDED_FOR header for forwarding the client ip at the proxy major disadvantages? Letting the proxy overwrite REMOTE_ADDR seems to me a lot messier.

> For the last years we've always been using HTTP_X_FORWARDED_FOR in a nginx + passenger/unicorn setup with hardware lbs as well as haproxy.

When you have a proxy(e.g. Nginx) and a ruby server in the backend you have always add a client ip to `HTTP_X_FORWARDED_FOR` header.

So, take a look:
1. A client makes a request.
2. Nginx handles it and adds header `HTTP_X_FORWARDED_FOR` with the client IP.
3. Nginx proxy request to ruby server upstream(e.g. unicorn).
4. Unicorn adds `REMOTE_ADDR` header [here](https://github.com/defunkt/unicorn/blob/080bbe7a14bdb0373eaf25384003e51eec6ab748/lib/unicorn/http_request.rb#L75). It's not the client IP, it's IP from the Nginx server.
5. [Here](https://github.com/rack/rack/blame/master/lib/rack/request.rb#L354-L375) is the ip method where we check `REMOTE_ADDR` first and we return one if it's trusted.
In this part, we can't set `trusted_ips` because it can be dynamic, e.g. in Amazon, digital ocean, hetzner etc. We can add/remove virtual machines with different IPs.

That's why I have a question: 
Why we should check `REMOTE_ADDR` first instead of `HTTP_X_FORWARDED_FOR`? 
It's much better to check `HTTP_X_FORWARDED_FOR` and if it's blank we should check `REMOTE_ADDR`.

Here is the hack which I can use in my rails app to fix the problem to get the client ip:
```ruby
class FixRemoteAddrMiddleware
  HTTP_X_FORWARDED_FOR = 'HTTP_X_FORWARDED_FOR'
  REMOTE_ADDR = 'REMOTE_ADDR'

  def initialize(app)
    @app = app
  end

  # The forwarded for addresses are ordered: client, proxy1, proxy2.
  def call(env)
    env[REMOTE_ADDR] = env[HTTP_X_FORWARDED_FOR].split(',').first if x_forwarded_for_exist?(env)

    @app.call(env)
  end

  private

  def x_forwarded_for_exist?(env)
    env[HTTP_X_FORWARDED_FOR]&.is_a?(String)
  end
end
```

**Comment by jeremyevans** [comment]
`HTTP_X_FORWARDED_FOR` is trivially forged, `REMOTE_ADDR` is not.  I'm assuming you can fix your issue by setting `Rack::Request.ip_filter = lambda{ true_if_nginx_ip_false_if_not }`.  Is there a reason that would not work for your use case?

**Comment by krim** [comment]
@jeremyevans thanks for your reply

> I'm assuming you can fix your issue by setting Rack::Request.ip_filter = lambda{ true_if_nginx_ip_false_if_not }

It's impossible when you buy/sell your Nginx servers. So it doesn't work when you don't have a static list of your Nginx's IPs.

**Comment by jeremyevans** [comment]
`Rack::Request.ip_filter` doesn't need to be a static list.  It's a proc, and can be a dynamic lookup of your current Nginx IPs.  I assume you must at least have a dynamic whitelist setup, as otherwise people would be able to send requests directly to your Unicorn servers without going through Nginx, which would be a denial of service vulnerability.  So asking again, Is there a reason that would not work for your use case?

**Comment by krim** [comment]
>  I assume you must at least have a dynamic whitelist setup, as otherwise people would be able to send requests directly to your Unicorn servers without going through Nginx, which would be a denial of service vulnerability.

No, they can't.
There are several simple rules to resolve it:
- when you have firewall rules to accept requests only from your balancers
- when you have a private network and have a [consul](https://www.consul.io/) to register your app-servers which can be used by your balancers(with consul-template)

> So asking again, Is there a reason that would not work for your use case?

It's very hard to set `trusted_ips`. When you have `Nginx + passenger/unicorn` you will always have to change the `trusted_ips` list in your backend app when you add a new Nginx server. Or get the IP list from the consul, or somewhere else, and restart the app(or get the list for each request). But it's overengineering.

Look at to the comment from [fredv](https://github.com/rack/rack/commit/250cde152b186e43dde264cf16808abfd459d394#commitcomment-1457043)

**Comment by jeremyevans** [comment]
> > I assume you must at least have a dynamic whitelist setup, as otherwise people would be able to send requests directly to your Unicorn servers without going through Nginx, which would be a denial of service vulnerability.
> 
> No, they can't.
> There are several simple rules to resolve it:
> 
> * when you have firewall rules to accept requests only from your balancers

The firewall rules must then know who the balancers are, and that could be exposed to the backend.

> * when you have a private network and have a [consul](https://www.consul.io/) to register your app-servers which can be used by your balancers(with consul-template)

If this is a private network, the issue should be easily solved by having the balancers in one IP address range that is trusted.

> > So asking again, Is there a reason that would not work for your use case?
> 
> It's very hard to set `trusted_ips`. When you have `Nginx + passenger/unicorn` you will always have to change the `trusted_ips` list in your backend app when you add a new Nginx server.

There is no `trusted_ips` list, it's a proc, it can be a dynamic lookup at runtime, it does not need to be a static setting.

> Or get the IP list from the consul, or somewhere else, and restart the app(or get the list for each request). But it's overengineering.

Again, it's not a list, it is a proc, and you don't need to restart the app to update it.  You could use redis or another database to hold the trusted ips, and have the proc look for an entry in the database.

> Look at to the comment from [fredv](https://github.com/rack/rack/commit/250cde152b186e43dde264cf16808abfd459d394#commitcomment-1457043)

I looked at the comment and I'm not sure it adds any new information to this discussion.  The fact remains that `trusted_ips`  is not a static list, it is a proc so the lookup can be dynamic.  You still haven't provided an example of why a dynamic trusted ip lookup cannot work for your use case.

**Comment by krim** [comment]
> There is no trusted_ips list, it's a proc, it can be a dynamic lookup at runtime, it does not need to be a static setting.

I totally understand. I wrote about it here:
> Or get the IP list from the consul, or somewhere else, and restart the app(or get the list for each request). But it's overengineering.

It's not a good idea to set up a list of IPs.
I prefer the initial logic which was in the rack before.
