### ISSUE TITLE
session not working with rack 2.2.3 

### ISSUE THREAD

**Issue by seb-sykio** [rack/rack#1682]
hi,
no pb with 2.2.2, but if I update to 2.2.3, session are not working anymore.
devise successfully log in the user, then redirect him, but then it is not authorized to access page
if I go back to rack 2.2.2, then it works correctly

```
Started POST "/fr/connexion" for 127.0.0.1 at 2020-07-11 19:56:50 +0200
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"VdSdJskxgy9ySTUrjIPiTKJG4cvO+sMus2Iem21IcsJdRzuPFZeRb3rX2wpflEdaUQ5QLpsPoUQa/KXanUuKHQ==", "user"=>{"email"=>"xxx@ccc.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "button"=>"", "locale"=>"fr"}
  User Load (11.4ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "xxx@ccc.com"], ["LIMIT", 1]]
   (0.3ms)  BEGIN
  User Update (2.1ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2020-07-11 17:56:50.386072"], ["last_sign_in_at", "2020-07-01 11:36:16.139109"], ["sign_in_count", 86], ["updated_at", "2020-07-11 17:56:50.386478"], ["id", 308156]]
   (2.3ms)  COMMIT
Redirected to http://0.0.0.0:3000/fr
Completed 302 Found in 112ms (ActiveRecord: 20.5ms | Allocations: 11592)


Started GET "/fr" for 127.0.0.1 at 2020-07-11 19:56:50 +0200
Processing by AdsController#index as HTML
  Parameters: {"locale"=>"fr"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Allocations: 544)
```

tested with
ruby 2.7.1 and 2.6.6
rails 6.0.3.2
devise 4.7.2

**Comment by jeremyevans** [comment]
This seems similar to #1674. Are you using cookies with names that need URL escaping?

**Comment by seb-sykio** [comment]
thanks for your answer
not sure to understand what u mean
every url might need escaping, but no, there is no space in our url
and cookies for session are managed by devise gem

we are using 'route_translator' gem, and this gem might escape url. Can it be linked ?

**Comment by jeremyevans** [comment]
It sounds like this could be related to the use of the `route_translator` gem. The security fix in rack 2.2.3 may require application/library changes if cookie names/keys that need URL escaping are used.  Previously, rack would URL decode cookie keys and values, but for security, starting in 2.2.3, rack only decodes cookie values (not cookie keys).  See https://hackerone.com/reports/895727 for more details on why the security change was made.

If you still think this is a bug in rack, please post a minimal self contained reproducible example (no external libraries) showing the issue that works with 2.2.2 and fails in 2.2.3.

**Comment by bishosilwal** [comment]
I had a similar problem after updating to rack 2.2.3 and I solved it by clearing old cookie from the browser.

**Comment by seb-sykio** [comment]
for me , all me tests that need session don't work anymore, so clearing cookies can't help

**Comment by seb-sykio** [comment]
I asked on route-translator gem issues and the answer was :
"Route Translator does not use cookies.
I took a brief look at rack/rack@5ccca47 and it is not clear to me how that change could affect route_translator"

all cookies are working correctly on my site, except session's.

the cookie name for session is of this kind : _Hf5%23%3F%21cs-sd67Ddf

is it because of "%23%3F%21" that I have issues ? this is generated by devise, right ?
thanks a lot for your help

**Comment by jeremyevans** [comment]
I'm not sure whether the cookie name is generated by devise or not, but it is expected that accessing that cookie name using the decoded value will break with the 2.2.3 security fix.  Your best fix is using a cookie name that doesn't require escaping.

**Comment by seb-sykio** [comment]
thanks. I forgot to check session_store initializer.
