### ISSUE TITLE
Hi admin

### ISSUE THREAD

**Issue by callsSolve** [rack/rack#1700]
I keep on getting this _response _ And I don't really know how to solve it!:

Rails is not currently installed on this system. To get the latest version, simply type:

  // * $ sudo gem install rails*//

//*You can then rerun your "rails" command.*//
 //* $ sudo gem install rails*//
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
Sorry, try again.
sudo: 3 incorrect password attempts

**Comment by jeremyevans** [comment]
I'm sorry, but this is unrelated to the rack library.  It's unrelated to Rails or Ruby, even.  If you don't know your password, or your sudo configuration does not allow you to use it, you probably need to talk to your system administrator.
