### ISSUE TITLE
Move Thin handler test into Thin?

### ISSUE THREAD

**Issue by voxik** [rack/rack#1714]
The Thin dependency was removed by 98d9cf5834d4e27e34bbaa017cdfc68795763b55 and moved to [Thin](https://github.com/macournoyer/thin/commit/b201525f0db7d7e9faf26681b68646e0be9f96ec). Shouldn't the tests, i.e. the `test/spec_thin.rb` follow the suite? I don't think the test are executed anyway, because nothing pulls Thin in since 20d248e9ad32515bb4f12f4f7211a6c89441b93f.

**Comment by jeremyevans** [comment]
I agree.  @ioquatix, do you see a reason to keep the spec?

**Comment by ioquatix** [comment]
It can be removed.
