### ISSUE TITLE
Issue with rack response

### ISSUE THREAD

**Issue by suryaiscrazy** [rack/rack#1717]
Hi Maintainers,

I am seeing an issue with rack response on the latest version. It is breaking rack-protection gem at this line : https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/xss_header.rb#L18

rack version 2.0.7 used to do this:

> status, headers, body = Rack::Response.new("x")
=> #<Rack::Response:0x00007fbde63652f8
 @block=nil,
 @body=["x"],
 @header={"Content-Length"=>"1"},
 @length=1,
 @status=200,
 @writer=#<Proc:0x00007fbde6365118@/Users/ss/.rvm/gems/ruby-2.5.1/gems/rack-2.0.7/lib/rack/response.rb:32 (lambda)>>

> [status, headers]
=> [200, {"Content-Length"=>"1"}]

rack version 2.2.3 though, when I do the same exact thing, does:

> status, headers, body = Rack::Response.new("x")
=> #<Rack::Response:0x00007fc59a2a5258
 @block=nil,
 @body=["x"],
 @buffered=true,
 @headers={},
 @length=1,
 @status=200,
 @writer=#<Method: Rack::Response(Rack::Response::Helpers)#append>>

> [status, headers]
=> [#<Rack::Response:0x00007fc59a2a5258
  @block=nil,
  @body=["x"],
  @buffered=true,
  @headers={},
  @length=1,
  @status=200,
  @writer=#<Method: Rack::Response(Rack::Response::Helpers)#append>>,
 nil]

As you can see the header and status are not getting set as they used to. Can someone take a look and tell me if this is an issue or not. If it is then what is a remedy.

**Comment by jeremyevans** [comment]
`Rack::Response` no longer sets the `Content-Length` header.  This is an expected change in 8c62821f4a464858a6b6ca3c3966ec308d2bb53e.  

The other issue you are running into is that `Rack::Response` no longer defines `to_ary`.  You need to manually call `finish` to get the rack response array.

```ruby
status, headers, body = Rack::Response.new("x", 200, "Content-Length"=>1).finish
# => [200, {"Content-Length"=>1}, ["x"]]
```

**Comment by suryaiscrazy** [comment]
ok, thank you @jeremyevans
