### ISSUE TITLE
No tag for release 2.2.3

### ISSUE THREAD

**Issue by eregon** [rack/rack#1721]
Yet the gem is available.
Could you add the tag?

**Comment by ioquatix** [comment]
That's odd. I'll take a look what's going on.

**Comment by ioquatix** [comment]
@tenderlove you made this release I believe?

The branch is https://github.com/rack/rack/commits/2-2-stable

Should we add a tag to the commit?

**Comment by ioquatix** [comment]
Oh, I just went looking for it, and it seems it is: https://github.com/rack/rack/releases/tag/2.2.3

@eregon what exactly are you missing?

**Comment by eregon** [comment]
You're right, it's there now at least. Sorry for the noise.
The order is strange on GitHub, that's probably why I missed it (also there is a `test` tag, intended?):
![rack_rack_ A modular Ruby web server interface  and 28 more pages - Personal - Microsoft​ Edge 16_11_2020 23_50_43](https://user-images.githubusercontent.com/168854/99317720-ca418980-2866-11eb-98eb-20e58e5eafc5.png)

**Comment by tenderlove** [comment]
I think there is a tag? https://github.com/rack/rack/tree/2.2.3
