### ISSUE TITLE
Asserts in Rack::Lint are very inefficient

### ISSUE THREAD

**Issue by eregon** [rack/rack#1723]
I was looking at the failure of truffleruby-head on a recent run:
https://github.com/rack/rack/runs/1482881957
```
[ruby] WARNING OutOfMemoryError
<internal:core> core/truffle/string_operations.rb:144:in `copy_from': failed to allocate memory (NoMemoryError)
	from <internal:core> core/string.rb:530:in `block in inspect'
	from <internal:core> core/string.rb:529:in `each'
	from <internal:core> core/string.rb:529:in `inspect'
	from /Users/runner/work/rack/rack/lib/rack/lint.rb:758:in `block in each'
	from /Users/runner/work/rack/rack/lib/rack/lint.rb:756:in `each'
	from /Users/runner/work/rack/rack/lib/rack/lint.rb:756:in `each'
	from /Users/runner/work/rack/rack/lib/rack/response.rb:277:in `buffered_body!'
	from /Users/runner/work/rack/rack/lib/rack/mock.rb:191:in `initialize'
	from /Users/runner/work/rack/rack/lib/rack/mock.rb:85:in `request'
	from /Users/runner/work/rack/rack/lib/rack/mock.rb:59:in `post'
	from /Users/runner/work/rack/rack/test/spec_show_exceptions.rb:58:in `test_0003_handles invalid POST data exceptions'
```

And noticed https://github.com/rack/rack/blob/d3225f7c201320ed272a2fa7b000c5850e4a5f88/lib/rack/lint.rb#L758-L760 which seems very innefficient.
Notably it will call `String#inspect` on each part of the body, even if it is correctly a String.

The general `assert` pattern like:
```ruby
        assert("Body yielded non-string value #{part.inspect}") {
          part.kind_of? String
        }
```
seems to have the same problem, the error message can be very expensive to compute, and should only be computed on error, not if the condition passes.

So I guess we should swap the arguments here, and have the message computed in the block, and the condition as an argument since the condition must be always evaluated, but the message needs not:
```ruby
        assert(part.kind_of? String) {
          "Body yielded non-string value #{part.inspect}"
        }
```
or maybe keep it simple and:
```ruby
unless part.kind_of? String
  raise LintError, "Body yielded non-string value #{part.inspect}"
end
```
This avoids many String allocations and whatever interpolations are done, etc.

I guess Rack::Lint is never meant to be used in production, but in the current state I would say it's so slow and inefficient that it will often be unusable.

---

We'll probably try to make String#inspect more efficient in TruffleRuby, but in general String#inspect should only be used for debugging and when an error is raised, because it is quite slow and a large overhead.

**Comment by jeremyevans** [comment]
Agreed that we should fix this.  I don't think changing the assert API is a good idea, since it is technically a public API. I think keeping it simple and using the `unless` example you gave is best.

You are correct that Rack::Lint is not meant to be used in production.

**Comment by eregon** [comment]
I'll make a PR for this.
