### ISSUE TITLE
ETag: undefined method `empty?'

### ISSUE THREAD

**Issue by sumpfralle** [rack/rack#1725]
The Debian package installation of gitlab exposes a [problem with gitlab's artifact handling](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968626), which seems to be related to rake's `ETag` class:
```
undefined method `empty?' for 201:Integer
/usr/lib/ruby/vendor_ruby/rack/etag.rb:70:in `block in digest_body'
/usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:34:in `block in each'
/usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:34:in `each'
/usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:34:in `each'
/usr/lib/ruby/vendor_ruby/rack/etag.rb:68:in `digest_body'
/usr/lib/ruby/vendor_ruby/rack/etag.rb:31:in `call'
/usr/lib/ruby/vendor_ruby/rack/conditional_get.rb:40:in `call'
/usr/lib/ruby/vendor_ruby/rack/head.rb:14:in `call'
/usr/share/rubygems-integration/all/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/share/gitlab/lib/gitlab/middleware/read_only/controller.rb:52:in `call'
```

The following patch solves/hides/works around this problem:
```patch
--- /usr/lib/ruby/vendor_ruby/rack/etag.rb.old  2020-12-19 18:54:53.266122418 +0100
+++ /usr/lib/ruby/vendor_ruby/rack/etag.rb.new  2020-12-19 18:54:04.169502266 +0100
@@ -67,7 +67,7 @@

         body.each do |part|
           parts << part
-          (digest ||= Digest::SHA256.new) << part unless part.empty?
+          (digest ||= Digest::SHA256.new) << part if part.is_a?(String) && !part.empty?
         end

         [digest && digest.hexdigest.byteslice(0, 32), parts]
```

I am not sure, whether this problem is caused
* A) by the `ETag` class (failing to handle integer values as part of the *body*) 
* B) or by gitlab, due to sending invalid data to `ETag`.

The [documentation of the `ETag` class](https://github.com/rack/rack/blob/1970771c7e01d54cb631dae0bc7618e2561ad1c7/lib/rack/etag.rb#L7) contains the following sentence:

> Automatically sets the ETag header on all String bodies.

Does this mean, that non-string bodies should be ignored or are non-string bodies considered illegal input?

Thank you for your time!

**Comment by jeremyevans** [comment]
Part of the rack SPEC is that calling `each` on the body must yield strings. From SPEC:

```
The Body must respond to each
and must only yield String values.
```

If GitLab isn't doing this and is providing a body where `each` yields something that isn't a string, it is violating the rack SPEC, and the related code should be fixed in GitLab.

**Comment by sumpfralle** [comment]
Thank you for your helpful and quick clarification!
