### ISSUE TITLE
Remove WEBrick handler?

### ISSUE THREAD

**Issue by voxik** [rack/rack#1728]
Various handlers were removed. However WEBrick remained, probably on the base of the default server. But since WEBrick was removed from Ruby, maybe it is time to remove also the handler?

**Comment by jeremyevans** [comment]
Removing the webrick handler would currently break `test/spec_server.rb`.  We would need to address this before we could remove the webrick handler.  We would also have to switch to a different handler for the tests.  I don't see much of an advantage to switching the tests to a different handler.

We could get the handler included in newer versions of the webrick gem, but it will be a few years before we could remove the webrick handler from rack if we don't want to risk breaking rack usage on Ruby 2.  I think we should wait until we drop Ruby 2 support from Rack before we drop the webrick handler.

**Comment by voxik** [comment]
That is fair.
