### ISSUE TITLE
Rack::Builder.load_file - read as UTF-8 ?

### ISSUE THREAD

**Issue by MSP-Greg** [rack/rack#1735]
Assuming an *.ru file with multi-byte characters in strings (a modern 'Hello World'), and error is thrown in the following code:

https://github.com/rack/rack/blob/a05f8d56f9ac4da14dddb8f312a3b43644f73397/lib/rack/builder.rb#L86-L90

One option might be:

```ruby
config = ::File.read(path, mode: 'rb:UTF-8')
```

or
```ruby
begin
  first = config[/^#\\(.*)/]
rescue ArgumentError # probably UTF-8 encoding
  config.force_encoding 'UTF-8'
  config.slice!(/\A#{UTF_8_BOM}/)
  first = config[/^#\\(.*)/]
end

if first
```

Not knowing previous encoding issues, nor being familiar with the test code...

**Comment by jeremyevans** [comment]
I'm not sure why `config[/^#\\(.*)/]` is raising ArgumentError for you.  I can't reproduce using a UTF-8 string with a BOM and multi-byte characters inside a string:

```ruby
s = "\ufeff#\\foo bar\n\"\u1234\""
s.slice!(/\A\ufeff/)
s[/^#\\(.*)/]
# => "#\\foo bar"
```

I don't think we should be forcing `config.ru` to be UTF-8, and think only using `slice!` if an ArgumentError is raised is wrong:

```ruby
s = "\ufeff#\\foo bar\n\"\u1234\""
s[/^#\\(.*)/]
# => nil
```

Can you provide an failing example/test?

**Comment by MSP-Greg** [comment]
@jeremyevans

Thanks for looking into this.  Was working locally on a test using `systemd-socket-activate`.  If the *.ru file has any multi-byte characters, it fails.  Switching to an 'ASCII' *.ru file, it passes.  I pushed to Actions CI, and the same thing happened.

I'm confused, but it doesn't look like a rack issue.  Closing...

**Comment by MSP-Greg** [comment]
@jeremyevans

Working on something where I was reminded of this issue.  Might it be possible to add the following below line 88 shown above:
```ruby
config.force_encoding(Encoding::UTF_8) if config.encoding == Encoding::US_ASCII
```

I believe `Encoding::US_ASCII` is a subset of `Encoding::UTF_8`, so the change shouldn't affect anything?

As mentioned above, the issue is with `systemd-socket-activate`, but getting that changed (and updated everywhere) is a bit more involved...

**Comment by jeremyevans** [comment]
In general, I'm not in favor of adding code to one library to work around a bug in another library.  However, in this particular case, it may make sense to assume that the `.ru` file is UTF-8 encoded, since that is the default Ruby source encoding.

An alternative implementation approach would be to add `encoding: 'UTF-8'` to the `File.read` call, though that goes even further and would break cases where non-UTF-8 data is used.

**Comment by MSP-Greg** [comment]
> In general, I'm not in favor of adding code to one library to work around a bug in another library

Agreed.

> ... would break ...

I thought that only converting it if it's `Encoding::US_ASCII` would be the best alternative.

Not sure if `Encoding::ASCII` and/or `Encoding::ASCII_8BIT` are also considered subsets of UTF_8?  I can check it later.


JFYI, the command is:
```
systemd-socket-activate --listen=127.0.0.1:40001 <your app/server start code>
```

Running the 'app/server code' alone, rack has the encoding as UTF-8.  When it's started by `systemd-socket-activate`, the encoding is US_ASCII...

**Comment by ioquatix** [comment]
Isn't this a bug in your system? I've had encoding issue like this before and it usually stems from the wrong encoding being set for the system itself.

**Comment by MSP-Greg** [comment]
If a command works by itself, but doesn't work with `systemd-socket-activate`, then I believe my system is ok...
