### ISSUE TITLE
Selecting last ip address in the X-Forwarded-For Header

### ISSUE THREAD

**Issue by ahoglund** [rack/rack#1746]
👋🏼 Friendly Rack Maintainers!

We've encountered a bit of an issue with the return value of the `ip` method in the case where the `Rack::Request.ip_filter` has been set to a custom lambda. In the scenario where `Rack::Request.ip_filter` has been set to not exclude all private ip address ranges, this line:

https://github.com/rack/rack/blob/master/lib/rack/request.rb#L368

would return a proxy address rather than a client ip.  At the very least, it has more _potential_ to do so since it's selecting the `last` ip in the list rather than the first.  And it is my understanding that the `X-Forwarded-For` header should be populated with `client, proxy1, proxy1`.

Example:

```ruby
   # override the ip filter to only include 127.0.0.1, ::1, and localhost
    Rack::Request.ip_filter = lambda { |ip| /\A127\.0\.0\.1\z|\A::1\z|\Alocalhost\z/i.match(ip)  }
```

Doing this type of override may be needed in the case where a request is coming from some other server in a private cloud or datacenter, but is still considered an "external" service.

```shell
$ curl -H "X-Forwarded-For: 10.5.4.3, 10.2.2.2" http://service:3000
```

This request would have its `ip` set as `10.2.2.2` since neither of these ip's were filtered out. But according to how `X-Forwarded-For` works (and [this comment](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L364-L367)) it seems that in this case we would want to default to grabbing the first ip in the list in this scenario.

If I take the standard scenario, where the default Rack ip_filter is used selecting the `first` ip in the list would still work as desired.

```shell
$ curl -H "X-Forwarded-For: 88.2.3.4, 10.2.2.2" http://service:3000
```

In this case, the `10.2.2.2` would be filtered by the default [Rack ip_filter](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L19).  So whether or not you grab `first` or `last` is irrelevant.

And in the case where it filters out everything:
```shell
$ curl -H "X-Forwarded-For: 10.5.4.3, 10.2.2.2" http://service:3000
```

It would grab the `first` item in this list anyways.

I am proposing we change [this code](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L368) to call `first` in both scenarios.

I would be happy to open a PR to change this but wanted to ask this question first because maybe there are other scenarios in which getting `last` is totally valid.

Thanks!

**Comment by ahoglund** [comment]
Well, it's been pointed out to me that this is not a recent concern or issue.  It's literally the first issue here 🤦🏼 

https://github.com/rack/rack/issues/1

and I was reading through this as well: https://github.com/rack/rack/issues/1055

**Comment by ioquatix** [comment]
I'm happy to discuss a fix for this but ideally we need

- Don't break existing apps, so maybe we need an expanded interface with the same default behaviour.
- Reference to RFC/standards which indicate the correct approach if possible.

If the current behaviour is indeed the correct one, there is still an actionable item here which is related to documentation, i.e. make sure that it's clear why the decision has been made.

**Comment by ahoglund** [comment]
As far as I understand the reasoning behind wanted to choose the `last` ip in this scenario is due to potential spoofed ip's in the `X-Forwarded-For` header.  So by picking the last one we can be more confident that the ip we are using for the request is valid.

> so maybe we need an expanded interface with the same default behavior.

This unexpected behavior only came up for our use case because we overrode the `ip_filter` regex.  I wonder if some sort of other filter or option could be leveraged to be able to continue selecting the `first` ip.  Or maybe just an optional configuration value that can be set (and defaults to current behavior). 

So, for example in my above code:

```ruby
# override the ip filter to only include 127.0.0.1, ::1, and localhost
Rack::Request.ip_filter = lambda { |ip| /\A127\.0\.0\.1\z|\A::1\z|\Alocalhost\z/i.match(ip)  }
Rack::Request.prefer_client_ip_addresses = true
```

If this is set, then my web application will return the first ip in the `X-Forwarded-For` in cases where we've allowed certain internal ip ranges to be considered external.

**Comment by ioquatix** [comment]
I'm okay with something like this since we already have a precedent for it, but that being said, I wonder if we should have a slightly more elaborate model with a single attribute. I don't like per-process overrides like this very much, personally. What you are saying makes sense to me.

```
Rack::Request.ip_filter = Rack::AddressFilter.new(...)
```

is one idea.

**Comment by matthewd** [comment]
I don't understand this, sorry.

The point of `ip_filter` is specifically to exclude proxies from the forward list. You're overriding it to _not_ match proxies, which you then wish to not use as the client IP?

`first` puts the IP entirely under client control; at that point it's just some arbitrary client-supplied value, not any indication of who you're actually talking to... what are you using it for, that it's still useful if any malicious request can just decide its IP should be recorded as `111.111.111.111`?

**Comment by matthewd** [comment]
(wisdom aside, `prefer_client_ip_addresses = true` is already supported: it is spelled `ip_filter = -> { true }`)

**Comment by ahoglund** [comment]
@matthewd - Thanks for your feedback and wisdom! 🙇🏼 

> You're overriding it to not match proxies, which you then wish to not use as the client IP?

Not exactly.  Since the default filter will exclude `10.0.0.0/8` ip addresses, it is _also_ filtering requests being made from legitimate clients that are within that same ip address range.  So, we've overridden the filter to _not_ exclude `10.0.0.0/8` addresses. So the list in the `X-Forwarded-For` header will include both client and proxy address within that ip range.

```
X-Forwarded-For: 10.5.4.3, 10.2.2.2
                 ^ client, ^ proxy
```

**Comment by matthewd** [comment]
For the specific case where the filter excludes all addresses, the first address should already win (the client address in that example) -- see #1224, and request.rb:368 as linked in this issue body.

If you truly distrust the client, then you _should_ exclude it from `ip_filter`, so it can't lie about being a proxy for some other, arbitrary, IP address. As I mentioned above, though, "use the leftmost address always" is the opposite of that -- it's equivalent to trusting all clients to choose what address they'd like to be logged as, regardless of actual network topology.

It sounds like you need to set `ip_filter` to match `10.2.2.2` (or whatever subnet it lives in, but not all of `10/8`) to accurately reflect your trust boundary. I don't think you need a new / changed feature to support this use case.

**Comment by ioquatix** [comment]
@ahoglund It feels like there is sufficient discussion to address your concern/problem. I agree that there can be concerns about the value of those headers and determining the actual client IP address. More work is required here as we move to adopt the `forwarded` header.

I will close this issue for now. If you feel that this is still a problem, can you give some failing test cases? Please feel free to re-open this issue in that case.

**Comment by ioquatix** [comment]
One other idea to consider is we could introduce `Request#client_address` or `Request#peer_address` which uses the first address. I'll think about whether this warrants more energy.
