### ISSUE TITLE
Rack on master seems incompatible with actionpack 6.1.4.1

### ISSUE THREAD

**Issue by timhaines** [rack/rack#1768]
I updated my Gemfile to use the latest commit on master earlier today, and when I ran my tests I received this error:

```
gems/ruby-2.7.4/gems/actionpack-6.1.4.1/lib/action_dispatch/http/request.rb:27:in `<class:Request>': uninitialized constant Rack::Request::Env
```

Sorry - don't have time to investigate further right now, but seemed worth reporting.

**Comment by jeremyevans** [comment]
This should be fixed as I merged #1755.
