### ISSUE TITLE
ruby 3.0 support?

### ISSUE THREAD

**Issue by GildedHonour** [rack/rack#1770]
Rake 2.2.3 doesn't support ruby 3.0.x, does it?

**Comment by jeremyevans** [comment]
Rack 2.2.3 should support Ruby 3.0.x.  Have you tried it and run into any bugs?

**Comment by GildedHonour** [comment]
Yes and it failed due to something related with keyword arguments.

**Comment by jeremyevans** [comment]
Closing due to lack of response.
