### ISSUE TITLE
Get filename from header include % character

### ISSUE THREAD

**Issue by anhdd2901** [rack/rack#1772]
I've tried to upload a file which has character % in filename. But what I get from the rack is different from the header
What should I do to solve this problem?
In my case:
- My filename is "%abcdef.docx"
- filename received from rack: "\xABcdef.docx"
- my filename get from header['Content-Disposition']: '....; filename="%abcdef.docx"...'
![binding](https://user-images.githubusercontent.com/46146496/134641996-2d846897-9404-4989-b2c7-8eac81069053.png)

**Comment by jeremyevans** [comment]
You need to escape the file name when uploading the file (you can use `URI::DEFAULT_PARSER.escape`).  Rack will then unescape the name when it parses the uploaded file, resulting in the same name as the original file.   Can you try that and report whether it works for you?

**Comment by anhdd2901** [comment]
Thanks for  your comment.
I don't pass filename in parameter or header. I only pass file in form-data. So, I don't think this escape suit for me.
Do you have another solution?

**Comment by jeremyevans** [comment]
The file you pass in form-data is turned into a parameter when the form is submitted.

Please post a minimal self-contained reproducible example showing the problem you are having.

**Comment by jeremyevans** [comment]
Closing as this doesn't appear to be a problem with Rack.
