### ISSUE TITLE
Allow using Process.daemon(nil, true) "noclose" with rackup

### ISSUE THREAD

**Issue by singpolyma** [rack/rack#1775]
If STDOUT has been redirected to a file or pipe, it can be useful to daemonize but leave them open.  Something like:

    rackup -Dnoclose

to cause the call to be `Process.daemon(nil, true)` instead of the defaults of both nil.

**Comment by jeremyevans** [comment]
I'm not opposed to this feature, but I would like to avoid the optional argument.  Maybe something like `--daemonize-noclose` (only long option, since rarely needed). Is that something you could submit a pull request for?
