### ISSUE TITLE
Can rack.after_reply be added to the spec?

### ISSUE THREAD

**Issue by BlakeWilliams** [rack/rack#1777]
Both [Puma](https://github.com/puma/puma/blob/56a25f709604240fb32310f15126d47d5a6541ca/lib/puma/request.rb#L72-L176) and [Unicorn](https://github.com/defunkt/unicorn/blob/158e9aad11ee2ed7dc01182da150e803f7cdbfef/lib/unicorn/http_server.rb#L632-L657) have support for `rack.after_reply` which has been extremely useful but it's not part of the official Rack spec. 

Given its usefulness and existing support, would it make sense to make this an official part of the spec to help encourage other rack based webservers to implement this functionality? If not, is there a path forward to making this an official part of the spec?

**Comment by ioquatix** [comment]
@tenderlove I know you have some ideas around this, do you mind reviewing this request?

**Comment by tenderlove** [comment]
I agree we should add this and I like `rack.response_finished`.  I'm not 100% sure what to do in the case of errors though.  I think we should send this message even in the case an error occurs, but pass a value (maybe an exception object?).  The thing is no webserver can really guarantee this thing will get executed (maybe the process segv's, or gets `kill`d or something).  I don't think that's a big deal, we just need to document it.  Also each webserver should probably document its guarantees wrt executing this.

**Comment by ioquatix** [comment]
@BlakeWilliams do you want to have a go at cutting the spec for this? Update `lib/rack/lint.rb`

**Comment by nateberkopec** [comment]
Just linking for posterity - an excellent use of `after_reply`: https://github.com/testdouble/maybe_later

**Comment by BlakeWilliams** [comment]
> @BlakeWilliams do you want to have a go at cutting the spec for this? Update `lib/rack/lint.rb`

Definitely, I'll make some time to work on that.

**Comment by BlakeWilliams** [comment]
Just opened up a draft PR that has a few open questions here: https://github.com/rack/rack/pull/1802

**Comment by ioquatix** [comment]
Merged in https://github.com/rack/rack/pull/1952
