### ISSUE TITLE
Link to SPEC.rdoc is dead

### ISSUE THREAD

**Issue by hupf** [rack/rack#1782]
The generated link to the specification file (`SPEC.rdoc`) in the `README.rdoc` apparently does not work. It links to https://github_com/rack/rack/blob/master/SPEC_rdoc.html whereas it should link to https://github.com/rack/rack/blob/master/SPEC.rdoc.

In the `README.rdoc` file it is specified as such:
```
{\Rack specification}[https://github.com/rack/rack/blob/master/SPEC.rdoc]
```

**Comment by jeremyevans** [comment]
Thanks for the report.  I'll fix this using rdoc-ref.

**Comment by ecantu12** [comment]
thanks
