### ISSUE TITLE
rack 2.2.2 broken sidekiq UI

### ISSUE THREAD

**Issue by siddhant-mohan** [rack/rack#1785]
NoMethodError (undefined method `bson_type' for #<Rack::Session::SessionId:0x00007f922c377a88>).

rack version - 2.2.2
sidekiq version - 6.3.1
rails version - 6

**Comment by jeremyevans** [comment]
Rack isn't calling `bson_type`, something else is.  You'll need to update the related code so it doesn't call methods that aren't defined. If this is related to Sidekiq, you probably want to ask them, hopefully with a much more complete description of the issue that at least shows the backtrace.
