### ISSUE TITLE
TypeError: nil can't be coerced into Float

### ISSUE THREAD

**Issue by izaguirrejoe** [rack/rack#1822]
Ruby version 3.0.3
Rails 7.0.1

I'm getting the following error in browser console when reloading page in a Rails Application. This is an intermittent error, it appears randomly when reloading the page. Usually it takes 4-5 reloads for it to appear. It's always a random asset that fails:

```
2022-02-27 17:51:33 -0800 Rack app ("GET /assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js" - (::1)):
 #<TypeError: nil can't be coerced into Float>
```

I'm not sure if this is a Rack problem, Sprockets problem, or something in my code. Is there a way to debug this to see exactly which line is causing the TypeError? A backtrace?

**Comment by ioquatix** [comment]
We need a full backtrack.

**Comment by matthewd** [comment]
I don't immediately recognise that log line format as coming from either Rack or Sprockets, so I'd suggest finding its source -- that's presumably where the exception is being so aggressively truncated. Perhaps your web application server, or some log-shortening middleware?

When opening issues across multiple projects, it's best to at least cross-reference them (cc rails/sprockets#738)

**Comment by izaguirrejoe** [comment]
Thanks @matthewd, I figured it's probably the application server, I'm just surprised as to why there's no backtrace. I'm having to start from scratch essentially.

**Comment by SkipKayhil** [comment]
This sounds very similar to rails/rails#44167. You could try disabling the `ServerTiming` middleware or using rails `7.0-stable` branch and see if the issue goes away

**Comment by ioquatix** [comment]
I don't believe this is related to Rack but feel free to re-open the issue with more detailed information.

**Comment by izaguirrejoe** [comment]
Thanks @SkipKayhil that sound exactly like my issue!
