### ISSUE TITLE
Eager loading mode?

### ISSUE THREAD

**Issue by casperisfine** [rack/rack#1823]
For context there's a discussion in Ruby's bug tracker about replacing the global constant cache by a more finely grained cache: https://bugs.ruby-lang.org/issues/18589

This led me to investigate global constant cache busts in our app, and one source turned out to be `rack`.

For instance the first time we access `Request#media_type` it triggers the autoloading of `Rack::MediaType` which bust the cache, but also means this code wasn't loaded pre-fork, so slightly degraded Copy on Write performance.

I get that the library make use of `autoload` so that you only pay for what you actually need, but if I could chose I think I'd rather load a bit of unused code.

@jeremyevans would you be open to a `Rack.eager_load!` method?

**Comment by casperisfine** [comment]
Another example is `Rack::Auth::Digest`:

```
    from gems/rack-2.2.3/lib/rack/auth/digest/params.rb:6:in `<module:Digest>'
    from gems/rack-2.2.3/lib/rack/auth/digest/params.rb:5:in `<module:Auth>'
    from gems/rack-2.2.3/lib/rack/auth/digest/params.rb:4:in `<module:Rack>'
    from gems/rack-2.2.3/lib/rack/auth/digest/params.rb:3:in `<main>'
    from gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    from gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    from gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:244:in `handle_mime_head'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:211:in `block in run_parser'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:204:in `loop'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:204:in `run_parser'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:188:in `on_read'
    from gems/rack-2.2.3/lib/rack/multipart/parser.rb:73:in `parse'
    from gems/rack-2.2.3/lib/rack/multipart.rb:54:in `extract_multipart'
    from gems/rack-2.2.3/lib/rack/request.rb:594:in `parse_multipart'
    from gems/rack-2.2.3/lib/rack/request.rb:446:in `POST'
    from gems/rack-2.2.3/lib/rack/method_override.rb:45:in `method_override_param'
    from gems/rack-2.2.3/lib/rack/method_override.rb:29:in `method_override'
    from gems/rack-2.2.3/lib/rack/method_override.rb:17:in `call'
```

**Comment by jeremyevans** [comment]
Starting in Rack 3, you'll be able to load only the parts of rack you are using via `require 'rack/request'`.  These parts generally will not use autoload, though a few cases still do.  I'm up for switching the remaining cases that use autoload to require_relative, so that autoloads will only be used if you do `require 'rack'`. Do you think that will meet your need?

I strongly dislike the use of autoload, for a different reason.  I run my production applications in high security environments that drop access to most of the filesystem after loading the application, and every gem that uses autoload needs an exception so the gem directory is still  allowed to be accessed. Unfortunately, I think it's a bit too late to remove autoload from Ruby.

**Comment by jeremyevans** [comment]
I think one of the problems with loading everything by default is that the vast majority of rack will probably not be used, and it seems wasteful.  If you are running something like Rails, such waste may seem small in comparison, but not everyone is doing that.

Another alternative would be to add a `rack/eager_load` file that resolved all autoloads.  I like that approach better than a `Rack.eager_load!` method.

**Comment by casperisfine** [comment]
> and it seems wasteful

I'd argue that it's potentially more wasteful to lazy load it if we assume that Ruby is generally deployed in a forked setup. That's as much memory that will be duplicated in each puma or unicorn worker, instead of being shared in the parent process.

That being said, there's indeed a fine line between what is likely to be used by the vast majority of users, and what is more niche.

In the case of Rails, `Rack::Request` is referenced during boot, so I'd be ok with doing a  `require_relative` for `Rack::MediaType` and `Rack::Auth::Digest` in `request.rb`.

I'll prepare a PR.

**Comment by jeremyevans** [comment]
`Rack::Auth::Digest` will likely be removed (the part of the multipart parser that uses it is being changed, see #1821).  `rack/request` already does a require_relative on `media_type`.

**Comment by casperisfine** [comment]
Ok, it seems that the two classes causing my issues are either already eager loaded on `main`, or are about to, so closing.

Thanks!
