### ISSUE TITLE
Cookie parsing failed with base64 ´=´ padding characters

### ISSUE THREAD

**Issue by sergioa** [rack/rack#1830]
It seems that [this](https://github.com/rack/rack/pull/1645) fix hasn't been back ported to [2-2-stable](https://github.com/rack/rack/tree/2-2-stable) branch.

Our code is breaking when trying to parse a Cookie with equals characters in it.

Latest release, 2.2.3, does not include this bug fix.

May you consider to release a new version including it?

**Comment by jeremyevans** [comment]
I'm not against a 2.2.4 release.  However, if we are going to do a bug-fix 2.2.4 release, we should evaluate other fixes committed since 2.2 and see if any make sense to backport.

**Comment by jeremyevans** [comment]
This isn't a security issue, and this would be for 2.2-stable, is should only be updated for security issues, so I think we should close this.
