### ISSUE TITLE
"Wiki > Tutorials > Understanding Rack Middleware" leads to a website with malware

### ISSUE THREAD

**Issue by rosatolen** [rack/rack#1852]
When following the "Understanding Rack Middleware" link in the Wiki > Tutorials page, my Chrome browser warns me there is malware there, and blocks me from visiting that page.

**Comment by ioquatix** [comment]
I checked it and it looks okay to me on Safari, but not to say the problem doesn't exist (maybe your browser is better/more sensitive). Do you know why it's being reported?

**Comment by ioquatix** [comment]
I plugged this into Google's safe site report:

https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fcodenoble.com%2Fblog%2Funderstanding-rack-middleware%2F&hl=en

It came back as okay.

**Comment by ioquatix** [comment]
I cannot reproduce this issue but please let us know if this continues to be a problem.
