### ISSUE TITLE
Noticing `Net::HTTP` `EOFError` in CI.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1859]
I've been noticing this recently and don't really know why it's coming up.

<img width="817" alt="Screen Shot 2022-04-08 at 6 13 10 PM" src="https://user-images.githubusercontent.com/30030/162375499-8b8c60ae-929c-4ff4-a317-aa860ccad305.png">

It looks like race condition... maybe?

**Comment by ioquatix** [comment]
I wonder if it's related to this:

https://bugs.ruby-lang.org/issues/14972

**Comment by ioquatix** [comment]
Blowing up on this line:

https://github.com/jruby/jruby/blob/9.3.4.0/lib/ruby/stdlib/net/protocol.rb#L225

**Comment by ioquatix** [comment]
@headius @eregon do you have any advice about what might be going wrong here? I've seen it affect both JRuby and TruffleRuby... I'm a bit suspicious that the busy waiting here is not very robust. Check #1860 for a proposed solution... also concerned about `Process.kill :INT, $$` which seems really unproductive. I mean, it appears to work, but it also seems like it might introduce other issues.

**Comment by jeremyevans** [comment]
I think this is related to code moved into the `rackup` gem, so I'm closing this.  I'm guessing the issue still exists in the `rackup` gem, so maybe an issue should be opened in that repository.

**Comment by ioquatix** [comment]
I'm fine with that.
