### ISSUE TITLE
Does round-tripping cookie names work as expected?

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1865]
While working through the cookie utils methods adding documentation and examples, I noticed the following:

```
Rack::Utils.set_cookie_header("a&b", ":)")
# => "a%26b=%3A%29"

cookies = Rack::Utils.parse_cookies_header("a%26b=%3A%29")
# => {"a%26b"=>":)"}

Rack::Utils.set_cookie_header("a%26b", ":)")
# => "a%2526b=%3A%29"
```

URL encoding the cookie name on the way to the client but not on the way back from the client means that if a server application tries to set the same cookie based on the incoming name, it will have it's percent escapes encoded again, never reaching a fixed point/symmetry.

Not sure if this is the desired behaviour or not. I know there is a security issue with decoding cookies which are URL encoded. Just wondering if we've made the right trade off here.

Looking at the relevant RFCs:

```
         CTL            =  %x00-1F / %x7F
                                ; controls
```

```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

```
 set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
```

Maybe rather than general URL encoded cookie key names, we should either:

1. Reject any cookie key that doesn't match the `token` pattern, or
2. Have a `token` specific encoded form which encodes and decodes **only** `CTLs or separators` as defined by the parser.

Sorry to get pedantic about this but I'm a little concerned that URL encoding cookie keys is probably not the right behaviour and maybe we should follow the RFCs here more closely.

**Comment by ioquatix** [comment]
So thinking this out a bit more, the following are valid cookie key characters:

```
!#$%&'*+-.^_`|~
```

And should not be encoded, but they are:

```
Rack::Utils.set_cookie_header("!#$%&'*+-.^_`|~", ":)")
# => "%21%23%24%25%26%27*%2B-.%5E_%60%7C%7E=%3A%29"
```

This means that if someone writes:

```
headers = {'set-cookie' => '~=~'}
Rack::Utils.set_cookie_header!(headers, '~', '~')
=> ["~=~", "%7E=%7E"]
```

This will result in the browser storing two distinct cookies. Obviously an edge case but an edge case non-the-less.

**Comment by robinetmiller** [comment]
Just encountered this today in a situation wherein cookie keys included `#` as a separator for additional namespacing. 
This was fine when only created & parsed in JS, but but they are overzealously escaped when coming from Rack, breaking compatibility.

Somewhat related (though maybe should file a different issue) is the use of `Rack::Utils.escape`, which uses `URI.encode_www_form_component` under the hood and produces `+` for whitespace.

Would `Rack::Utils.escape_path` instead be better? I haven't verified, but I wonder if it would align with JS `encodeURI()` or `encodeURIComponent()`.

**Comment by jeremyevans** [comment]
I think the current behavior is expected due to the cookie security fix.  If there is a way to fix it that does not result in reintroducing a security issue, I would be open to that, but I'm not sure it is possible.  Not encoding characters that do not need to be encoded seems fine with me, though.

**Comment by ioquatix** [comment]
I've created a PR which retains the security properties of the current implementation, while unescaping the vast majority of cookies.

However, I believe we should probably consider removing the key escape/unescape, for the reasons explained by @robinetmiller above. In other words, we should throw an error if the cookie key cannot be encoded correctly.

**Comment by ioquatix** [comment]
The first step is <https://github.com/rack/rack/pull/2191>.

Later, we will remove the `escape` behaviour. As a result, there will be neither `escape` nor `unescape`, so cookie keys will be symmetrical and also align better with `document.cookies`.
