### ISSUE TITLE
Midldleware is displayed as Module rather than Rack::Cache on Rails 6.1.5

### ISSUE THREAD

**Issue by acronin-stash** [rack/rack#1877]
Similar to issue: https://github.com/rtomayko/rack-cache/issues/172
but this is happening on:
Rails 6.1.5
Ruby 3.0.1.

Added config.middleware.insert_after(Rack::ETag, Rack::Cache) to application.rb to confirm and getting this output from rake middleware:

use ActionDispatch::HostAuthorization
use Rack::Sendfile
use ActionDispatch::Static
use Module
use ActionDispatch::Executor
use Rack::Runtime
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use Sentry::Rails::CaptureExceptions
use ActionDispatch::DebugExceptions
use Sentry::Rails::RescuedExceptionInterceptor
use ActionDispatch::ActionableExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Module
run Lembas::Application.routes

**Comment by jeremyevans** [comment]
Is there a reason you think this is a problem in rack itself, and not in rack-cache or Rails?

**Comment by acronin-stash** [comment]
Nope, apologies I actually meant to open this in `rack-cache` issues. Too many tabs 😅 
And anyway, I think I found the bug so all good. Thanks for the quick response in any case!
