### ISSUE TITLE
Missing changelog entry for version 2.2.3.1

### ISSUE THREAD

**Issue by tgxworld** [rack/rack#1905]
Hi we got a dependabot alert about the release of rack version 2.2.3.1. However, I noticed that there isn't an entry in the changelog and was wondering if that was intentional? 

Thank you in advance.

**Comment by tgxworld** [comment]
Oops sorry, found the changelog changes in https://github.com/rack/rack/compare/2.2.3...2.2.3.1

**Comment by simi** [comment]
Yup, it is in here - https://github.com/rack/rack/blob/2-2-stable/CHANGELOG.md#2231---2022-05-27. Dependabot just fails to find those.
