### ISSUE TITLE
Cookies deletion fail

### ISSUE THREAD

**Issue by AlexWayfer** [rack/rack#1965]
Hello.

I'm working on Flame and have an error with Rack 3.0: https://github.com/AlexWayfer/flame/pull/218

I see no bullets in the CHANGELOG about logic which I use.

Especially:

```ruby
cookies[:abc] = 'xyz'
cookies[:abc] = nil
```

Which calls:

```ruby
case new_value
when NilClass
  response.delete_cookie(key.to_s, path: '/')
end
```

(I tried without `path:`, nothing changed)

And the specs output is:

```
  1) Flame::Controller::Cookies#[]= deleting cookie for response by nil value is expected to include "abc=;"
     Failure/Error: it { is_expected.to include 'abc=;' }
       expected ["abc=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT", "abc=xyz; path=/", "abc=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"] to include "abc=;"
```

So, what should I do to remove a cookie for response from version 3?

**Comment by ioquatix** [comment]
Don't set a header and then delete it in the same request. If you send this response to the browser, it won't be set, because it processes the response in order.

What is the use-case/motivation for this usage?

**Comment by AlexWayfer** [comment]
It sounds reasonable, but still works kind of weird. It's good that processing in order, but I'm not sure we're need for arrays at least in this case (cookies) at all.

Use-case… for example, some middleware (post-request) can unset some cookie at some condition. And yes, this cookie can be set previously at the pre-request hook or in the request. So, there are possible code in different places working with the same cookies (or headers).

**Comment by ioquatix** [comment]
I tested the behaviour.

It's not clear to me that "Add cookie" and "Delete cookie" are operation that should cancel each other out. So, I still think this is the correct behaviour. However, if it results in bugs or other issues, we'd like to know about it. So can you test it more?

**Comment by AlexWayfer** [comment]
> However, if it results in bugs or other issues, we'd like to know about it. So can you test it more?

How? I already had tests and they're failing.

Real-life… not sure. I'll check but doubt.

Anyway, my main point that this change is not described in CHANGELOG, as I saw, but also breaking.

**Comment by ioquatix** [comment]
> How? I already had tests and they're failing.
> Real-life… not sure. I'll check but doubt.

Yes, if you find issues with real browsers, that is important for us to consider.

> Anyway, my main point that this change is not described in CHANGELOG, as I saw, but also breaking.

Whether it's breaking change or not, I don't have strong opinion. Well, at one level, it's different behaviour, but at another level, the browser behaves the same. So, there should be no practical user visible effect.

We probably considered it too minor/implementation detail. But we can add it to the changelog for sure.

**Comment by AlexWayfer** [comment]
> Well, at one level, it's different behaviour, but at another level, the browser behaves the same. So, there should be no practical user visible effect.

Rack is a middleware (protocol, standard) between servers and frameworks, as I understand, not browser. And whenever a type of data change — it should be noticed at least. But, again, this type change is doubtful for me.

**Comment by jeremyevans** [comment]
This is already mentioned in CHANGELOG:

- Remove internal cookie deletion using pattern matching, there are very few practical cases where it would be useful and browsers handle it correctly without us doing anything special. ([#1844](https://github.com/rack/rack/pull/1844), [@ioquatix])

The backwards compatibility issues with the change were known and accepted when this was merged, and backwards compatibility breakage is allowed in major versions.  Since this is mentioned already in CHANGELOG, and I don't think @tenderlove or @ioquatix wants to revert it, I'm going to close this.

**Comment by AlexWayfer** [comment]
> * Remove internal cookie deletion using pattern matching

I saw it, but I have no deal with with pattern matching, there are simple `set_cookie` and `delete_cookie`…

**Comment by jeremyevans** [comment]
@AlexWayfer Internally, `Response#delete_cookie`, called `Utils#add_remove_cookie_to_header`, which called `Utils#make_delete_cookie_header`, which used pattern matching to remove any existing matching cookies. Would you like to propose better language for CHANGELOG?

**Comment by AlexWayfer** [comment]
> Would you like to propose better language for CHANGELOG?

You know, I'm not good in language, especially not-native English…

Probably something like:

> Remove internal cookie deletion using Regexps, and there can occur duplicates of cookies with different values in the Array. At least, browsers handle it correctly without us doing anything special. (https://github.com/rack/rack/pull/1844, [@ioquatix])

Points:
1. I see `case Regexp` removing, not pattern matching. Probably it's a subset of pattern matching, but I don't know where to check a definition (Ruby-specific). Anyway, a form of `case Regexp` description is more familiar for Ruby developers than recently introduced pattern matching, mostly for more complicated cases.
2. The most affecting me line is [with `reject!`](https://github.com/rack/rack/pull/1844/files#diff-85960cbd609e7f51a9881d1876b82d748f4ba8312a31e3329a5bb9bf791c60beL345), so I'd mention this change too, it's definitely out of any pattern matching.
