### ISSUE TITLE
rack 3: mention Rack::Handler::WEBrick and CGI in upgrading

### ISSUE THREAD

**Issue by grosser** [rack/rack#1971]
needed to dig around to find https://github.com/rack/rackup/blob/main/lib/rackup/handler/webrick.rb

**Comment by jeremyevans** [comment]
This is already mentioned in the upgrade guide: https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#binrackup-was-moved-to-a-separate-gem

Do you want to recommend different language for this section?

**Comment by grosser** [comment]
🤦 idk how I missed that, was search for webrick and did not find anything ... maybe I typed webbrick
