### ISSUE TITLE
`SourceMap` header

### ISSUE THREAD

**Issue by joelmoss** [rack/rack#1985]
I see that headers are now lowercased, which unfortunately means the `SourceMap` header, which is not dash-case, but camelCase, is not correct. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/SourceMap

How can I set this header and have Rack not lowercase it?

**Comment by jeremyevans** [comment]
Can you explain the problem with lower casing the header?  Does `sourcemap` as a header name not work?  Seems unlikely the lower case version would not work, considering HTTP/2 requires lower case headers.

**Comment by joelmoss** [comment]
I'm just saying what I see on MDN and the spec. And in my tests, `sourcemap` didn't seem to work.
