### ISSUE TITLE
should not process form data if it is a GET method

### ISSUE THREAD

**Issue by catatsuy** [rack/rack#1994]
I would like to make another suggestion on this issue. #1787

The implementation of Go is a problem. But in reality there are such HTTP clients.

I think rack should ignore them.

sinatra has implemented the following response to this problem.

https://github.com/sinatra/sinatra/pull/1743/files

I think this sinatra change is terrible. However, due to the implementation of rack, sinatra has no choice but to do this.

I propose the following changes to this issue.

https://github.com/rack/rack/blob/a7d56490fd2fb41de8c94ead2f63fbad71c5c489/lib/rack/request.rb#L470-L475

We will change the implementation of this function so that form_data? is false for GET methods. For example:

```diff
-         (meth == POST && type.nil?) || FORM_DATA_MEDIA_TYPES.include?(type)
+         (meth == POST && type.nil?) || (meth != GET && FORM_DATA_MEDIA_TYPES.include?(type))
```

We rarely send form data with the GET method.

However, this implementation would cause multiple rack tests to fail. This should be corrected in the test itself.

**Comment by sorah** [comment]
The following both arguments and present behaviours seem we're falling into inambiguity of the HTTP spec.

- https://github.com/rack/rack/issues/1787#issuecomment-1112830204
- https://github.com/golang/go/issues/52519#issuecomment-1107807401

Chaging `form_data?` definition sounds dangerous for me, this will involve unintentional incompatibility - to workaround this issue I propose handling this at Rack::Request#POST to discard error when empty body is present for non-POST/PUT/PATCH requests.

https://github.com/rack/rack/blob/a7d56490fd2fb41de8c94ead2f63fbad71c5c489/lib/rack/request.rb#LL504C58-L504C58

**Comment by ioquatix** [comment]
Thanks I've created an issue here for further discussion: <https://github.com/sinatra/sinatra/issues/1844>.

I'm not against being "liberal in what you accept" but this is a clear violation of the RFC.

So, I think we need a clear problem statement, example reproduction, a discussion from the Go team that they understand their behaviour is (?) in violation of the spec and they don't plan to fix it.

We could make a specific error for this case in Rack (i.e. something that would return a bad request). I'm more in favour of being strict in that regard than silently ignoring the error/protocol violation.

**Comment by ioquatix** [comment]
@catatsuy I think your middleware is fine if you want a compatibility fix, but just to be clear on my opinion, I think it would be better to return 400 Bad Request in such a case, since IIUC, it's prohibited for a GET request to have an entity body.

**Comment by ioquatix** [comment]
I spent some more time looking at the rack implementation, and noticed that `env['rack.input']` is non-optional even if no entity body is provided.

I think this is a little odd.

If there is no entity body, I feel like this should be nil.

That's different from "the entity body exists but was nil".

I've created <https://github.com/rack/rack/issues/1995> and will propose a PR.

**Comment by ioquatix** [comment]
I've also proposed <https://github.com/rack/rack/issues/1996> which can be used like so:

```ruby
      def parse_multipart(env, params = Rack::Utils.default_query_parser)
        unless io = env[RACK_INPUT]
          raise BadRequest, "missing multipart input"
        end
```

(from <https://github.com/rack/rack/blob/a7d56490fd2fb41de8c94ead2f63fbad71c5c489/lib/rack/multipart.rb#L17-L18>)

This to me feels like the correct solution - if we are expecting to parse a multipart body, and no body is given, this is a bad request.

**Comment by dentarg** [comment]
Sounds good to me @ioquatix

**Comment by ioquatix** [comment]
@catatsuy @sorah can you please see the above linked PR and give your feedback.
