### ISSUE TITLE
Make `env['rack.input']` optional if no entity body is given.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1995]
See <https://github.com/rack/rack/issues/1994> for more context.

Most requests don't have an entity body.

It's difficult to detect this condition except for reading from the input stream provided.

But this may fail after the fact if there is no entity body.

I feel like it would be more efficient and transparent if we simply did not set `env['rack.input']` if there is no entity body.

See <https://github.com/rack/rack/issues/1994#issuecomment-1352117937> for an example use case.

**Comment by jeremyevans** [comment]
This seems reasonable, but we need to make sure this doesn't get backported.  We should not be backporting incompatible changes, unless they are necessary for security reasons.  I found out that we released Rack 3.0.2 with backwards incompatible changes: ab1f1c1f912c5e434e0ac05b26140f5b8b2c0bff.  We should be much more judicious in our backporting, IMO.

**Comment by ioquatix** [comment]
ab1f1c1 is a bug fix IMHO.

**Comment by jeremyevans** [comment]
> [ab1f1c1](https://github.com/rack/rack/commit/ab1f1c1f912c5e434e0ac05b26140f5b8b2c0bff) is a bug fix IMHO. I'm fine with making this part of Rack 3.1, but I also don't see it as a hugely breaking change. We could assess it based on the impact it has to external tests.

Water under the bridge as Rack 3.0.2 has already shipped with it.  But bug fixes with backwards compatibilities should only be backported if the need is great.
