### ISSUE TITLE
[2.2.4] lib/rack/urlmap.rb:38: warning: 3rd argument to Regexp.new is deprecated and will be removed in Ruby 3.3; use 2nd argument instead

### ISSUE THREAD

**Issue by drnic** [rack/rack#2002]
In ruby 3.2, the latest rack 2 (2.2.4) has a deprecation warning.

Perhaps its possible to "fix" this deprecation in 2.2.5 for those of us not yet on rack3? Thanks in advance; and sorry to ask.

**Comment by drnic** [comment]
Ahh, I found this fix on 2-2-stable branch

https://github.com/rack/rack/commit/ac892ab84dbac20729fcc96da8fcdb5eb4aa7bb9

**Comment by simi** [comment]
Isn't that fixed in 2.2.5 (https://rubygems.org/gems/rack/versions/2.2.5)?

**Comment by ioquatix** [comment]
Yes.

**Comment by drnic** [comment]
Ugh, that's embarrassing that I didn't notice 2.2.5 had been released.

**Comment by ioquatix** [comment]
nvm :)
