### ISSUE TITLE
Please Include New Releases in Changelog

### ISSUE THREAD

**Issue by BenSandeen** [rack/rack#2022]
Dependabot keeps telling us to update rack to patch vulnerabilities, but it's hard to know what changed when the version in question (2.2.6.2) doesn't appear in changelogs or release notes
<img width="659" alt="Screenshot 2023-01-19 at 9 53 20 AM" src="https://user-images.githubusercontent.com/12025856/213490034-767acddc-dd09-4acc-9243-a6752d607c13.png">

It would be awesome if we could see a few bullet points enumerating any changes, just to assure us that it shouldn't break anything.

Thanks!

**Comment by tenderlove** [comment]
Sorry, I'm not sure where dependabot is looking, but the changes are in the changelog on the 2-2-stable branch [here](https://github.com/rack/rack/blob/2-2-stable/CHANGELOG.md)

**Comment by ioquatix** [comment]
@BenSandeen maybe you can help us by outlining a way in which we can get the changelog to show up correctly in Dependabot. That would be really helpful and hopefully actionable by us.

**Comment by BenSandeen** [comment]
Ahhh, I found the issue: I was just going to the rack repo and clicking the changelog, but that takes me to the main branch's changelog, not the changelog for the 2-2 series.  I hadn't even thought of the possibility that changelogs were branch-specific like that.

It looks like that's the exact issue that's tripping up Dependabot as well, since the link it gives me always seems to pull the changelog from the main branch.  It seems like maintaining diverging changelogs on different branches is the problem, so it would seem that just appending all new changes to the changelog in the main branch would fix this, at least in Dependabot's case.  I don't know if there are other things which might be broken by this change, though.
