### ISSUE TITLE
Been slowly catching up to the several threads about the topic, and it seems that there are two valid perspectives: on one side, the protocol needs to evolve, while on the other, breaking code relying on the current contract is unacceptable. So why not just create a new entrypoint, and thereby, a new protocol, that could reuse most of the existing boilerplace?

### ISSUE THREAD

**Issue by bazah060606** [rack/rack#2034]
Been slowly catching up to the several threads about the topic, and it seems that there are two valid perspectives: on one side, the protocol needs to evolve, while on the other, breaking code relying on the current contract is unacceptable. So why not just create a new entrypoint, and thereby, a new protocol, that could reuse most of the existing boilerplace?

I'd propose smth like this:

```ruby
def call_req(request)
  # do stuff with req

 # get a response object
  response = @app.call_req(request)
  return response
end
```

This could provide new ground for speccing smth which the current `rack` protocol is limited for, i.e. partial responses, streaming, etc, while allowing for removing the current reliance on the CGI protocol headers.

The `rack` library could then provide a compatibility layer to allow for "new protocol" middleware to drop-down to "old protocol" when needed. Consider these middlewares:

```ruby
class NewMiddleware
  def call_req(req)
    @app.call_req(req)
  end
end

class OldMiddleware
  def call(env)
     @app.call(env)
  end
end

class DualMiddleware
  def call_req(req)
     @app.call_req(req)
  end

  def call(env)
     @app.call(env)
  end
end
```

The `rack` library would be, in the rack app middleware stack chaining, be responsible for injecting "shim handlers" for the unhandled protocol versions:

```ruby
class NewMiddleware
  # rack would inject: attr_reader :request_class
  def call_req(req)
     @app.call_req(req)
  end

  # rack would inject
  def call(env)
    call_req(@request_class.from_env(env))
end

class OldMiddleware
  def call(env)
    @app.call(env)
  end

  # rack would inject
  def call_req(request)
    rack_array = call(request.to_env)

    request.make_response(rack_array)
  end
end
```

If we skip bikeshedding on the names above, the benefit would be that old middlewares would play well with new middlewares and vice-versa, in any order, with negligible impact (1 extra method call in the stack). Middlewares could be adapted for both versions. Frameworks could provide entrypoints for both versions and adapt accordingly. Application servers would be in charge with passing down request and response interfaces complying with the new protocol. 

I also agree with @jeremyevans that `Rack::Request` has too big method footprint to deem it the standard interface to implement. But the point is, in order for new interfaces to be speccable, rack needs a new entrypoint beyond `call` which allows current code to execute, and provide a migration path to a new protocol which can reuse most of the old middlewares around, while allowing to create new ones which the current protocol can't handle. 

(I've tried, and ultimately gave up on, years ago, to [build an alternative to rack](https://gitlab.com/honeyryderchuck/reqrep/)).

_Originally posted by @HoneyryderChuck in https://github.com/rack/rack/issues/1879#issuecomment-1111301095_

**Comment by jeremyevans** [comment]
Closing this, please continue discussion in #1879 if you have a perspective you would like to share.
