### ISSUE TITLE
Configure the rack stack like a tree

### ISSUE THREAD

**Issue by foonlyboy** [rack/rack#2066]
Hi at the rack team

I come up with a new module.
That should be an extended version of Rack::Static

I'd like to improve on the configuration of the rack stack.
As far as I know this is strictly sequential?
(this somehow reminds me of STREAMS, btw)

I want to declare the rack processing like a tree.
I want to have filters, mappers and handlers.

I want to show my new module
to someone from the rack team.

I need some help to write the rdoc

```
# Copyright (c) 2023 Eike Dierks, all rights reserved


# The Rockers::Rack::XMapping represents a mapping from a pattern to a translation
# the mapping from url to file are defined in the mappings hash
#
# The following mappings are supported (pattern => translation)
# - String  => String
# - Regexp  => String
# - String  => Proc
# - Regexp  => Proc
# - Proc    => Proc
#
# The mappings are applied as follows:
# - find the first mapping where the url matches the pattern
# - if a mapping is found:
#   - translate the url according to the translation from the mapping
#   - call the fileserver with the translated path
# - otherwise chain to the next rack module
#
# The url is matched against the key of the mapping as follows:
# - String matches urls starting with String
# - Regexp matches urls matching Regexp
# - Proc matches when Proc.call(url) returns truthy
#
# The url is translated using the translation of the mapping as follows:
# - String => String
#   - File.join(translation, url)
# - Regexp => String
#   - url.sub(pattern, translation)
# - * => Proc
#   - proc.call(url, pattern)
#     - it is up to the proc to do the translation
#     - TODO: what to do if the translation proc returns nil?
#     - FIXME: we should give the full env to the proc
```

**Comment by jeremyevans** [comment]
I don't think I would be in favor of shipping something like this in Rack, but I'll reserve judgment until I see the underlying code.  If you are interested in this, please submit a pull request.  Asking Rack maintainers to assist in documentation writing for a module that may not be included in Rack doesn't make sense to me.  If this is something the Rack maintainers accept, then we can have a discussion about improving the documentation for it before it is merged.

Note that `Copyright (c) 2023 Eike Dierks, all rights reserved` makes no sense if you are submitting code to be included in Rack, as Rack is open source under the MIT License, and this implies you are not reserving "all rights".

**Comment by foonlyboy** [comment]
Hi Jeremy
Thank you for your immediate reply.

My new module was not intended as a patch.
But I need some people to review my code, upfront.

I need a review in private, first.

Best regards,
Eike Dierks

(see attacheed, the coide)

**Comment by jeremyevans** [comment]
I'm sorry, but that is not how open source in general works.  Please submit a pull request if you would like code reviewed for inclusion for Rack.  If your code is not intended for inclusion in Rack, then I don't think you should be asking for review here, as this would not be the appropriate forum.

Also, as this isn't a bug report, I'm closing this.  You can continue discussion here if you want, but in general, unless you are reporting a bug, open a Discussion instead of an Issue (or open a Pull Request if you would like code reviewed for inclusion).
