### ISSUE TITLE
Add gem name (context) to "Rack::Chunked" warning message

### ISSUE THREAD

**Issue by jasnow** [rack/rack#2067]
Can you add the gem name (context) that triggered this warning message? That would help want who to monitor for fix.
```
/usr/local/rvm/gems/ruby-3.2.2@ruby3.2-railsedge/gems/rack-3.0.7/lib/rack/chunked.rb:6: 
warning: Rack::Chunked is deprecated and will be removed in Rack 3.1
```
Thanks

**Comment by ioquatix** [comment]
How would you like to see the message changed?

**Comment by jasnow** [comment]
Think I'm confused. Closing this issue.
