### ISSUE TITLE
Missing CHANGELOG entry for 2.2.7?

### ISSUE THREAD

**Issue by tisba** [rack/rack#2074]
Hey there! 👋 

Looks like 2.2.7 has been released yesterday (2023-04-24).

Looking at the diff of the release, there seems to be some changes, see https://my.diffend.io/gems/rack/2.2.6.4/2.2.7 or https://github.com/rack/rack/compare/v2.2.6.4...v2.2.7.

I'm trying to find a matching change log entry for the 2.2.7 release and couldn't find any, neither in https://github.com/rack/rack/blob/2-2-stable/CHANGELOG.md nor https://github.com/rack/rack/blob/main/CHANGELOG.md.

I'm not exactly sure how rack keeps changelog for the 2-2-stable branch. Happy to provide a PR (changes between 2.2.6.4 and 2.2.7 seems to be minor).

**EDIT** https://github.com/rack/rack/pull/2071 seems to be the only relevant change, I guess.

**Comment by ioquatix** [comment]
It's listed in the GitHub release notes. If you have time to update the change log that would be helpful.

**Comment by tisba** [comment]
Closed by https://github.com/rack/rack/pull/2081
