### ISSUE TITLE
Rack::ETag, and Enumerator support

### ISSUE THREAD

**Issue by 0x1eef** [rack/rack#2091]
Can Rack::ETag support Enumerator as well ? 
For example, the following application does not 
work out of the box with Rack::ETag because
there is no [`Enumerator#to_ary` method](https://github.com/rack/rack/blob/main/lib/rack/etag.rb#L31):

```ruby
Rack::Builder.app do
  use Rack::ETag
  run lambda { |env| [200, {}, "one\ntwo\three".each_line] }
end
```

I can call `to_a` on `each_line` and then Rack::ETag works
as expected. But I wonder if Rack::ETag can handle the 
coercion instead.

**Comment by jeremyevans** [comment]
It is expected that this will no longer work in Rack 3, and I don't think we want to support it, for the same reasons support for non-arrays was dropped.  There is no way for Rack to tell the difference between `"one\ntwo\three".each_line` and `network_socket.each_line`

**Comment by 0x1eef** [comment]
Alright - thanks for the quick response !

**Comment by 0x1eef** [comment]
I extended Rack::ETag to support If-None-Match. Afterwards I saw the performance savings I was hoping for. Sharing here in case it might be useful to anyone else:

```ruby
class Server::ETag < Rack::ETag
  ETAGS = {}

  def initialize(app)
    @app = app
  end

  def call(env)
    headers = ETAGS[env["REQUEST_PATH"]] || {}
    if headers["etag"] && headers["etag"] == env["HTTP_IF_NONE_MATCH"]
      [304, headers, [""]]
    else
      status, headers, body = super(env)
      ETAGS[env["REQUEST_PATH"]] = headers
      [status, headers, body]
    end
  end
end
````

**Comment by ioquatix** [comment]
Not only does that seem like it would leak memory over times, it also looks thread unsafe. Just FYI.

**Comment by 0x1eef** [comment]
It is for a development server that hosts static files from a local directory. And there is not that many paths. So I'm not too worried about it.

**Comment by MSP-Greg** [comment]
If you're serving static files, why does your example use `"one\ntwo\three".each_line` for the body?

Or, most would either use the below for the body or an object that responds to `to_path`?

```ruby
run lambda { |env| [200, {}, [<file contents>]] }
```

**Comment by 0x1eef** [comment]
My goal is to have a development server that supports gzip compression, and caching so that the local environment is similar to nginx. The example was an isolated reproduction for this issue. `#to_path` might be useful, I might research using it.
