### ISSUE TITLE
HTML escape of slash is not recommended by OWASP

### ISSUE THREAD

**Issue by JunichiIto** [rack/rack#2096]
`Rack::Utils.escape_html` escapes `/` to `&#x2F;`, but OWASP doesn't mention it now:

https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

So `Rack::Utils.escape_html` should escape `&<>'"` only.

## Motivation

There is no difference in the code's safety whether you leave this specification as it is or make changes. However, I spent much time investigating why `Rack::Utils.escape_html` escapes slashes and whether there is any significance to escaping them. Unnecessary escaping can confuse users like me.

Additionally, I found that `CGI.escapeHTML` only escapes the characters `'&"<>`. It also made me confused and investigate why the two similar methods have different specifications.

https://docs.ruby-lang.org/en/3.2/CGI/Util.html#method-i-escapeHTML

## Related pages

- https://github.com/rack/rack/issues/27
- https://github.com/rack/rack/commit/37ca2539c423f29337486cf0469dd49a019cfea3
- https://security.stackexchange.com/a/249423
- https://github.com/OWASP/CheatSheetSeries/commit/d7a6823db92af82da3f9538b23b03851d7556d78

**Comment by ioquatix** [comment]
I agree the security should not be impacted by this change, and making it consistent with `CGI.escapeHTML` should allow us to use that implementation for improved performance.
