### ISSUE TITLE
Rack::Lint is incompatible with Rack::BodyProxy

### ISSUE THREAD

**Issue by nunosilva800** [rack/rack#2100]
While trying to add Rack::Lint to Rails' `ActionDispatch::Executor` ([here](https://github.com/rails/rails/blob/26ceb7fc33363c488f73977fc14153dd30a38542/actionpack/test/dispatch/executor_test.rb#L163)), one of the issues that makes it quite hard is that the `Rack::Lint.new` call returns an array, where the body (3rd position), is itself a instance of `Rack::Lint::Wrapper`. 

Here's the return value of `.new`: https://github.com/rack/rack/blob/444dc8a130663159ed490f25948b73ff9b5fbba0/lib/rack/lint.rb#L88-L88

This prevents us from being able to make assertions about the response body.

Here is a demo of the issue:

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rack", "~> 3"
  gem "minitest"
end

require "rack"
require "minitest/autorun"

class CustomMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    state = false
    response = @app.call(env)
    response << ::Rack::BodyProxy.new(response.pop) { state = true }
  end
end

class TestRackLintBodyProxy < Minitest::Test
  # This has no issues, and we can call `.close` on the body after the call
  def test_body_proxy
    app = proc { [200, {}, []] }
    env = Rack::MockRequest.env_for("", {})

    app = CustomMiddleware.new(app)
    response = app.call(env)
    assert_equal 200, response[0]
    assert_equal false, response[2].closed?

    response[2].close
    assert_equal true, response[2].closed?
  end

  # This fails with `NoMethodError: undefined method `closed?' for #<Rack::Lint::Wrapper`
  def test_body_proxy_with_linter
    app = proc { [200, {}, []] }
    env = Rack::MockRequest.env_for("", {})

    app = Rack::Lint.new(CustomMiddleware.new(Rack::Lint.new(app)))
    response = app.call(env)
    assert_equal 200, response[0]
    assert_equal false, response[2].closed?

    response[2].close
    assert_equal true, response[2].closed?
  end
end
```

Is this an actual issue or expected behaviour?
We can try to submit a fix if this is indeed incorrect. Any tips welcome!

cc @skipkayhil

**Comment by skipkayhil** [comment]
Thanks for the quick response! It definitely feels a little weird that we can't call methods on the body that we know are present in a test even though they aren't part of the SPEC. I would definitely understand if this was happening in the middleware itself but I'm not convinced that the same requirement should apply in the tests.

Anyway, we'll look into updating the tests so that they only used methods that are part of the SPEC since that is what you recommend :+1:

**Comment by jeremyevans** [comment]
Note that there is no problem with what you are doing, it's just outside of SPEC, and Rack::Lint is designed solely to ensure applications/middleware/callers(servers) comply with SPEC.   If you want to operate outside of SPEC, I would recommend not using Rack::Lint.

**Comment by ioquatix** [comment]
If someone was to, say, insert a rack middleware into Rails, it's entirely valid for them to replace the response body with something that does not respond to `#closed?`. In your tests, `Rack::Lint` brings attention to situations where you might be making affordances that would later break compatibility.

**Comment by skipkayhil** [comment]
> e.g. if you want to be super pedantic, insert a copy of `Rack::Lint` between every middleware layer.

Yep, we're working on doing just that 😆 skipkayhil/rails#5

**Comment by ioquatix** [comment]
Nice, that looks amazing! Great job!

**Comment by nunosilva800** [comment]
Here's the PR for the change that prompted this discussion: https://github.com/rails/rails/pull/48825
