### ISSUE TITLE
Rack 3 breaks deeply nested hash when inside an array

### ISSUE THREAD

**Issue by Fjan** [rack/rack#2125]
I have a somewhat complex form that worked fine in Rack 2 but breaks in Rack 3. I narrowed it down to a difference in how one element is getting parsed by `normalize_params`:

```ruby
# rack 2 (correct)
qp=Rack::QueryParser.make_default(32,32)
qp.normalize_params({},'array[]hashwitharrays[A][]','0',32)
=> {"array"=>
  [#<Rack::QueryParser::Params:0x0000000110fdb590 @limit=32,
    @params={"hashwitharrays"=>#<Rack::QueryParser::Params:0x0000000110fdb4a0 @limit=32, @params={"A"=>["0"]}, @size=1>},   @size=14>]} 

# rack 3 (only parses top level)
qp=Rack::QueryParser.make_default(32)
qp.normalize_params({},'array[]hashwitharrays[A][]','0')
=> {"array"=>[#<Rack::QueryParser::Params:0x0000000107d98548 @params={"hashwitharrays[A][]"=>"0"}, @size=0>]} 
```

So rack 3 puts the entire part in the key name, while rack 2 correctly parses it recursively. If I remove the top level of nesting rack 3 does work:
```ruby
qp.normalize_params({},'hashwitharrays[A][]','0')
 => {"hashwitharrays"=>#<Rack::QueryParser::Params:0x00000001081da5e8 @params={"A"=>["0"]}, @size=0>} 
```

So this element contains an array of hashes, where one of the elements of the hash is a hash with arrays. Complex, but now that Rails 7.1 is out, which has Rack 3 as default and makes it pretty easy to construct forms like this, I think more people will run into this.

**Comment by ioquatix** [comment]
I think every subsequent key needs to be in square brackets. I’ll test it.

**Comment by ioquatix** [comment]
Using square brackets works as expected. 

```
> qp.normalize_params({},'array[]hashwitharrays[A][]','0')
=> 
{"array"=>
  [#<Rack::QueryParser::Params:0x00007f92a5749638
    @params={"hashwitharrays[A][]"=>"0"},
    @size=0>]}
irb(main):004> qp.normalize_params({},'array[][hashwitharrays][A][]','0')
=> 
{"array"=>
  [#<Rack::QueryParser::Params:0x00007f92a0d07610
    @params=
     {"hashwitharrays"=>
       #<Rack::QueryParser::Params:0x00007f92a0d07138
        @params={"A"=>["0"]},
        @size=0>},
    @size=0>]}
```

Is this sufficient?

cc @jeremyevans

**Comment by Fjan** [comment]
Ok, good, this is pretty easy to fix in my code. Those fields came from a custom helper that was apparently doing it wrong all this time, in a way that rack 2 allowed.

I'll close this, thanks @ioquatix !
