### ISSUE TITLE
How to manually decode a Rack::Session::Cookie 2023

### ISSUE THREAD

**Issue by francoataffarel** [rack/rack#2138]
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rack/session (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from decode3.rb:4:in `<main>'

**Comment by jeremyevans** [comment]
Session handling moved to the rack-session gem.  You probably need to install it or add it to your Gemfile.
