### ISSUE TITLE
Multiple writes to Rack::Response result in incorrect content-length header in Rack 3

### ISSUE THREAD

**Issue by mattbrictson** [rack/rack#2148]
## Problem

After upgrading to Rack 3, I found that `Rack::Response` generates an incorrect content-length header when:

- it is constructed with an empty array for the body, and
- `write` is called multiple times

Here is a simple reproduction script:

```ruby
require "rack"

status = 200
headers = {}
response = Rack::Response.new([], status, headers)

# Write 11 total bytes
response.write "hello"
response.write "world"
response.write "!"

# Resulting content-length should be 11, but is 26
response.headers
# => {"content-length"=>"26"}
```

## Underlying cause

When `Rack::Response` is constructed with an empty array, it sets this internal state:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L82

This causes the value of `@length` to accumulate on every call to `Rack::Response#write`:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L317-L323

When `chunked?` is `false`, `@length` is incremented yet again, and then emitted as a content-length header:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L348-L350

The result is that the content-length value is too large, and the error gets larger on every call to `write`.

**Comment by ioquatix** [comment]
Without digging into it, it appears that the latter `@length += chunk.bytesize` is incorrect. Do you think removing it is the correct course of action?

**Comment by mattbrictson** [comment]
I'm actually not sure I understand the intention of the existing code, in particular why `@buffered` is set to `nil` in the constructor and lazily initialized later. Since I may be missing the point of `@buffered`, take what follows with a grain of salt.

The problem I see is that there is a missing assignment of `@buffered` in one of the conditional branches within `buffered_body!`.

Abbreviated, the code currently looks like this:

```ruby
if @buffered.nil?
  if @body.is_a?(Array)
    # ...
    # ⚠️ @buffered is not set in this branch
  elsif @body.respond_to?(:each)
    # ...
    @buffered = true
  else
    @buffered = false
  end
end
```

It seems like the point of this code was to lazily init `@buffered` to true or false, but currently that isn't happening in the first branch. So I think the fix is to add `@buffered = true`, like this:

```diff
--- lib/rack/response.rb
+++ lib/rack/response.rb
@@ -318,12 +318,14 @@ module Rack
           if @body.is_a?(Array)
             # The user supplied body was an array:
             @body = @body.compact
             @body.each do |part|
               @length += part.to_s.bytesize
             end
+
+            @buffered = true
           elsif @body.respond_to?(:each)
             # Turn the user supplied body into a buffered array:
             body = @body
             @body = Array.new
 
             body.each do |part|
```

With this one-line change, I get the correct content-length result when running my reproduction script.

**Comment by mattbrictson** [comment]
OK, I've opened PR #2150
