### ISSUE TITLE
RACK_INPUT not rewound on form data

### ISSUE THREAD

**Issue by dblock** [rack/rack#2152]
Coming from https://github.com/slack-ruby/slack-ruby-client/issues/506, it looks like Rack 2.x called `rewind` on `RACK_INPUT` for form data.

In 2.x it used to call `.rewind` explicitly after reading the form data.

https://github.com/rack/rack/blob/2-2-stable/lib/rack/request.rb#L456

And it no longer does in 3.x.

https://github.com/rack/rack/blob/e50b72a9b2400cbe3b25f3619926f306796503ac/lib/rack/request.rb#L523

This causes anyone accessing `http_request.body` to get an empty value.

Was this by design? I can add a test/fix if it's not.

**Comment by jeremyevans** [comment]
Yes, this is expected, and mentioned in the upgrade guide: https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#rackinput-is-no-longer-required-to-be-rewindable.  You can use Rack::RewindableInput::Middleware if you would like the request body to be rewindable, as it was in Rack 2.

**Comment by dblock** [comment]
Thanks, should have checked, my bad.
