### ISSUE TITLE
Upgrading from rack ~> 2.2 to >= 3.0.0 required me to do a new request.body.rewind before a request.body.read

### ISSUE THREAD

**Issue by JonJagger** [rack/rack#2155]
Hi
I use Ruby in https://cyber-dojo.org an open-source web app for practising TDD with all £$ proceeds going to charity.
Sinatra + rack is great :-) So first off - a big thank you.

The cyber-dojo creator repo is one of cyber-dojo's dockerized microservices.
I was previously using a sinatra 3.2.0 base-image using rack ~> 2.2 and in one place I do a `request.body.read` 
https://gitlab.com/cyber-dojo/creator/-/blob/762ba5d23423a4646330626497167668ca58da6e/app/app_base.rb#L73

I upgraded to a new sinatra 4.0.0 base-image using rack >= 3.0.0 (to fix a snyk vulnerability) and I found that the
call to `request.body.read` always gave me an empty body. And so naturally things stopped working.
On a hunch I added a call to `request.body.rewind` before that call, and all is now working again.
https://gitlab.com/cyber-dojo/creator/-/blob/0c3181dfe6c95354531131e76c038bf75ba26baf/app/app_base.rb#L73

So I speculate that somewhere there is now code that previously did a rewind after a read but that is no longer doing the rewind. Or a new call to read without a following rewind. Don't know if this qualifies as a bug. But it was a surprise.

Two Gemfile.lock's, for the before and after are here:
https://gitlab.com/cyber-dojo/creator/-/tree/0c3181dfe6c95354531131e76c038bf75ba26baf/docs/debug

Thanks again

**Comment by jeremyevans** [comment]
This is expected, see the upgrade guide: https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#rackinput-is-no-longer-required-to-be-rewindable

**Comment by JonJagger** [comment]
Roger that. Thanks for the quick response.
