### ISSUE TITLE
Request for release - EOFError on empty multipart request 

### ISSUE THREAD

**Issue by JoeDupuis** [rack/rack#2163]
Hi, 
I was investigating a [Rails issue](https://github.com/rails/rails/issues/51292). 

Turns out there is already a fix for it on both `2-2-stable` and `main` (but not `3-0-stable`)
https://github.com/rack/rack/pull/2104 (main)
https://github.com/rack/rack/pull/2121 (2-2-stable)

These were excluded from the last releases.  I was wondering if we could cut a release of both 2-2 and 3-0 including this fix and/or what is the policy around releases. Apologies if this is indicated somewhere and I missed it.

As a temporary fix for the Rails issue, I'll tell the user to point their Gemfile to the Rack Github repo. 

I can open a PR to port the #2104 to `3-0-stable` if needed. 
Thank you!

**Comment by ioquatix** [comment]
Can you please open a PR to 3-0-stable and I'll handle the releases once merged.

**Comment by JoeDupuis** [comment]
Awesome! Thank you! Here's the PR #2164

**Comment by ioquatix** [comment]
This is already released as `v2.2.8.1` and I've just released `v3.0.10` which includes the backport.

**Comment by JoeDupuis** [comment]
@ioquatix `v2.2.8.1` was released after the backport, but it looks like it excluded fix. I tried to compare the files from a fresh rubygems download to the [2-0-stable backport PR](https://github.com/rack/rack/pull/2121) and it doesn't look like it made the release.

**Comment by ioquatix** [comment]
Thanks for that clarification. Yeah that's super weird because the commit history says otherwise. Okay, I'll cut a new release.

**Comment by ioquatix** [comment]
Okay, I just released v2.2.9 with this change.
