### ISSUE TITLE
Deprecation should note how to fix

### ISSUE THREAD

**Issue by mperham** [rack/rack#2172]
https://github.com/rack/rack/blob/d3c545e69d58e588622bcf9b1ab9f971b8a02112/lib/rack/response.rb#L35-L39

Please add "use `headers` instead" to the user message so the user knows how to fix the deprecation.

**Comment by ioquatix** [comment]
Are you able to submit a PR? Thanks!

**Comment by mperham** [comment]
@ioquatix See #2173

**Comment by ioquatix** [comment]
Thanks Mike! Although small, this is a great improvement. Feel free to submit more PRs :)
