### ISSUE TITLE
`Rack::Logger` depends on `logger` which will be bundled in Ruby 3.5

### ISSUE THREAD

**Issue by Earlopain** [rack/rack#2190]
You know the drill. 3.4 will warn, 3.5 will error: https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c

The logger interface is specced, so perhaps you can do something with that. Or just to the gemspec it goes.

**Comment by ioquatix** [comment]
My gut feeling is I think we should drop our dependency on `logger` and just write our own shim, logging to `stderr`. It's okay if it's simple, it's supposed to be.

**Comment by ioquatix** [comment]
@jeremyevans what do you think about moving `Rack::Logger` to `rack-contrib` and leaving it with an optional dependency on the `logger` gem?

**Comment by jeremyevans** [comment]
I'm OK with moving Rack::Logger to rack-contrib.
