### ISSUE TITLE
MockRequest can't handle an empty cookie anymore

### ISSUE THREAD

**Issue by wynksaiddestroy** [rack/rack#2201]
Executing
```ruby
Rack::MockRequest.new(->(env) { [200, { "Set-Cookie" => "" }, [""]] }).get("")
```
will fail with
> NoMethodError: undefined method `split' for nil
from /Users/foobar/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.0/lib/rack/mock_response.rb:101:in `identify_cookie_attributes'

In earlier versions (<= 3.0.11) this used to work.

**Comment by ioquatix** [comment]
Are you able to submit a PR? Thanks :)

**Comment by wynksaiddestroy** [comment]
> Are you able to submit a PR? Thanks :)

Give me a few hours 👍
