### ISSUE TITLE
rackup package v1 release **entirely broken** (missing lots of files)

### ISSUE THREAD

**Issue by joshgoebel** [rack/rack#2251]
https://github.com/rack/rackup/issues/13

No one is responding on that repository - is this package no longer maintained by the rack team?   _This issue seems to go back to Dec of last year._

Sorry for cross-post, but this is affecting a lot of our active projects.  I think a few of us would be HAPPY to help with a fix to get a working 1.0.1 or 1.1.0 released, IF we could make contact with someone on the rack team willing to do the review and final merge, etc.

Can anyone help?  **Thanks!**

**Comment by ioquatix** [comment]
Thanks for the notification, I have replied on the original issue.
