### ISSUE TITLE
[SECURITY] Responsible Disclosure

### ISSUE THREAD

**Issue by RootUp** [rack/rack#2258]
Hey there team, 

I have emailed a security advisory to tenderlove[at]ruby-lang[dot]org but haven't heard anything yet it's been 8 days. Hence, based on the security policy creating an issue here so maintainers can have a look.

Ping @tenderlove 

Thanks,

**Comment by tenderlove** [comment]
Hi @RootUp,

Sorry, for some reason your email went in to my spam box.  I'm taking a look now 😄
