### ISSUE TITLE
Cannot test no content properly with mock response body definition

### ISSUE THREAD

**Issue by fosrias** [rack/rack#2264]
A proper 204 response will have a nil body. However, the implementation in MockResponse turns this into an empty string and so you cannot use the #body method to actually properly test a no content API.

https://github.com/rack/rack/blob/v3.1.8/lib/rack/mock_response.rb#L60

This should return nil if there is no buffered_body and there is a 204 status. 

Happy to open a PR to fix this, but wanted to get some feedback first.

**Comment by ioquatix** [comment]
That seems reasonable to me.

**Comment by jeremyevans** [comment]
I'm not sure I agree with `A proper 204 response will have a nil body`.  The RFCs aren't going to discuss `nil`, and using an empty string seems consistent with what the standards require.  Using any non empty string would be wrong, but I don't see why an empty string would be considered wrong.

Can you explain why you cannot actually properly test with the current API?  What would be the problem with testing that the body is empty, compared to testing that is is nil?

Changing this seems like it would break backwards compatibility for existing code that expects an empty string to be returned.

**Comment by fosrias** [comment]
@jeremyevans Per RFC [7231](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5):

> A 204 response is terminated by the first empty line after the header
   fields because it cannot contain a message body.
   
As such, having an empty string in the response after the header would be non-conforming.
 
In ruby, I would expect nothing there to translate to `nil`, not an empty string, particularly given there also should be no `Content-Type` type header to give any directive on the empty string.
 
Using a ruby testing library that is particularly strict on this and expects `nil` for a 204. 
 
That being said, I am not sure the impact on backwards compatibility is worth making this change. Likely better to address this in the testing library.
