### ISSUE TITLE
max_key_space breaking valid form submissions

### ISSUE THREAD

**Issue by jgadbois** [rack/rack#318]
I'm posting a large form of data in my Rails app and the addition of max_key_space in lib/rack/utils.rb is causing the server to error out.  Are there any workarounds?

**Comment by TangMonk** [comment]
I set `Rack::Utils.key_space_limit = 2621440000123123123123123123`, but still not works and throw the same error

**Comment by jrochkind** [comment]
The README docs for the key_space_limit currently say:

> The default number of bytes to allow all parameters keys in a given parameter hash to take up. Does not affect nested parameter hashes, so doesn't actually prevent an attacker from using more than this many bytes for parameter keys.

**so doesn't actually prevent an attacker from using more than this many bytes for parameter keys.**

This makes it sound to me like this isn't doing anything useful, it's NOT actually preventing any kind of DOS attack if the attacker is smart enough to use nested hashes? 

Could it be just getting in the way of people without actually providing any meaningful protection, would it make sense to consider removing it?

**Comment by jrochkind** [comment]
Actually, i'm not sure about any of that now. More at https://github.com/rack/rack/pull/1487
