### ISSUE TITLE
Changing CommonLogger format?

### ISSUE THREAD

**Issue by eterps** [rack/rack#328]
Is there a reason why the CommonLogger format is defined as a constant? I would like to configure the log format.

lib/rack/commonlogger.rb:
...
FORMAT = %{%s - %s [%s] "%s %s%s %s" %d %s %0.4f\n}
...

**Comment by sysout** [comment]
Anyone knows how to customize the format? I want to log the http host header as well. 
I am using Puma and Sinatra, but I don't know how to change the format without monkey patching.
I know in Rails we can use a lambda in Application.configure to change the config.log_tags.
