### ISSUE TITLE
invalid %-encoding error in application for malformed uri

### ISSUE THREAD

**Issue by StefanH** [rack/rack#337]
When you go to, for example, `/foo?%9g` in my (rails) app, rack raises an `ArgumentError: invalid %-encoding`. I would expect to get a `400 Bad request` back.

The offending line is:

``` ruby
  URI.decode_www_form_component(s, encoding)
```

in rack/utils.rb line 39, wich tries to decode this invalid url component.

I'm using Nginx with passenger as a webserver. I've tried Rack versions 1.4.1 and 1.3.6.

Interestingly, when I go to `/%9g` (i.e. use `%9g` as part of the URI instead of passing it as a parameter), I immediately get a `400 Bad request` from nginx. Webrick returns a 400 either way. I'm not sure if nginx is correct in ignoring the invalid URI component and passing this request off to the app, but it would be nice if rack could handle it either way.

**Comment by md5** [comment]
Would there be any chance of getting a patch like the following into Rack?

```patch
diff --git a/lib/rack/utils.rb b/lib/rack/utils.rb
index d541608..e0a528c 100644
--- a/lib/rack/utils.rb
+++ b/lib/rack/utils.rb
@@ -10,6 +10,8 @@ module Rack
   # Rack::Utils contains a grab-bag of useful methods for writing web
   # applications adopted from all kinds of Ruby libraries.
 
+  class InvalidPercentEncodingError < ArgumentError; end
+
   module Utils
     ParameterTypeError = QueryParser::ParameterTypeError
     InvalidParameterError = QueryParser::InvalidParameterError
@@ -48,7 +50,11 @@ module Rack
     # Unescapes a URI escaped string with +encoding+. +encoding+ will be the
     # target encoding of the string returned, and it defaults to UTF-8
     def unescape(s, encoding = Encoding::UTF_8)
-      URI.decode_www_form_component(s, encoding)
+      begin
+        URI.decode_www_form_component(s, encoding)
+      rescue ArgumentError
+        raise InvalidPercentEncodingError, $!.message
+      end
     end
     module_function :unescape
 
```

That would make possible to do a `rescue_from "InvalidPercentEncodingError"` in Rails cleanly instead of having to poke around to see if it's the right kind of `ArgumentError`.

**Comment by raggi** [comment]
Why not propose this to MRI?

**Comment by md5** [comment]
@raggi I did consider that.

All the custom errors in `URI::*` are child classes of `URI::Error` which itself descends from `StandardError`. If I were to propose changing `decode_www_form_component`, I would either have to introduce an error class in that module that doesn't descend from `URI::Error` and instead descends from `ArgumentError` or possibly break everyone's code that was used to rescuing `ArgumentError`.

**Comment by AlexWayfer** [comment]
> Puma, Thin, Webrick, Unicorn all return a 400 Bad Request before this hits Rack.

No.

> This is a rack / rails bug, not puma.

https://github.com/puma/puma/issues/500#issuecomment-48829171

:neutral_face:

**Comment by array42** [comment]
Post XML Body with  Comment also breaks for Rails 5.

**Comment by raggi** [comment]
I made the recommendation when we switched this out from our own parser to
the stdlib one, that the stdlib needs to add a distinct error for this
case. Once it does (such as UriEncodingError) then we can catch that in an
appropriate place in an appropriate middleware and return 400. Before the
error can be distinguished the best we have is a 500.

Note: rack doesn't currently ship a request validating middlware with
production performance characteristics, only lint, which you often don't
want in production. We could add one, but frameworks seem to have taken
this on just fine, with only a few challenges such as this.

**Comment by AlexWayfer** [comment]
> but frameworks seem to have taken this on just fine

Puma still no. We're getting low-level errors.

In production:

```
An unhandled lowlevel error occurred. The application logs may have details.
```

In development:

```
Puma caught this error: invalid %-encoding (%9g) (Rack::QueryParser::InvalidParameterError)
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/query_parser.rb:72:in `rescue in parse_nested_query'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/query_parser.rb:60:in `parse_nested_query'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/request.rb:468:in `parse_query'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/request.rb:319:in `GET'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/request.rb:358:in `params'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/request.rb:20:in `params'
```

**Comment by raggi** [comment]
That is correct behavior from puma. You will want to validate request
parameters in your application or catch this error from rack request.

**Comment by AlexWayfer** [comment]
> You will want to validate request parameters in your application or catch this error from rack request.

But how? I even can't take `Rack::Request#params` for validating. Or where should I catch this error?

**Comment by bf4** [comment]
Easy middleware from this thread years ago https://github.com/rack/rack/issues/337#comment-48555831

**Comment by dentarg** [comment]
The link in the above comment didn't work for me (`https://github.com/rack/rack/issues/337#comment-48555831`), I think @bf4 meant to link to `https://github.com/rack/rack/issues/337#issuecomment-48555831`

So here it is: https://github.com/rack/rack/issues/337#issuecomment-48555831

**Comment by AlexWayfer** [comment]
@bf4, @dentarg: thank you.
