### ISSUE TITLE
Rack::Chunked - how to get started?

### ISSUE THREAD

**Issue by phillipp** [rack/rack#396]
Hi!
I love to use Rack, but I don't understand whats going on here:

I have this application that should send the response chunked (long-running api request transferring lots of data that takes time to generate):

``` ruby
require 'backup_gateway'

use Rack::Chunked

if ENV["RACK_ENV"] == "development"
  use Rack::Reloader, 0
end

run BackupGateway.new
```

``` ruby
require 'backup_authentication'

class BackupGateway
  def initialize
    @authentication = BackupAuthentication.new
  end

  class TestPage
    def each
      yield "test"
      sleep 2
      yield "test2"
      sleep 2
    end
  end

  def call(env)
    [200, {"Content-Type" => "text/plain"}, TestPage.new]
  end
end
```

The curl output is:

```
HTTP/1.1 200 OK 
Content-Type: text/plain
Transfer-Encoding: chunked
Server: WEBrick/1.3.1 (Ruby/1.9.3/2011-10-30)
Date: Fri, 01 Jun 2012 16:58:27 GMT
Content-Length: 24
Connection: Keep-Alive

testtest2
```

But curl and/or Firefox waits until the request is completed. Is this a WEBrick issue (is chunked transfer enabled on webrick by default?) or is there something else wrong?

Thanks for the support!

**Comment by perlun** [comment]
@raggi - age-old request: has this been fixed with Webrick and Thin nowadays?

**Comment by raggi** [comment]
Some patches were dropped that should have helped webrick. In reality though both of these webservers are pretty inferior to puma for hosting rack apps. Use of the chunked and content-length middleware should be discouraged in general.

The current maintainer is @tenderlove

**Comment by tenderlove** [comment]
I think we could fix this for WEBrick, it just seems really hacky.  This patch makes @raggi's gist work mostly as expected:

```diff
diff --git a/lib/rack/handler/webrick.rb b/lib/rack/handler/webrick.rb
index d0fcd21..637d25b 100644
--- a/lib/rack/handler/webrick.rb
+++ b/lib/rack/handler/webrick.rb
@@ -27,6 +27,7 @@ module Rack
         default_host = environment == 'development' ? 'localhost' : nil
 
         options[:BindAddress] = options.delete(:Host) || default_host
+        options[:OutputBufferSize] = 5
         options[:Port] ||= 8080
         @server = ::WEBrick::HTTPServer.new(options)
         @server.mount "/", Rack::Handler::WEBrick, app
@@ -107,14 +108,37 @@ module Rack
           elsif body.respond_to?(:to_path)
             res.body = ::File.open(body.to_path, 'rb')
           else
-            body.each { |part|
-              res.body << part
-            }
+            if chunked?(res)
+              rd, wr = IO.pipe
+              rd.sync = true
+              wr.sync = true
+              res.body = rd
+              res.chunked = true
+              Thread.new do
+                begin
+                  body.each { |part|
+                    wr.write part
+                  }
+                ensure
+                  wr.close
+                end
+              end
+            else
+              body.each { |part|
+                res.body << part
+              }
+            end
           end
         ensure
           body.close  if body.respond_to? :close
         end
       end
+
+      private
+
+      def chunked?(response)
+        response[TRANSFER_ENCODING] == "chunked"
+      end
     end
   end
 end
```

Off the top of my head, problems with the patch are: 1) Creating two new file descriptors per response (maybe that's ok), 2) creating a new thread per response (maybe that's OK too), 3) setting the output buffer to a very tiny value.  I guess we have to pick some value for the size, but I'm not sure what size fits most people, and we would have to educate people about that setting.  I'm not totally sure if doing this is worth while when you can use Puma and it just works out of the box.  🤷‍♀️

/cc @eileencodes @jeremy

**Comment by raggi** [comment]
https://github.com/ruby/webrick/blob/master/lib/webrick/httpresponse.rb#L401 :(

**Comment by raggi** [comment]
@tenderlove it requires a monkey patch, but the following works with mostly puma style semantics: https://github.com/rack/rack/commit/0dd6fdec4ad10e1c86c1ba740e6163f66a0cba35

**Comment by tenderlove** [comment]
Ah yep, we could do that.  Still not sure if doing this is worth while.

**Comment by perlun** [comment]
> Use of the chunked and content-length middleware should be discouraged in general.

That's an interesting side note. What are the reasons for this? Apps should be more explicit with what they return instead of relying on middleware to do "magic tricks" for them? Or are you just talking about the (agreeably somewhat odd) _combination_ of the Chunked and ContentLength middlewares?

**Comment by raggi** [comment]
The decision about whether to perform chunked encoding, or close the socket, or to compute content length depends on factors that cannot be entirely passed to middleware. Specifically you cannot do pipelining correctly and support all valid responses using the middleware pattern. Servers need to compute what is possible and what the app (including middleware) have forced on them and operate accordingly. Using middleware for this was a mistake from the outset.

**Comment by perlun** [comment]
@raggi Thanks for that. Helpful both for me and perhaps to others who happen to find this issue as well.
