### ISSUE TITLE
[response].flatten causes infinite loop

### ISSUE THREAD

**Issue by dchelimsky** [rack/rack#419]
- `Rack::Response#finish` is aliased with `to_ary` [1]
- `Rack::Response#finish` returns an array including `self`when the response code is anything other than 204, 205, 304 [2]

The result is an infinite loop if the result of `app.call(env)` (assigned to `response` in Rails' testing framework) is included in an array that is flattened. The reason is that `Array#flatten` invokes `to_ary` on each element that responds to `to_ary`, then does the same to the contents of the result of `to_ary`, and so on.

Because `self` is in the array returned by `to_ary`, it gets `to_ary` invoked and returns the same array, including `self`, which then gets `to_ary` invoked on it, which returns the same array, including `self`, and so on.

[1] https://github.com/rack/rack/blob/ab67e70d82911c0c86dce737c7064d0bd6daf3d4/lib/rack/response.rb#L83
[2] https://github.com/rack/rack/blob/ab67e70d82911c0c86dce737c7064d0bd6daf3d4/lib/rack/response.rb#L79

**Comment by ioquatix** [comment]
@jeremy we will implement your solution.
