### ISSUE TITLE
ShowExceptions should filter known sensitive keys from env

### ISSUE THREAD

**Issue by skimbrel** [rack/rack#420]
A warning that this "could" happen really isn't sufficient, particularly when using this in conjunction with other Rack middleware like Rack::Session::Cookie _will_ result in leakage of the session cookie secret.

For reference, here's how Django handles its debug page: https://github.com/django/django/blob/master/django/views/debug.py
Note the HIDDEN_SETTINGS variable and the use of cleanse_setting() to prevent configuration of Django built-ins from leaking.

To reproduce: enable ShowExceptions and Session::Cookie, then do anything to a Rack-powered application that causes it to crash and show the ShowExceptions page. Witness the dumping of all of env, including rack.session.options and its :secret/:oldsecret values.

**Comment by frankel** [comment]
@dleve123 I encounter the exact same problem. How do you solve this later?

**Comment by frankel** [comment]
@dleve123 In my case, I found the answer, http://manpages.ubuntu.com/manpages/quantal/man1/unicorn.1.html Search "RACK_ENV" and "Rack::ShowExceptions"
