### ISSUE TITLE
nil error in merging get and post data

### ISSUE THREAD

**Issue by michaeleconomy** [rack/rack#430]
I'm seeing this error on a very small percentage of our requests  (like 25 per day), i don't have very good data, but it could be related to multipart posts.

TypeError: can't convert nil into Hash

[GEM_ROOT]/gems/rack-1.4.1/lib/rack/request.rb:221:in `merge'
[GEM_ROOT]/gems/rack-1.4.1/lib/rack/request.rb:221:in`params'

Any idea whats up?

Running RoR 3.2.8, unicorn 4.3.1.

**Comment by volx7577** [comment]
Did anyone ever find a workaround to this issue? I'm getting it using unicorn and new relic:

    
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb:221 :in `merge`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb:221 :in `params`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/jquery-fileupload-rails-0.4.1/lib/jquery/fileupload/rails/middleware.rb:32 :in `iframe_transport?`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/jquery-fileupload-rails-0.4.1/lib/jquery/fileupload/rails/middleware.rb:17 :in `_call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/jquery-fileupload-rails-0.4.1/lib/jquery/fileupload/rails/middleware.rb:10 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/error_collector.rb:50 :in `traced_call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/agent_hooks.rb:26 :in `traced_call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/browser_monitoring.rb:23 :in `traced_call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-ssl-enforcer-0.2.8/lib/rack/ssl-enforcer.rb:52 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:35 :in `block in call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34 :in `catch`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/best_standards_support.rb:17 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/head.rb:14 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/params_parser.rb:21 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/flash.rb:242 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210 :in `context`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/cookies.rb:341 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/query_cache.rb:64 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:479 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:28 :in `block in call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405 :in `_run__3158766179523798800__call__1830933626558231124__callbacks`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405 :in `__run_callback`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385 :in `_run_call_callbacks`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81 :in `run_callbacks`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:27 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/remote_ip.rb:31 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/debug_exceptions.rb:16 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/show_exceptions.rb:56 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:32 :in `call_app`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:16 :in `block in call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/tagged_logging.rb:22 :in `tagged`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:16 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/request_id.rb:22 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/cache/strategy/local_cache.rb:72 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/static.rb:63 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136 :in `forward`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143 :in `pass`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155 :in `invalidate`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71 :in `call!`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-timeout-0.0.4/lib/rack/timeout.rb:16 :in `block in call`
    [PROJECT_ROOT]/vendor/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:69 :in `timeout`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-timeout-0.0.4/lib/rack/timeout.rb:16 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/engine.rb:484 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/application.rb:231 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/railtie/configurable.rb:30 :in `method_missing`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 :in `call`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576 :in `process_client`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670 :in `worker_loop`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525 :in `spawn_missing_workers`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140 :in `start`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/bin/unicorn:126 :in `<top (required)>`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/bin/unicorn:23 :in `load`
    [PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/bin/unicorn:23 :in `<main>`


and here's my env:

    "REQUEST_METHOD" => "POST",
  "SERVER_PROTOCOL" => "HTTP/1.1",
  "HTTP_VERSION" => "HTTP/1.1",
  "HTTP_CONNECTION" => "close",
  "HTTP_ACCEPT" => "*/*",
  "HTTP_X_CSRF_TOKEN" => "S4avD6tueTXTai3j2STC8rW22VHu61Oy481CDoVTYH8=",
  "HTTP_X_REQUESTED_WITH" => "XMLHttpRequest",
  "CONTENT_TYPE" => "multipart/form-data; boundary=---------------------------7df33c3b30576",
  "HTTP_ACCEPT_LANGUAGE" => "en-US",
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate",
  "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; NP09; NP09; MAAU; rv:11.0) like Gecko",
  "HTTP_DNT" => "1",
  "HTTP_CACHE_CONTROL" => "no-cache",
  "HTTP_X_REQUEST_ID" => "82952cd0-e783-4c70-8213-431c90e331bf",
  "HTTP_X_FORWARDED_FOR" => "204.111.22.5",
  "HTTP_X_FORWARDED_PROTO" => "https",
  "HTTP_X_FORWARDED_PORT" => "443",
  "HTTP_VIA" => "1.1 vegur",
  "HTTP_CONNECT_TIME" => "2",
  "HTTP_X_REQUEST_START" => "1424193899923",
  "HTTP_TOTAL_ROUTE_TIME" => "0",
  "CONTENT_LENGTH" => "3675",
  "SCRIPT_NAME" => "",
  "SERVER_SOFTWARE" => "Unicorn 4.8.3"


Same as others, I can't reproduce this locally, it only occurs in production.

**Comment by zimbatm** [comment]
Make sure that rack is v1.5.2 or more

**Comment by volx7577** [comment]
Ok, will do. Is this a known fix or just a good idea moving forward?

**Comment by zimbatm** [comment]
Read the thread. #561 is a fix to the issue, the check in the history after which version is has been merged
