### ISSUE TITLE
SPEC does not require `to_hash` on `rack.session` interface

### ISSUE THREAD

**Issue by pmahoney** [rack/rack#461]
I encountered this in Rack 1.3.6, but it seems to be also present on master.

The SPEC claims `rack.session` must implement:
- `store(key, value) (aliased as []=)`
- `fetch(key, default = nil) (aliased as [])`
- `delete(key)`
- `clear`

But [session/abstract/id.rb:238](https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L238) expects to be able to `merge!` a `rack.session` into a `SessionHash`.  I was able to work around this by having my `rack.session` also implement `to_hash`.

Either I am misunderstanding something, or SPEC should be updated to also require `to_hash`.

**Comment by ioquatix** [comment]
This needs to be reviewed.

**Comment by jeremyevans** [comment]
I agree with @raggi that `rack.session` needs to implement `to_hash`.  Effectively this is required by rack's current session support, so it should be added to SPEC/Lint.  I'll submit a pull request for this.
