### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by Electron-libre** [rack/rack#589]
It seems that in some cicumstances rack request try to set some keys on the @env while another stack iterate over it.

I am wondering which piece of code is iterating over the @env variable. It happens while using session_off ( https://github.com/kares/session_off ) gem in conjunction with airbrake ( https://github.com/airbrake/airbrake ). Rails 4 and Ruby 2.0.0-p247

Here is the corresponding pry session :

```
From: /home/cedric/.rvm/gems/ruby-2.0.0-p247@barakafrites/gems/rack-1.5.2/lib/rack/request.rb @ line 291 Rack::Request#cookies:

    290: def cookies
 => 291:   hash   = @env["rack.request.cookie_hash"] ||= {}
    292:   string = @env["HTTP_COOKIE"]
    293: 
    294:   return hash if string == @env["rack.request.cookie_string"]
    295:   hash.clear
    296: 
    297:   # According to RFC 2109:
    298:   #   If multiple cookies satisfy the criteria above, they are ordered in
    299:   #   the Cookie header such that those with more specific Path attributes
    300:   #   precede those with less specific.  Ordering with respect to other
    301:   #   attributes (e.g., Domain) is unspecified.
    302:   cookies = Utils.parse_query(string, ';,') { |s| Rack::Utils.unescape(s) rescue s }
    303:   cookies.each { |k,v| hash[k] = Array === v ? v.first : v }
    304:   @env["rack.request.cookie_string"] = string
    305:   hash
    306: end

hash   = @env["rack.request.cookie_hash"] ||= {}
RuntimeError: can't add a new key into hash during iteration
from (pry):1:in `[]='
```

I am wondering this would not prevent any race condition over the @env variable.

I managed to fix this specific issue duplicating the env hash to modify , and then replace it once modified.

I'll provide a pull request as soon as I ensure I did not broke anything.

**Comment by zinosama** [comment]
i ran into this 'can't add new key into hash' error in a production environment recently. it appears to be referring to the env object but i don't understand what you mean by 'rack request try to set some keys on the @env while another stack iterate over it' - the request objects should be thread-local, which means unless something is intentionally opening a new thread from the current thread and mutating the hash concurrently from that new thread, the code above shouldn't cause any problem. Was airbrake mutating the request object in a different thread? Looking for inspiration to resolve my issue ..
