### ISSUE TITLE
Expect / Continue not supported by Rack

### ISSUE THREAD

**Issue by rkh** [rack/rack#629]
Tried to implement a simple app imitating S3, but failed at that point.

**Comment by jeremyevans** [comment]
As the Unicorn approach shows, rack supports Expect/Continue fine, it just requires servers to call back into Rack after the 100 response is sent to the client.  With Unicorn's approach, the same environment is reused, just the HTTP_EXPECT entry is deleted, which should allow for state handling via the environment.  The first request can set the state in the request environment, which will be preserved when the second request is made.

So this doesn't appear to be a rack issue, it appears to be a server issue.  I recommend other servers handle the issue similar to how Unicorn handles it.

**Comment by raggi** [comment]
Sorry for the flyby comment but maybe this should get added to SPEC?

**Comment by jeremyevans** [comment]
We could probably add something to SPEC, but I don't think we could enforce this with Lint, since Lint does not address this behavior.

**Comment by ioquatix** [comment]
@raggi pleasd make a PR if you have some concrete ideas.
