### ISSUE TITLE
TypeError: no implicit conversion of nil into Hash

### ISSUE THREAD

**Issue by bcackerman** [rack/rack#653]
I receive this error `TypeError: no implicit conversion of nil into Hash` all over my app at random times.  Not sure what the issue is.  

Backtrace
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/request.rb:221 in "merge"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/request.rb:221 in "params"
/vendor/bundle/ruby/2.0.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:92 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/deflater.rb:13 in "call"
/vendor/bundle/ruby/2.0.0/gems/client_side_validations-3.2.6/lib/client_side_validations/middleware.rb:17 in "call"
/vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35 in "block in call"
/vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34 in "catch"
/vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:35 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210 in "context"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341 in "call"
/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64 in "call"
/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28 in "block in call"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405 in "_run__2671751439356286223__call__4251604582201843529__callbacks"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405 in "__run_callback"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385 in "_run_call_callbacks"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81 in "run_callbacks"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56 in "call"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/rack/logger.rb:32 in "call_app"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/rack/logger.rb:16 in "block in call"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22 in "tagged"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/rack/logger.rb:16 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17 in "call"
/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72 in "call"
/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-ssl-1.3.3/lib/rack/ssl.rb:27 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-canonical-host-0.0.8/lib/rack/canonical_host.rb:18 in "call"
/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136 in "forward"
/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:143 in "pass"
/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:155 in "invalidate"
/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:71 in "call!"
/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51 in "call"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:484 in "call"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:231 in "call"
/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30 in "method_missing"
/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:571 in "process_client"
/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:658 in "worker_loop"
/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.1.188/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22 in "call"
/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.1.188/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22 in "block (4 levels) in <top (required)>"
/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:520 in "spawn_missing_workers"
/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:140 in "start"
/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.0/bin/unicorn:126 in "<top (required)>"
/vendor/bundle/ruby/2.0.0/bin/unicorn:23 in "load"
/vendor/bundle/ruby/2.0.0/bin/unicorn:23 in "<main>"

**Comment by bcackerman** [comment]
@outerim did you ever find a solution?

**Comment by XBeg9** [comment]
Just got the issue, any updates?

**Comment by bcackerman** [comment]
@raggi how would you recommend handling it and returning a 400?

**Comment by spiderpug** [comment]
We also receive this error frequently now. This is how the typical request looks like:

    {
      "REMOTE_ADDR" => "127.0.0.1",
      "REQUEST_METHOD" => "GET",
      "REQUEST_PATH" => "/stuff",
      "PATH_INFO" => "/stuff",
      "REQUEST_URI" => "/stuff",
      "SERVER_PROTOCOL" => "HTTP/1.0",
      "HTTP_VERSION" => "HTTP/1.0",
      "HTTP_X_FORWARDED_FOR" => "1.1.1.1, 2.2.2.2",
      "HTTP_HOST" => "www.mydomain.com",
      "HTTP_CONNECTION" => "close",
      "HTTP_ACCEPT" => "*/*",
      "HTTP_ACCEPT_ENCODING" => "gzip, deflate",
      "CONTENT_TYPE" => "multipart/form-data; boundary=eccf832e37f04a7db470ff456548f00d",
      "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.1; rv:34.0) Gecko/20100101 Firefox/34.0",
      
      "ORIGINAL_FULLPATH" => "/stuff",
      "ORIGINAL_SCRIPT_NAME" => ""
    }

Please note that is acts like a `GET` request but is passing a `multipart/form-data` content type.

I'm also not sure how to catch this and return code 400, because it is just a `TypeError` in Rack 1.5.5.
