### ISSUE TITLE
Rack::BodyProxy with Rack::ContentLength middleware

### ISSUE THREAD

**Issue by martinotten** [rack/rack#734]
I ran into this issue using the Rack::ContentLength middleware with Rails 4.1.5. The middleware checks  body.respond_to?(:to_ary) before calculating the Content-Length header. This fails if the body is a Rack::BodyProxy. The line has been added in 5b251a986962f3577e14c01a698fab9dd21383ba to fix https://github.com/rack/rack/issues/419 . Is there another solution for 419 or should the middleware be changed? It seems there is also no spec for this.

**Comment by jeremyevans** [comment]
`Rack::Response#to_ary` was removed in 72959ebc2f300f3b2ccb7ae2aae9f199e611dfb6, so I think we can remove the `to_ary` check, which seems simpler than the approach in #895.   I'll submit a pull request for that.
