### ISSUE TITLE
Allow configuration of trusted proxies

### ISSUE THREAD

**Issue by jordan-thoms** [rack/rack#735]
I'm not sure if this has been discussed before, but it seems like it'd be beneficial to allow the configuration of the trusted proxies list used in https://github.com/rack/rack/blob/master/lib/rack/request.rb#L344 (trusted_proxy?).

Right now you have to monkey patch to change this. Rails relies on to get the IP for it's logs, so getting the correct remote IP to show up there requires monkeypatching Rack, which isn't ideal.

**Comment by jeremyevans** [comment]
Starting in 2.1.0, you can use `Rack::Request.ip_filter=` to override the trusted proxies, you no longer need to monkey patch Rack.  This is the related commit: 906c8c04a049de14042f289ffe46ed45978f2e9b
