### ISSUE TITLE
`autoload` is deprecated

### ISSUE THREAD

**Issue by whatyouhide** [rack/rack#750]
I just came to know that [`autoload` is going to be deprecated](https://www.ruby-forum.com/topic/3036681) (later more than sooner, but still). I like the feature in theory, but in practice it makes things a bit tricky. For example, writing extensions for `Rack::Builder` (yeah I have to be honest, extensions means monkeypatching) is tricky since opening the `Rack::Builder` class causes `autoload` to not load it again.

Should we consider moving to standard `require`s, at least for the core Rack classes?

**Comment by whatyouhide** [comment]
Closing this as I never had time to finish it :disappointed: Sorry people!

**Comment by arthurnn** [comment]
I wonder if `autoload` is still in the roadmap to be deprecated. The link in the description doesnt work anymore

**Comment by raggi** [comment]
The whole thing is odd. Hash isn't thread safe either, but that isn't
deprecated.

The only backwards compatible way to fix this would be to load all rack
code up front, and that sucks.
