### ISSUE TITLE
Rack.release identifier

### ISSUE THREAD

**Issue by zzak** [rack/rack#751]
If you look at https://github.com/rack/rack/blob/master/lib/rack.rb#L22-L24
It still says "1.5", but the gemspec has the version hardcoded.

Should we change this to use one method for both?
I'd like to be able to call `Rack.version` or `Rack.release` to find out which version of Rack I'm running.

**Comment by jodosha** [comment]
This was fixed by https://github.com/rack/rack/pull/777
