### ISSUE TITLE
Rack::Lint breaks `rack.request.form_input` and `rack.input` comparison

### ISSUE THREAD

**Issue by terlar** [rack/rack#752]
I have found that when I am using `Rack::Lint` in my tests they change the behavior of my application due to a faulty `.equal?` and/or `.eql?` method.

Here is a failing example using [`Rack::PostBodyContentTypeParser`](https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib/post_body_content_type_parser.rb) from [rack-contrib](https://github.com/rack/rack-contrib):

``` ruby
require 'bundler/setup'
require 'minitest/autorun'
require 'rack/test'

require 'rack'
require 'rack/contrib'
require 'json'

class TestRackLint < MiniTest::Unit::TestCase
  include Rack::Test::Methods

  TestApp = Rack::Builder.new do
    use Rack::Lint
    use Rack::PostBodyContentTypeParser
    use Rack::Lint

    run -> env { [200, { }, [JSON.dump(Rack::Request.new(env).params)]] }
  end

  def app
    TestApp
  end

  def test_middleware_relying_on_rack_request_form_input_and_rack_input_comparison
    input = { 'foo' => 'bar' }

    post '/', JSON.dump(input), { 'CONTENT_TYPE' => 'application/json' }

    assert_equal 200, last_response.status
    assert_equal input, JSON.parse(last_response.body)
  end
end
```

When using `Rack::Lint` it will fail, when removed this example passes. What happens is that the `equal?` method returns false in [`Rack::Request`](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L204) as [`Rack::Lint::InputWrapper`](https://github.com/rack/rack/blob/575bbcba780d9ba71f173921aa1fcb024890b867/lib/rack/lint.rb#L336) cannot compare itself properly. And because of that the params are never populated.

**Comment by jeremyevans** [comment]
I think was fixed in Rack::Request in 606421394d9e62936d18a4b6aab149cff0bb0f19 by using `==` instead of `equal?`.  If you still think this is a problem in rack, please submit a failing test or minimal self contained example that does not use any other libraries.
