### ISSUE TITLE
Spec is written very deceptivley

### ISSUE THREAD

**Issue by AtomicCreeper** [rack/rack#759]
I recommend making it more clear that "rack.hijack" is NOT a method and "environment" is not a class.

**Comment by snuggs** [comment]
Can we close this? After reviewing with @zanadar determined the specs and documentation are fairly clear in the following:
https://github.com/rack/rack/blob/master/test/spec_webrick.rb#L142

However there is much usage of this ```rack.hijack``` within:
https://github.com/rack/rack/blob/master/test/spec_webrick.rb#L142

This may be where the confusion lies.

**Comment by snuggs** [comment]
Thank you @raggi /cc @zanadar
