### ISSUE TITLE
params is empty if multipart request boundary is incorrect

### ISSUE THREAD

**Issue by tinexw** [rack/rack#761]
params in request.rb is empty if a multipart request ends with an incorrect boundary e.g. with `-9e923a4c2c2cbc9dd5f104b02ec111df-` and the header contains `Content-Type: multipart/form-data; =-6f88629f6762cfcdcdbe4b9c0156a786`. This is caused by the fact that params catches EOFError. Is there a specific reason that the exception is not propagated?

I'm using 1.6.0.beta.

**Comment by jeremyevans** [comment]
Removing the rescue inside `params` still results in a passing test suite.  I think the only time this would break things would be a POST request submitted without a body, which legitimately sounds like a situation that should raise.  Can any core team members think of a reason we would want to rescue EOFError inside `params`?

**Comment by jeremyevans** [comment]
@tenderlove @ioquatix What are your thoughts on removing the `rescue EOFError` inside `params`?

**Comment by ioquatix** [comment]
I think it's fine. Server can handle it.

**Comment by ioquatix** [comment]
Nice work.
