### ISSUE TITLE
Rack 1.6.0 release is 1.5?

### ISSUE THREAD

**Issue by dblock** [rack/rack#773]
https://github.com/rack/rack/blob/master/lib/rack.rb#L23 says 1.5 for 1.6 release. Is that intentional?

**Comment by raggi** [comment]
@tenderlove

**Comment by chneukirchen** [comment]
While we are all complaining, the changelog in the README is not updated either. ;)

**Comment by raggi** [comment]
confirm. scripts weren't used / followed, just a gem build and gem push by the looks of things.

**Comment by dblock** [comment]
PR + spec in https://github.com/rack/rack/pull/777.

**Comment by tenderlove** [comment]
No, this was a mistake.  I am very sorry.

**Comment by tenderlove** [comment]
@raggi I used the `rake officialrelease` task.  I'll update it to ensure this doesn't happen again.  I am *really* sorry.

**Comment by dblock** [comment]
Thanks for merging my PR @tenderlove. I think this issue should be reopened though, and we should figure out what to do with 1.6.0. I suggest cutting a 1.6.1 (double-checking all the things, updating history :)) and possibly yanking 1.6.0 from Rubygems (although this might be too radical since the code is fine).

**Comment by raggi** [comment]
@tenderlove no problem, the first time is always more tricky. I'll touch base when I'm not on a plane

**Comment by spastorino** [comment]
Shouldn't we have a rack/version.rb file with 1.6.0 there and then reuse the info in the gemspec and in this method to avoid duplication and hence avoid this kind of issues ?

**Comment by raggi** [comment]
@spastorino i guess we could figure something out, though some history/notes:
 * we didn't used to commit the gemspec, but bundler cries changed that (convenient excuse!)
 * the current interface for this does not include the patch level (this could be changed, but that could break things - users have been broken by this stuff before (sorry, not searching issues just atm))
 * if i'm remembering correctly, Gem::Specification.load is used in the rakefile and that runs under $SAFE so the require will fail - that'll need to be fixed unless i'm crazy and remembering things wrong.

other than that i'm all for it :dancer:

**Comment by raggi** [comment]
I'd also really like if Rubygems would just provide a public API for version discovery, as this really should be a package managers concern more than a packages concern. cc @drbrain

**Comment by tenderlove** [comment]
AFAICT, it does:

```
[aaron@TC rack (master)]$ irb
irb(main):001:0> require 'rack'
=> true
irb(main):002:0> Gem.loaded_specs['rack'].version
=> #<Gem::Version "1.6.0">
irb(main):003:0>
```

**Comment by raggi** [comment]
I can't remember / don't know if this is one of the things that'll be heading over to Gem::Specification like half of the methods on Gem did.

**Comment by dblock** [comment]
I think killing `Rack.release` or delegating it to `Gem` is definitely a sensible plan. Now that we have specs ;)

**Comment by raggi** [comment]
It could do something horrendous: `Gem.loaded_specs['rack'] || Gem::Specification.load(File.expand_path('../../../rack.gemspec', __FILE__))` etc.

**Comment by edmund-huber** [comment]
This made me cry out in rage and desperation.

**Comment by kares** [comment]
while delegating to RubyGems' is an option ... a simple `Rack.release` feels much better/reliable for tools doing rack version "feature-detection" - one can still strip out RubyGems loading in crazy "embed" envs JRuby supports ... not relying on `Gem` would be much appreciated (as well as a fixed 1.6.1 release) ...

**Comment by raggi** [comment]
No one uses rack in embedded envs anymore. We didn't publish a tarball this time around, and no one noticed.

**Comment by kares** [comment]
I meant JRuby embedded envs ... it really would be useful to not depend on `Gem` although it's not crucial.

**Comment by chneukirchen** [comment]
A .tar.gz is available on http://chneukirchen.org/releases/ as usual.
