### ISSUE TITLE
Backporting multipart_part_limit on the 1.5.X branch

### ISSUE THREAD

**Issue by byroot** [rack/rack#779]
Is there any chance the `multipart_part_limit` set of commit could be backported on the `1.5` branch?

We have to maintain a fork of rack because of this and to use rack `1.6` we need to upgrade to actionpack 4.2 which won't happen before months.

To not break compatibility the feature should probably be disabled by default.

Would you guys be ok with this? Alternatively a minor version of actionpack 4.1 could allow the use of rack 1.6.

What do you think @tenderlove or @spastorino?

**Comment by tenderlove** [comment]
I think it might be ok to backport.  Would you mind sending a PR so we can see the diffs? (If it's not too much work)

**Comment by byroot** [comment]
I would do it with please, I just don't know how to create a PR against another branch than master `/o\`. I need to check that up.

**Comment by tenderlove** [comment]
@byroot there should just be a dropdown when you send the PR.  Just select the branch from that.

**Comment by spastorino** [comment]
I was also talking with Aaron about relaxing Rack dependency on Rails side. At least we could do that in master ~> 1.x then ~> 2.x it should be that way and Rack shouldn't break Rails.

**Comment by byroot** [comment]
See: https://github.com/rack/rack/pull/783
