### ISSUE TITLE
Regression on handling of W3C HTML 4.01 compliant URL query parameters

### ISSUE THREAD

**Issue by paploo** [rack/rack#782]
Rack 1.6.0 introduces a bug whereby URLs that use semi-colons instead of ampersands in their query parameters are no longer correctly parsed.

For example, the following two URLs should parse to equivalent param hashes:

```
http://localhost:3333/echo?foo=bar&alpha=beta
http://localhost:3333/echo?foo=bar;alpha=beta
```

However, starting with 1.6.0, semicolons are no longer accepted and therefore the params hash is parsed as `{"foo"=>"bar;alpha=beta"}` instead of the expected `{"foo"=>"bar", "alpha"=>"beta"}`.

The W3C HTML 4 Document has an official Recommendation that web servers accept and parse semicolons and ampersands in section [B.2.2](http://www.w3.org/TR/html4/appendix/notes.html#h-B.2.2). Some enterprise web applications, unfortunately, rely on this official recommendation.

The root cause for this regression is that the `Rack::Request#parse_query` method was altered from:

``` ruby
# Rack 1.5
def parse_query(qs)
  Utils.parse_nested_query(qs)
end
```

to explicitly give the delimiter character

``` ruby
 # Rack 1.6
def parse_query(qs)
  Utils.parse_nested_query(qs, '&')
end
```

This can be resolved either by reverting to the call done in v1.5, or possibly by explicitly giving both ampersand and semicolon as so:

``` ruby
# Proposed Patch
def parse_query(qs)
  Utils.parse_nested_query(qs, '&;')
end
```

**Comment by paploo** [comment]
As a note, in a comment on the closed issue https://github.com/rack/rack/issues/543 was a PR (https://github.com/rack/rack/pull/781) that resolves this same issue I have reported, in a slightly different way.

**Comment by Nyoho** [comment]
@paploo, thank you for referring a pull request (#781) I sent.
I'm puzzled how we resolve this problem (fixing only GET-behavior (I wrote my patch for this), or reverting both GET and POST).

**Comment by paploo** [comment]
My understanding from various resources (e.g. Wikipedia) is that semicolons need to be supported in application/x-www-form-urlencoded POST as well as in GET query strings, but I have not done the research to verify this because the use case I have to support only requires supporting the query GET query strings.

**Comment by ioquatix** [comment]
It seems like relevant PRs have been merged. If this is still an issue can you create a PR with failing specs. Thanks everyone!
