### ISSUE TITLE
Cant connect to server running in VM

### ISSUE THREAD

**Issue by nickmcdonnough** [rack/rack#786]
Hey,

When running any Rack based app inside my VM (ubuntu) using Rack 1.6 I cant connect to the server from my host machine. I noticed this when working on a Sinatra app. When I forced it to use Rack 1.5.2 it worked just fine as it always has.

I'm not sure what the problem is or what was changed changed between 1.5.2 and 1.6.

Any advice would be appreciated.

**Comment by nickmcdonnough** [comment]
I actually just discovered that at least with Rails if I launch the server with `rails s -b 0.0.0.0` it will work as expected. I haven't tried anything with Sinatra where I'm using `rackup` to launch the server.

Thanks.

**Comment by mattwildig** [comment]
Looks like this could be due to 28b014484a8ac0bbb388e7eaeeef159598ec64fc. The default host has changed from 0.0.0.0 to localhost in development. Try running  `rackup` with `--host 0.0.0.0`.

**Comment by nickmcdonnough** [comment]
Thanks @mattwildig. That worked. Thanks for pointing out the commit as well.
