### ISSUE TITLE
Release 1.5.3?

### ISSUE THREAD

**Issue by ericsullivan** [rack/rack#797]
I ran into a bug w/ a rails 4.0 system using omniauth similar to this one:
https://github.com/intridea/omniauth/issues/101

It was appending port 80 to an https callback url (using a vhost that sets X_FORWARDED_PROTO to 'https') 

Rails 4 has the rack dependency set at '~> 1.5.2', so I couldn't update to 1.6.0
The fix is already in the 1.5 branch
https://github.com/rack/rack/commit/f3a378d8f0205978c0a6257b2836f64ee93e2e43
It just hasn't been released.
I just monkey-patched the port method in a initializer, I could have also pointed my gemfile to that branch, but I was wondering if it's worth a tagged release. Thank You

**Comment by zzak** [comment]
Should be ok now: https://github.com/rack/rack/releases/tag/1.5.3

**Comment by ericsullivan** [comment]
Excellent, thanks for the update
