### ISSUE TITLE
“ThreadError: deadlock; recursive locking” when using Rack::MockRequest

### ISSUE THREAD

**Issue by davidcelis** [rack/rack#808]
Hi! I ran across an issue when trying to use Rack::MockRequest in a Rails Engine I’m writing. When running multiple test cases that call `Dummy::Application.call Rack::MockRequest.env_for('/')`, this results in `ThreadError: deadlock; recursive locking`

However, if I switch my tests to use `rack-test` or subclass from `ActionDispatch::IntegrationTest` and use that stack, the ThreadErrors go away. I've pushed a [repository](https://github.com/davidcelis/recursive_locking) that you can use to reproduce this error. It's [building on Travis](https://travis-ci.org/davidcelis/recursive_locking) against various versions of Ruby and is affected across all of them. This is on the latest version of Rack.

A weird bit about this is that [appears to itself use Rack::MockRequest under the hood](https://github.com/brynary/rack-test/blob/acdbee66fc765f15c2d3a1a372c368fe8ee0a49c/lib/rack/test.rb#L237), but the tests I have running against `rack-test` pass.

UPDATE: It looks like the failures in `locking_test.rb` go away when I change `Dummy::Application.call Rack::MockRequest.env_for('/')` to `Rack::MockRequest.new(Dummy::Application).get('/')` so... Maybe this is actually a Rails issue? Is something in the `Dummy::Application.call` stack not closing the response body?

**Comment by davidcelis** [comment]
It looks like the failures in `locking_test.rb` go away when I change `Dummy::Application.call Rack::MockRequest.env_for('/')` to `Rack::MockRequest.new(Dummy::Application).get('/')`

**Comment by tenderlove** [comment]
> Is something in the Dummy::Application.call stack not closing the response body?

This is very likely the problem.  Are you using Rack::Lock?  If so, if someone forgets to close the body, you will have a deadlock on the second request.

**Comment by mediaslave24** [comment]
@davidcelis 

Hello (just randomly picked this issue today). I paid attention to [this line](https://github.com/davidcelis/recursive_locking/blob/master/test/locking_test.rb#L11)

I looks like incorrect, because [body should be closed after each iteration.](https://github.com/rack/rack/blob/master/SPEC#L249)

When you call raw ```Rails::Application#call```, it doesn't close body as it should.
[This](https://gist.github.com/mediaslave24/ccd23c9006e7c5342f32) or [this](https://gist.github.com/mediaslave24/270b8493f2d7aad9c3f6) can fix the error.

**Comment by ioquatix** [comment]
I think this is a bug in Ruby which should since be solved.
