### ISSUE TITLE
webrick handler clobbers BindAddress option in default (development) environment

### ISSUE THREAD

**Issue by blackjackshellac** [rack/rack#821]
BindAddress is changed to "localhost" in a development environment when attempting to delete options[:Host].  setting :Host in the webrick options as well as BindAddress prevents this from happening, but it seems to me that :BindAddress should not be overwritten based on RACK_ENV unless it has not been specified, something like,

options[:BindAddress]=default_host unless options.has_key?(:BindAddress)

**Comment by jeremyevans** [comment]
I think it makes sense not to clobber `:BindAddress` if it is already set and `:Host` is not set.  I'll submit a pull request for that.
