### ISSUE TITLE
Running out of disk space throws a weird exception

### ISSUE THREAD

**Issue by steverob** [rack/rack#822]
When there is no space left on the disk, `https://github.com/phusion/passenger/blob/stable-3.0/lib/phusion_passenger/utils/rewindable_input.rb#L86` throws `Errno::ENOENT: No such file or directory /tmp/RackRewindableInput20150311-13259-cvqkcr.lock):` which is not very friendly :)

Can we handle the exception and let people who what may have gone wrong?

I had this problem with Passenger (2.2) today - `https://github.com/phusion/passenger/blob/stable-3.0/lib/phusion_passenger/utils/rewindable_input.rb#L86`.

Just a thought.. :)

**Comment by jodosha** [comment]
@steverob Shouldn't `Tempfile` fail with `Errno::ENOSPC` instead of `Errno::ENOENT`?

**Comment by raggi** [comment]
No. This is before the write call. See the '.lock'

**Comment by ioquatix** [comment]
I think this is out of scope for Rack. If you think it's in scope, please make a PR.
