### ISSUE TITLE
Unhandled exception on Post request with empty body

### ISSUE THREAD

**Issue by aingvarf** [rack/rack#838]
When you use NTLM authentication (for example with ntlm-sso gem) with IE, the last on POST requests acts in this way:
1. IE send full POST request
2. Rails (ntlm-sso) respond with 401 - need authentication 
3. IE send POST request with auth data but with empty body!

In previous versions of Rack it was handled by ntlm-sso responding on POST with 401 again, then IE again send POST with full body. That was possible because rack was handled POST request with empty body without exception. The exception was rescued in lib/rack/methodoverride.rb:

    def method_override(env)
      req = Request.new(env)
      method = req.POST[METHOD_OVERRIDE_PARAM_KEY] ||
        env[HTTP_METHOD_OVERRIDE_HEADER]
      method.to_s.upcase
    rescue EOFError
      ""
    end

Now this method does not rescue from EOFError and we cannot handle this situation. I request to return rescue from EOFError in this method.

**Comment by jodosha** [comment]
@aingvarf Which version of Rack are you using? Does this test reproduces your case? https://github.com/jodosha/rack/commit/416aade700d258581d58fb9c5046e0f86129c09e

It passes for me but, according to your description, it supposed to fail.

**Comment by aingvarf** [comment]
I use rack 1.6.0. 
The test jodosha@416aade700d258581d58fb9c5046e0f86129c09e passes successfully. But the test  aingvarf@d0b636c979c2aebfcea10144557b788680391ade fails. 

IE sends second POST request with auth data and empty content, but set header Content-Type equal to firtst unauthorized request and Content-Length = 0. I suppose that parsing content should be avoided if  header Content-Length = 0.

**Comment by jodosha** [comment]
@aingvarf Thank you, I've opened a PR (#869) to fix this problem. It's a quickfix hack, but it should work.

**Comment by aingvarf** [comment]
Thanks @jodosha!
