### ISSUE TITLE
Link to SPEC broken on website

### ISSUE THREAD

**Issue by chneukirchen** [rack/rack#847]
> http://rubydoc.info/github/rack/rack/master/file/SPEC

doesn't work anymore. Ideas?

**Comment by spastorino** [comment]
No idea to be honest, will try to figure out.

**Comment by lsegal** [comment]
Works now, just needed a refresh! Sometimes projects don't get updated correctly from Github due to networking or worker issues. Re-adding the project is usually a good way to solve these issues.

**Comment by spastorino** [comment]
Thanks @lsegal
