### ISSUE TITLE
"Can't modify frozen Hash" on request.cookies

### ISSUE THREAD

**Issue by chengguangnan** [rack/rack#848]
I was try to access cookie from a rack middleware.  So I used `request.cookies`, but it gives "cache error: can't modify frozen Hash".

The problem came from `/rack-1.6.0/lib/rack/request.rb:296:in `cookies'`. 

Or on master branch, its [line 302](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L302)

It seems to me that the code is try to modify the @env hash while it's frozen. 

In my case, I have to make a dup to bypass this problem.

`request = Rack::Request.new(request.env.dup)`

Is the `@env["rack.request.cookie_hash"] ` at line 302 a cache? Maybe its frozen state should be checked before modifying.

BTW. I encountered this problem while using rack-cache. 

```
    config.middleware.use Rack::Cache, {
      metastore: "file:tmp/cache/rack/meta",
      entitystore: "file:tmp/cache/rack/body",
      verbose: true,
      allow_reload: true,
      allow_revalidate: true,
      cache_key: lambda { |request|
        request = Rack::Request.new(request.env.dup)
        Rack::Cache::Key.new(request).generate + request.cookies["uid"]
      }
```

**Comment by jodosha** [comment]
@chengguangnan By grepping the source code of Rack, the only fronzen objects are string constants like `ETAG_STRING = 'ETag'.freeze`.

On the other hand, `Rack::Cache` seems to [freeze](https://github.com/rtomayko/rack-cache/blob/d00e6e491fcc7bdca9c27d735abde5c4fdb48cd9/lib/rack/cache/context.rb#L61) the environment before to pass it as argument for `Rack::Request`.

This last object works under the assumption of "mutable env" and cookies are exposed as a mutable Hash too. Eg `request.cookies['foo'] = 'bar'`.

One possible solution is to extract cookies parsing logic into `Rack::Utils` and make `Request` use it. This new function `.parse_cookies` should work without mutating the env. I'm preparing a PR with this approach.

**Comment by jodosha** [comment]
Opened a PR that solves this issue. /cc @tenderlove

**Comment by jodosha** [comment]
Now that #857 has been merged, I guess this issue can be closed :)

**Comment by tenderlove** [comment]
Great, thanks!
