### ISSUE TITLE
Should cookie parsing follow RFC6265 strictly?

### ISSUE THREAD

**Issue by al2o3cr** [rack/rack#849]
The cookie parser accepts both `;` and `,` as delimiters:

https://github.com/rack/rack/blob/7e0833d38c79d7d2fdf5de2a511a1a0cf9561f97/lib/rack/request.rb#L313

This follows the original specifications in [RFC 2109](http://www.rfc-editor.org/info/rfc2109) and [RFC 2965](http://www.rfc-editor.org/info/rfc2965), but both of these have been obsoleted by [RFC 6265](http://www.rfc-editor.org/info/rfc6265) which does not include the possibility of `,` as a delimiter in `Cookie:` headers. Note that `,` is still not allowed in cookie values (it is explicitly excluded from `cookie-octets` in RFC6265).

I ran across this today investigating whether Rails / Rack could be subject to the parsing error mentioned here:
https://hackerone.com/reports/14883

**Comment by tenderlove** [comment]
Huh. Honestly I have no idea if we should be strict.  I'd like to know what browsers send today.  Other than that, I'm planning on making master 2.0, so we could experiment with making it strict and see what happens.

**Comment by tenderlove** [comment]
@al2o3cr master is 2.0.  Would you mind putting together a PR that does this?

**Comment by Adam89** [comment]
@tenderlove and @al2o3cr I can put together a pr for this, would either of you mind?

**Comment by tenderlove** [comment]
Please do it!

--
Aaron Patterson
http://tenderlovemaking.com/
I'm on an iPhone so I apologize for top posting.

**Comment by Adam89** [comment]
I did not see much value in adding a test that makes sure the cookie parser only accepts `;`. Do you think I should add one and is there anything I might have missed in this pr?

**Comment by Adam89** [comment]
cc @tenderlove

**Comment by mrageh** [comment]
mind reviewing this pr @tenderlove :)

**Comment by ioquatix** [comment]
Merged.
