### ISSUE TITLE
Multipart Large file upload memory issue ?

### ISSUE THREAD

**Issue by yanzou** [rack/rack#851]
I was building a Rails App (rails 3.2.12)  trying to handle upload files,

Client Side
---------------------
Here is the Post from console (or browser by using HTML5 file API)
 ```
curl -X POST -H 
"Content-Type: multipart/form-data;" --data-binary @someLargeFile http://localhost/upload
```

Server Side
--------------------------
```ruby
class DataFileUploadController < ApplicationController
  def upload_file
    post = DataFile.save(params[:file])
  ...

class DataFile < ActiveRecord::Base
  def self.save(upload_file)
    #avoid writing to disks again (upload_file would be in /tmp directory already)
    FileUtils.mv upload_file.path, Rails.root.join("public/uploads", upload_file.original_filename)
   ...
```

When the size of the file is small (10KB, 10MB) , it seems ok.

When I try to upload  > 1GB file, (the 99% upload progress is fast) but at the end of transportation, it blocks like 5, 6 sencond (or more) before I get the response from server. 

So, I use ```top``` to monitor my server, I found the memory and CPU was consumed by ```Rails```, seems rails will consume as same size as the file I uploaded.

![____________________________untitled](https://cloud.githubusercontent.com/assets/7699445/7511563/4ea30104-f4d8-11e4-9510-0dcbbd1bc0cc.png)

I guess this cause by Multipart module will assemble the file chunks in memory ?

**Comment by yanzou** [comment]
my rack stack
```ruby
rake middleware
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000000ba8ab0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use ActionDispatch::Head
use Rack::ConditionalGet
use Rack::ETag
use ActionDispatch::BestStandardsSupport
run FileMultipartUpload::Application.routes

```

**Comment by yanzou** [comment]
maybe this is where I can hack ?

[rack/multipart/generator.rb](https://github.com/rack/rack/blob/master/lib/rack/multipart/generator.rb)
```ruby 
def content_for_tempfile(io, file, name)
<<-EOF
--#{MULTIPART_BOUNDARY}\r
Content-Disposition: form-data; name="#{name}"; filename="#{Utils.escape(file.original_filename)}"\r
Content-Type: #{file.content_type}\r
Content-Length: #{::File.stat(file.path).size}\r
\r
#{io.read}\r
EOF
end
```

**Comment by jodosha** [comment]
@yanzou Yes, that is the case. Unfortunately, Rack 1.x eager load request body before to pass the control to the middleware stack and then down to the application.

Buffered IO is a goal for Rack 2.0. See [Rack-Next](https://github.com/Wardrop/Rack-Next#input-and-output), [Rack 2.0](https://gist.github.com/raggi/11c3491561802e573a47#the-areas-for-improvement) and [The Metal](https://github.com/tenderlove/the_metal) as a reference for design proposals.

These are long term solutions and you need a to solve your problem now. Have you tried with direct upload on S3 via CORS? Bypassing your Rails app, won't hit this issue.

/cc @tenderlove Please close this issue if you confirm :arrow_up: :green_heart: :blue_heart: :yellow_heart:

**Comment by spastorino** [comment]
:+1:

**Comment by yanzou** [comment]
@jodosha Thank you for your explaination and I'll looking for alternative solution :+1:
