### ISSUE TITLE
HISTORY is not up-to-date

### ISSUE THREAD

**Issue by dblock** [rack/rack#852]
Trying to track down why some tests in Grape started failing with Rack 1.5.3, https://github.com/rack/rack/blob/master/HISTORY.md has not been updated with 1.5.3 or 1.6.x.

**Comment by zzak** [comment]
Closed by a2fe30a5e70371c89c1b29fdc2dc5f8027bc5fe6 ?

**Comment by dblock** [comment]
Honestly not IMHO, but I will let the maintainers make the call. If git history is "history", then we don't need a HISTORY file. The whole point is to extract meaningful changes, do things like separating bug fixes from features and maybe provide explanations of how users are affected.

**Comment by tenderlove** [comment]
@dblock we can do that going forward, but I don't have time to review every commit that's gone by for the past releases.  If someone wants to do that, then I'll happily merge it.  Also, going forward, I'd rather we don't put dates and release numbers in HISTORY.  I'd rather we have "ChangeLog" and "NEWS".

**Comment by ioquatix** [comment]
We are doing our best to keep this up to date, but there are lots of PRs which I've just merged. I welcome someone to help update the relevant change log.

**Comment by dblock** [comment]
My 0.02c is that no PR should be merged without having the changelog updated. Might want to try Danger with https://github.com/dblock/danger-changelog to avoid having to nag manually. Happy to help set that up.

**Comment by ioquatix** [comment]
At this point with PRs that are 3+ years old, we are stuck. Just need to get through this backlog. Agree with you about needing it to be provided in the PR.
