### ISSUE TITLE
Cookie header : NoMethodError (undefined method `gmtime' for [DateTime])

### ISSUE THREAD

**Issue by Startouf** [rack/rack#864]
I just updated a bunch of my gems, everyting works fine in local development environment, but when I tried to deploy to my production server and login, there's a problem with cookies 

```
NoMethodError (undefined method `gmtime' for Fri, 05 Jun 2015 01:24:55 +0000:DateTime):
```

Full Stack Trace

```
NoMethodError (undefined method `gmtime' for Fri, 05 Jun 2015 01:24:55 +0000:DateTime):
  rack (1.6.1) lib/rack/utils.rb:304:in `set_cookie_header!'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:352:in `block in write'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:352:in `each'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:352:in `write'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:564:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/ssl.rb:24:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  passenger (4.0.37) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.37) lib/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  passenger (4.0.37) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (4.0.37) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
```

I'm using Webbrick in my local environment and Passenger in my production server,

**Comment by Startouf** [comment]
Woh.... Just a few minutes later everything works perfectly. Possible vulnerability in the code for some inputs ?

**Comment by jodosha** [comment]
@Startouf The problem is that a `Rack::Utils` expects `:expires` option to be a `Time` instance, as it respond to `#gmtime`. This really depends on the value that is passed to the cookies.

Do you assign cookies with a value from `:expire` that comes from a dynamic value like a database field?

```ruby
cookies[:foo] = { value: 'bar', expires: @user.cookie_expires_on  }
```

Please grep your code and gem dependencies and check if there is something that sets `:expires` with the wrong value. If you're using Rails cookie session, it can be the value that you set for `:expire_after`.

**Comment by Startouf** [comment]
Sorry for the late reply, the issue had disappeared for the time being, but now it's back (not really sure what caused it :(... Only affects production environment.

There's nothing in my code that should modify cookies, at least nothing that I'm aware of (maybe some libraries that interfere with each other ?).

I thought it may come from some fields in my devise user model that were se to DateTime instead of Time, but then it had never been a problem, and even after I changed it... no improvement.

Any idea ?

**Comment by Startouf** [comment]
Oh apparently it only happens with devise when I tick the box "remember me", anyone knows which piece of code is responsible then ?

I didn't realize that before, because I usually use a login form without that checkbox...

**Comment by srghma** [comment]
Overcome this using specific time

```rb
    cookies["solicitation_#{active_solicitation.id}"] = {
      value:   true,
      expires: Time.zone.now + active_solicitation.cookie_duration_days.days
    }
```

**Comment by serhanbalci** [comment]
pretty weird but I solved such like this. 

`# Sets a cookie that expires in 10 days.`
`cookies[:login] = { value: "XJ-122", expires: (Time.current + 10.days)}`

**Comment by jeremyevans** [comment]
Rack now uses `httpdate` instead of `gmtime`/`rfc2822`, and works with both `Time` and `DateTime` instances, so this can be closed.

**Comment by growthcode** [comment]
I'm on an older version of Rack and Devise.  I needed to convert Devise's `:remember_created_at` from a DateTime to a Time and it started working again.
