### ISSUE TITLE
Rack::Response.new(body) does not close original body on #close

### ISSUE THREAD

**Issue by wjordan** [rack/rack#877]
These two lines of code seem to have slightly different behavior:

```
response = Rack::Response.new
response.body = body
response.close
```

```
response = Rack::Response.new body
response.close
```

In the first example, `body` is closed properly, but in the second example, `body` is left open, which caused deadlock issues in my Rack application. Is there a reason for this major difference, or should #close be explicitly called on the initializer body after iterating through its contents?

**Comment by wjordan** [comment]
I was a bit stumped by these two tests, which together seem to demand this difference in behavior: [should "allow calling body.close afterwards"](https://github.com/rack/rack/blob/b79e15304213403858538f45b8d1928376776ddb/test/spec_mock.rb#L264-L270) vs. [it "calls close on #body"](https://github.com/rack/rack/blob/b79e15304213403858538f45b8d1928376776ddb/test/spec_response.rb#L320-L325)

**Comment by tenderlove** [comment]
Can you write a test to demonstrate what you mean?

> I was a bit stumped by these two tests, which together seem to demand this difference in behavior: should "allow calling body.close afterwards" vs. it "calls close on #body"

How?  They seem fine to me.  I don't get it.

**Comment by wjordan** [comment]
>Can you write a test to demonstrate what you mean?

Here is my above code snippet expanded into a test:
```
it "calls close on body passed via initializer" do
  body = StringIO.new
  res = Rack::Response.new body
  res.close
  body.should.be.closed
end
```

> How? They seem fine to me. I don't get it.

- "calls close on #body" requires `close` to be called on the response body;
- "allow calling body.close afterwards" requires `close` to **not** be called on the response body;
- These two requirements cannot both hold simultaneously.

The only reason both tests currently pass is because one test sets the IO stream in the initializer, and the other sets it through the `attr_accessor` after the Response object is initialized. If this difference in API behavior between the initializer and `attr_accessor` is intentional (as the existence of the two contradictory tests might suggest), this difference (or the reasoning behind this difference) is not currently documented.

**Comment by tenderlove** [comment]
> "allow calling body.close afterwards" requires close to not be called on the response body;

I don't follow how that is true.  It could also mean that you can call `close` on the response body multiple times.

**Comment by wjordan** [comment]
This issue has apparently been a source of confusion/bugs for several years- see @rkh's commit-revert 1a7751d04090162bf08a8f0a0d265288453aa880 back in 2011:
> It is strange, though that `Response.new(something)` behaves different
than `Response.new.body = something`.

> I don't follow how that is true. It could also mean that you can call close on the response body multiple times.

The "allow calling body.close afterwards" test calls `close` directly on the StringIO stream passed via initializer to the MockResponse object, not `Response#close`. This usage pattern is codified in rack-test's [mock_session.rb](https://github.com/brynary/rack-test/blob/master/lib/rack/mock_session.rb#L32-L33). Calling close on an IO stream multiple times raises `IOError` (although this will be [changed](https://github.com/ruby/ruby/commit/255955585c922ec5e303df184057b7781fcee345) in Ruby 2.3, that doesn't help us here).

This pattern that rack-test requires made it more difficult to figure out a good solution, but I think I managed to put together a pull request that should fix the strange behavior in this class without needing to change any of the existing tests, so please have a look.

**Comment by tenderlove** [comment]
> Calling close on an IO stream multiple times raises IOError (although this will be changed in Ruby 2.3, that doesn't help us here).

Ahhhh. I was testing with Ruby 2.3.  Now it makes more sense.  Is there a reason people call the setter, and not just create a new response object?  I mean, why should we keep the setter around?

**Comment by wjordan** [comment]
It looks like all three Response-body interfaces (#write, #body setter, constructor) have been around since Feb 2007, soon after the Response class was first created ([history](https://github.com/rack/rack/commits/c525c2871a0de628786233077ac3603e9fe5d8e4/lib/rack/response.rb)).

Reasons people might currently be using the body setter versus the constructor or #write:
1. the passed-in body will be closed downstream per the Rack SPEC, unlike the constructor (my original reason for this GitHub issue)
2. the body is not iterated into a buffer in the Response object, unlike the constructor and #write (useful for large responses?)
3. it does not modify the content-length header (because the size of the body cannot be known until it is iterated over)
4. just because it's possible, and pros/cons of using are not clear

PR #887 is my attempt to bring all three interfaces in sync through backwards-compatible changes preserving the behavior in existing tests. If a breaking change is ok, I think removing the setter entirely in favor of always passing a body in the constructor could make sense.

If passing an unbuffered body to Response is important, the constructor code would need further tweaks to satisfy that (it would need to break the rack-test usage pattern I discussed above).

**Comment by tenderlove** [comment]
> If a breaking change is ok, I think removing the setter entirely in favor of always passing a body in the constructor could make sense.

Master is 2.0, so we can make breaking changes.  Can you send a PR to master that does this, then send #887 to 1-6-stable as a bug fix?

> If passing an unbuffered body to Response is important, the constructor code would need further tweaks to satisfy that (it would need to break the rack-test usage pattern I discussed above).

Can we split the response to buffered and unbuffered?  It seems like the current response object always buffers responses (or you have to jump through weird hoops not to buffer).

**Comment by wjordan** [comment]
> Master is 2.0, so we can make breaking changes. Can you send a PR to master that does this, then send #887 to 1-6-stable as a bug fix?

> Can we split the response to buffered and unbuffered? It seems like the current response object always buffers responses (or you have to jump through weird hoops not to buffer).

Done and done - please see #891. Also related to this issue, please take a look at #888 which implements Rack::Lint detection for when the old Rack body is not properly closed when replaced, which should help with debugging similar body-close issues in other Rack middleware.
