### ISSUE TITLE
#File.serving() OPTIONS request cannot return content

### ISSUE THREAD

**Issue by rebrendler** [rack/rack#914]
I'm trying to return an HTML document in response to an OPTIONS request (fairly standard behaviour for a ReST API), but the File.serving() method is short-circuiting and returning an empty body:

```
      if env[REQUEST_METHOD] == OPTIONS
        return [200, {'Allow' => ALLOW_HEADER, CONTENT_LENGTH => '0'}, []]
      end
```

There should be an option to allow content to be served for OPTIONS requests.

**Comment by Larivact** [comment]
[Link to the code](https://github.com/rack/rack/blob/master/lib/rack/file.rb#L59)

**Comment by jeremyevans** [comment]
I don't think the need for this is common enough to support in rack itself.  You can probably hack your way around this (untested):

```ruby
class MyFiles < Rack::Files
  def serving(request, path)
    request.env["REQUEST_METHOD"] = "GET" if request.options?
    super
  end
end
```
