### ISSUE TITLE
RFC: `X-Rack-No-Buffer` response header

### ISSUE THREAD

**Issue by julik** [rack/rack#932]
Recently I've been working on implementing Rack streaming in a compatible way for multiple servers. What baffles me is that Rack has no specification for buffering-after-headers. Even on PHP you can easily make a streaming responder just by flushing headers manually and then writing on the output stream, and you know the server will send your response as soon as possible.

My research so far has yielded this gem https://github.com/julik/long_body which largely solves the problem, but I think Rack should specify this behavior explicitly. There should be a way to tell the server that we want app-controlled output timing (to the closest possible extent).

Rack, however, does not have such a provision in the current spec. What I propose is having an extra output header for hinting this to the Rack handler, with a simple convention: if `X-Rack-No-Buffer` is set, the webserver handler should do most things possible to not buffer the request, and send each yielded response chunk as soon as it is available. The header can also be made to have a switching value (such as 'X-Rack-Unbuffered' set to `yes` or `no`).

This will also be backwards-compatible to older Rack versions and older Rack servers.

**Comment by matthewd** [comment]
I'm not sure I understand the problem you're trying to solve. I [see](https://github.com/macournoyer/thin/blob/db6f06856bd361a6a6546537c3dfe3f1565c34dc/lib/thin/connection.rb#L114-L117) [no](https://github.com/defunkt/unicorn/blob/f84309ebb9c792d0a2ffec5ffc2f859b361cddc8/lib/unicorn/http_response.rb#L54) [obvious](https://github.com/puma/puma/blob/c26490da4ba609e19c38e72a1782e785742b6372/lib/puma/server.rb#L666-L678) [buffering](https://github.com/phusion/passenger/blob/76e4ecf6b81194e85482c023c66a8e95104bd394/lib/phusion_passenger/rack/thread_handler_extension.rb#L280-L304).

The rack spec defines a call interface, and appears to make no promises about what a caller will do. But my quick survey seems to suggest all the servers are in agreement: each body chunk is put onto the wire as soon as it becomes available.

**Comment by julik** [comment]
This was not the case in my testing. Thin was buffering everything (the entire response). WEBrick is still buffering the entire response. Unicorn and Puma indeed do work correctly out of the box, but this is not documented and not enforced on the spec level - therefore any minor version bump on them could kill this functionality without warning.I think Passenger 5 also does buffering to support the new caching strategy.

> and appears to make no promises about what a caller will do

This is exactly the promise that should be added to the spec IMO.

**Comment by julik** [comment]
For example, when I enable the simple test output of the long_body test harness it will be visible that Thin happily concatenates the entire response and sends it in one swoop, after a substantial delay.

**Comment by julik** [comment]
And Passenger 5 as well (which is exactly what my suspicion is).

**Comment by matthewd** [comment]
My point is that *nothing* is currently promised -- the spec doesn't say that the response will be written to a network connection at all.

**Comment by matthewd** [comment]
> Thin was buffering everything (the entire response)

> I think Passenger 5 also does buffering

cc @FooBarWidget @macournoyer

**Comment by julik** [comment]
> My point is that nothing is currently promised

Mine as well :-)

**Comment by julik** [comment]
Clear demo of buffering (without using my gem, within the same test harness, per server) is here https://github.com/julik/long_body/tree/demo-buffering - just run `rake`. It will also print when each piece of the response has been received (with what delay).

**Comment by FooBarWidget** [comment]
Although Passenger 5 buffers the response by default, its buffering behavior is streaming. That is, sends the response parts as quickly as possible to client, instead of buffering everything before sending to the client. Thus, Passenger more or less does everything right out-of-the-box. More info: https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_buffer_response

**Comment by macournoyer** [comment]
Sorry for the late comment. Thin does indeed buffer everything unless an async callback is used. That is because it can only send data when control is given back to the EventMachine loop.

I could implement streaming by using Fibers, like long_body does, but that can't be enabled for all requests by default.

I like this proposal a lot, but I'd prefer avoiding the negative form (No-Buffer, Unbuffer). Perhaps `X-Rack-Stream`? W/ values `on`/`off` or `yes`/`no`, default lets the server decide.

**Comment by tenderlove** [comment]
I don't like the idea of adding a special header for this.  I don't think webservers should buffer in the first place, but it's really up to the webserver developers.  If you need streaming for your application, you should pick a webserver that supports it.

IOW, webservers are allowed to be special (see the difference between Rainbows! and Unicorn).
