### ISSUE TITLE
Missing documentation on how to access the --option passed into Rack via "$ rackup --option arg1=10"

### ISSUE THREAD

**Issue by atomless** [rack/rack#939]
I've searched high and low without any joy for how to access from the config.ru the option arg that the docs specify can be passed into Rack when running the rackup command like so:

```
$ rackup --server thin --option arg1=10
```

I'm new to Ruby and Rack so it's quite possible it seemed too obvious to detail in the docs but I've tried every method I can think of to access the option in order to make it available to my apps that I'm running from the config.ru using RAck::Cascade.

**Comment by jeremyevans** [comment]
rackup's `--option` option sets server options, not application options.  You should only be accessing these options if you are writing your own handler.  The options are passed to `Rack::Handler::$HANDLER.run`.  For example, in the webrick handler, the options are passed to `::WEBrick::HTTPServer.new`
