### ISSUE TITLE
Need more control over Rack::Static's 404 responses

### ISSUE THREAD

**Issue by edmorley** [rack/rack#946]
This is probably quicker to explain with an example:

config.ru:

``` ruby
use Rack::Static,
  :urls => ["/js", "/css"],
  :index => "index.html"

body = "My custom 404 text\n"
headers = {"Content-Type" => "text/html", "Content-Length" => body.size.to_s}
run lambda { |_| [404, headers, [body]] }
```

Querying the server (using Rack v1.6.4):

``` bash
# URL matches a prefix given in the `urls` option. See docs:
# http://www.rubydoc.info/github/rack/rack/Rack/Static
[~/src]$ curl http://localhost:9292/js/bar
File not found: /js/bar
# URL doesn't match anything in `urls` so Rack::Static falls back to our lamba function.
[~/src]$ curl http://localhost:9292/foo
My custom 404 text
```

This is suboptimal, since:

(1) If you want a custom 404 page, then there's no way to have it returned for both cases, so the user experience will be inconsistent.

(2) Even if you don't want a custom 404 page, trying to emulate Rack::File's response adds more boilerplate for escaping the filename in the body text etc, which is all duplication of what's already in Rack::File.

What would help is either of:

(a) Adding an option to Rack::Static that meant in the case of non-existent files that matched `urls`, we don't use [Rack::File's response](https://github.com/rack/rack/blob/c28f271d0c91f45e13bfa8f07bed445ef91f41de/lib/rack/file.rb#L47), but instead fall back to the wrapped app (ie our lamda function above).

(b) Adding support to Rack::Static for passing a custom 404 response (or file) to Rack::File, which gets served instead of the hardcoded string.

I think my preference is for (a), since it results in less duplication & seems like it would also be more useful for people using Rack::Static alongside a more typical Rack app (rather than my Heroku use-case example above).

Many thanks :-)

**Comment by jeremyevans** [comment]
I agree that this feature makes sense to add as an option.  Since it operates similarly to `Rack::Cascade`, I think `:cascade` is a good option name for it.  I'll submit a pull request for that.

**Comment by edmorley** [comment]
@jeremyevans Thank you :-)
