### ISSUE TITLE
`parse_nested_query` fails when first member of Array is a Hash

### ISSUE THREAD

**Issue by eins78** [rack/rack#951]
form values:

```rb
many_foos[][user][id]=1234&
many_foos[][bar]=baz&
many_foos[][user][id]=5678&
many_foos[][bar]=blub
```

test: 

```rb
Rack::Utils.parse_nested_query("many_foos%5B%5D%5Buser%5D%5Bid%5D=1234&many_foos%5B%5D%5Bbar%5D=baz&many_foos%5B%5D%5Buser%5D%5Bid%5D=5678&many_foos%5B%5D%5Bbar%5D=blub")
=> {"many_foos"=>[{"user"=>{"id"=>"5678"}, "bar"=>"baz"}, {"bar"=>"blub"}]}
```

- result:

    ```rb
    {"many_foos"=>[{"user"=>{"id"=>"5678"}, "bar"=>"baz"}, {"bar"=>"blub"}]}
    ```

- expected:

    ```rb
    {"many_foos"=>[{"bar"=>"baz", "user"=>{"id"=>"1234"}}, {"bar"=>"blub", "user"=>{"id"=>"5678"}}]}
    ```

---

Can be fixed application-side by re-ordering the form fields,
so that no Array starts with a Hash:

form values:

```
many_foos[][bar]=baz&
many_foos[][user][id]=1234&
many_foos[][bar]=blub&
many_foos[][user][id]=5678
```

test:

```rb
Rack::Utils.parse_nested_query("many_foos%5B%5D%5Bbar%5D=baz&many_foos%5B%5D%5Buser%5D%5Bid%5D=1234&many_foos%5B%5D%5Bbar%5D=blub&many_foos%5B%5D%5Buser%5D%5Bid%5D=5678")
```

- result:

    ```rb
    {"many_foos"=>[{"user"=>{"id"=>"5678"}, "bar"=>"baz"}, {"bar"=>"blub"}]}
    ```

**Comment by prrrnd** [comment]
Also having this issue with the following:
```
params = {"form"=>{"things"=>[{"user"=>{"name"=>"a"}, "amount"=>"1"}, {"user"=>{"name"=>"b"}, "amount"=>"2"}]}} 
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query(params))
# => {"form"=>{"things"=>[{"user"=>{"name"=>"b"}, "amount"=>"1"}, {"amount"=>"2"}]}} 
```

Any updates on this @eins78 ?

**Comment by kuldeepaggarwal** [comment]
\cc @conzett

**Comment by conzett** [comment]
@kuldeepaggarwal I do have a branch that seems to fix the issue at hand however, the parameter parsing portion of Rack seems under-tested and even with @eins78's specs passing I'm not sure how confident I am that this patch won't break some undocumented behavior :cry:

**Comment by conzett** [comment]
@kuldeepaggarwal I'm taking another look at this trying to shore up a few specs that seem to be missing and looking at fixing similar parsing issues with arrays. Hoping to have something next week :thumbsup:

**Comment by rthbound** [comment]
@conzett how's it coming? Any PRs in the works?

**Comment by conzett** [comment]
@rthbound Yes still in the works, sorry for the radio silence. We have a feature that we're shipping soon that needs this so it's definitely slated to be completed :thumbsup:

**Comment by rthbound** [comment]
@conzett excellent... sorry to bug you about it, I'm just so excited :heart_eyes_cat:

**Comment by jeremy** [comment]
Regression @ https://github.com/rack/rack/pull/1058#issuecomment-213815781
