### ISSUE TITLE
Rack::Auth::Basic::Request#inspect raise error

### ISSUE THREAD

**Issue by wafcio** [rack/rack#952]
When env doesn't have "HTTP_AUTHORIZATION" key then
```
auth = Rack::Auth::Basic::Request.new(env)
auth.inspect
```

inspect method raise error:

```
     NoMethodError:
       undefined method `split' for nil:NilClass
```

I think that problem can be here:
https://github.com/rack/rack/blob/master/lib/rack/auth/abstract/request.rb#L20

**Comment by jeremy** [comment]
Designed to check whether `#provided?` before operating on the auth request. Think it'd be better to be resilient, though. Worth a PR!

**Comment by wafcio** [comment]
In my opinion inspect metod should be available all time without raise error.
