### ISSUE TITLE
Parsing querystring with `foo[]bar` gives unexpected hash

### ISSUE THREAD

**Issue by boffbowsh** [rack/rack#964]
Parsing a querystring of `?foo[]bar` gives a hash of `{"foo"=>[{"bar"=>nil}]}`, which is unexpected and undocumented.

In order to generate that hash from a querystring, I would expect to provide `?foo[][bar]`, which also works.

I'd expect `?foo[]bar` to return `{"foo[]bar" => nil}`. 

For reference, python's `urlparse`:

``` python
>>> parse_qs('foo[]bar', True)
{'foo[]bar': ['’]} 
```

Is this expected behaviour?

**Comment by ioquatix** [comment]
Thanks for your contribution, but we are not going to change this, please see the original bug report for details.

**Comment by boffbowsh** [comment]
Which original bug report?

**Comment by ioquatix** [comment]
Sorry, I meant PR: https://github.com/rack/rack/pull/997
