### ISSUE TITLE
Renaming showexceptions.rb breaks Sinatra

### ISSUE THREAD

**Issue by plerohellec** [rack/rack#978]
This commit renames rack/showexceptions.rb into rack/show_exceptions.rb:
https://github.com/rack/rack/commit/857641dab255dbec490fead1d3a0f1ff999b2137

It breaks Sinatra because it requires the file with the old name (https://github.com/sinatra/sinatra/blob/master/lib/sinatra/show_exceptions.rb). Rails 5 apps will not be able to run engines with a Sinatra server, for example: Resque and Sidekiq.

**Comment by arthurnn** [comment]
should be this be fixes there or here? I guess if thats a new file/api they need to update the call

**Comment by djsegal** [comment]
:+1:

**Comment by stevebissett** [comment]
I see this issue was closed in 2015, but I'm experiencing this problem trying to add Resque to a Rails 5 app. 

How would I be able to make this work?

**Comment by rafaelfranca** [comment]
This should be fixed now with sinatra 2 beta.
