### ISSUE TITLE
Add 451 status code

### ISSUE THREAD

**Issue by colindean** [rack/rack#987]
https://github.com/rack/rack/blob/96ae9b9fed8d6809383b6f48a5884437e76f8ca4/lib/rack/utils.rb#L506 shows that it's not there, but that the list there is dependent on IANA's list. [HTTP 451 was finalized today](https://datatracker.ietf.org/doc/draft-ietf-httpbis-legally-restricted-status/?include_text=1) and should be publicized and everything updated in the coming days.

**Comment by colindean** [comment]
Could also add a `censored?` helper.

**Comment by jeremy** [comment]
See #985

**Comment by colindean** [comment]
Haha I searched issues but not PRs :-1: 

Thanks!
