### ISSUE TITLE
template in Rack::ShowExceptions works incorrectly when ParameterTypeError is raised. 

### ISSUE THREAD

**Issue by rrott** [rack/rack#991]
According to the following doc http://www.rubydoc.info/github/rack/rack/master/Rack/ShowExceptions

> Rack::ShowExceptions catches all exceptions raised from the app it wraps. It shows a useful backtrace with the sourcefile and clickable context, the whole Rack environment and the request data.

This feature does not work correctly and renders exception message in plain text in case of **Rack::QueryParser::ParameterTypeError**.
See attached screenshots:
![screenshot 2015-12-24 18 25 38](https://cloud.githubusercontent.com/assets/746383/11996751/cf9b8e2a-aa72-11e5-8a75-bc0348759df2.png)

It expected to look like:
![screenshot 2015-12-24 18 25 53](https://cloud.githubusercontent.com/assets/746383/11996752/d1c58f0c-aa72-11e5-9011-cef047b6ae18.png)
it is also true for **Rack::QueryParser::PInvalidParameterError** and probably other exceptions.

Issue caused by **TEMPLATE** that tries to GET/POST incorrect url once again just to show "Request information". Because of this a new Rack::QueryParser::ParameterTypeError is raised and templete-less page is rendered.

Affected code is the following:
https://github.com/rack/rack/blob/master/lib/rack/show_exceptions.rb#L288-L319

> <% if req.GET and not req.GET.empty? %>
> 
> ...
> 
> <% req.GET.sort_by { |k, v| k.to_s }.each { |key, val| %>
> 
> ...
> 
> <% if req.POST and not req.POST.empty? %>
> 
> ...
> 
> <% req.POST.sort_by { |k, v| k.to_s }.each { |key, val| %> 

As you can see it does several extra GET and POST calls in this template.

**Comment by jkowens** [comment]
I don't think this is actually an issue since Rack apps should rescue `Rack::Utils::ParameterTypeError` and `Rack::Utils::InvalidParameterError` and then return a 400 status.

**Comment by jeremyevans** [comment]
I agree, this is a bug in Rack::ShowExceptions.  I'll submit a pull request to fix it.
